- ts/packages/agents/desktop/README.md
- ts/packages/agents/desktop/package.json
- ts/packages/agents/desktop/src/agent/desktopActionHandler.ts
- ts/packages/agents/desktop/src/main.ts
- ts/packages/agents/desktop/src/programNameIndex.ts
- ts/packages/dispatcher/src/handlers/configCommandHandlers.ts
- ts/packages/shell/src/main/index.ts
Usability improvement for the desktop agent.
- desktop app agent automatically start the `autoShell` process without a extra step of `pnpm run start` in the desktop directory.
- Currently, there is no reason that the desktop controller (`autoShell`) needs to be a singleton process.
- Remove the websocket shim, and just implement the agent to directly manage it's only `autoShell` process.
- Automatically error and disable desktop agent if `autoShell` isn't built. 
- Save the program name index embedding to be reuse later in the typeagent profile storage. (i.e. shared across sessions), instead of recalculating it on every launch
> Improve desktop agent usability.

- ts/examples/siteSchemas/src/common/connector.ts
- ts/packages/agentSdk/src/agentInterface.ts
- ts/packages/agents/browser/src/agent/actionHandler.mts
- ts/packages/agents/browser/src/agent/browserConnector.mts
- ts/packages/agents/browser/src/extension/serviceWorker.ts
- ts/packages/agents/chat/src/chatResponseHandler.ts
- ts/packages/dispatcher/src/action/actionHandlers.ts
- ts/packages/dispatcher/src/agent/agentProcess.ts
- ts/packages/dispatcher/src/agent/agentProcessShim.ts
- ts/packages/dispatcher/src/agent/agentProcessTypes.ts
- Browser should use their own id to track calls
- Add `performanceMark` to `ActionContext`.
> Remove requestId access in agents

- ts/packages/dispatcher/src/handlers/common/interactiveIO.ts
- ts/packages/shell/src/preload/electronTypes.ts
> Cleanup unused parameter

- ts/examples/playground/src/main.ts
- ts/packages/aiclient/src/models.ts
- ts/packages/aiclient/src/openai.ts
- ts/packages/cli/src/commands/prompt.ts
- ts/packages/commonUtils/src/jsonTranslator.ts
The `completeStream` API should consistently return a "Result" so that it can detect error, instead of an async iterator.
> Fix model completeStream API to handle error

- ts/packages/dispatcher/src/action/actionHandlers.ts
- ts/packages/dispatcher/src/agent/agentConfig.ts
- ts/packages/dispatcher/src/agent/inlineAgentHandlers.ts
- ts/packages/dispatcher/src/handlers/common/appAgentManager.ts
- ts/packages/dispatcher/src/handlers/common/commandHandlerContext.ts
- ts/packages/dispatcher/src/handlers/configSpotifyCommandHandlers.ts
- ts/packages/dispatcher/src/handlers/requestCommandHandler.ts
- ts/packages/dispatcher/src/handlers/sessionCommandHandlers.ts
- ts/packages/shell/src/renderer/src/speech.ts
- Clean up the code and move all agents enable/disable state management into `AppAgentManager`.
- Defer instantiating app agent until it is enabled.
- Update app agent enable/disable (and therefore instantiation) in parallel.   Allow process to be spawn and started in parallel in out of proc mode, reduce the impact to load time.
> Enable separate agent process by default

- ts/packages/cli/src/commands/constructions.ts
- ts/packages/cli/src/commands/data/add.ts
- ts/packages/cli/src/commands/data/regenerate.ts
- ts/packages/cli/src/commands/data/stat.ts
- ts/packages/cli/src/commands/interactive.ts
- ts/packages/cli/src/commands/run/explain.ts
- ts/packages/cli/src/commands/run/request.ts
- ts/packages/cli/src/commands/run/translate.ts
- ts/packages/cli/src/commands/schema.ts
- ts/packages/dispatcher/src/agent/agentConfig.ts
- ts/packages/dispatcher/src/agent/agentProvider.ts
- ts/packages/dispatcher/src/command.ts
- ts/packages/dispatcher/src/handlers/common/appAgentManager.ts
- ts/packages/dispatcher/src/handlers/common/commandHandlerContext.ts
- ts/packages/dispatcher/src/handlers/configCommandHandlers.ts
- ts/packages/dispatcher/src/handlers/requestCommandHandler.ts
- ts/packages/dispatcher/src/handlers/sessionCommandHandlers.ts
- ts/packages/dispatcher/src/index.ts
- ts/packages/dispatcher/src/session/session.ts
- ts/packages/dispatcher/src/translation/actionInfo.ts
- ts/packages/dispatcher/src/translation/agentTranslators.ts
- ts/packages/dispatcher/src/translation/unknownSwitcher.ts
- ts/packages/dispatcher/src/utils/loadSchemaConfig.ts
- ts/packages/dispatcher/src/utils/test/testData.ts
- ts/packages/dispatcher/test/construction.spec.ts
- ts/packages/dispatcher/test/constructionCacheTestCommon.ts
- ts/packages/dispatcher/test/translate.test.ts
Move away from globals, and move to wrapping AppAgent loading in a provider. 
This will prepare for host to inject their own app agent, and also alternative implementation that provide different loading mechanism.
> App Agent provider infrastructure

- ts/packages/agentSdk/src/memory.ts
- ts/packages/agents/calendar/src/calendarActionHandler.ts
- ts/packages/dispatcher/src/action/actionHandlers.ts
- ts/packages/dispatcher/src/handlers/common/chatHistory.ts
- ts/packages/dispatcher/src/handlers/common/chatHistoryPrompt.ts
- ts/packages/dispatcher/src/handlers/requestCommandHandler.ts
Remove ImpressionInterpreter because it doesn't work across process boundary when agent is running out of proc.
Since it has minimal use right now, just change it to precompute the value that is needed for the dispatcher (instead of delay calling to interpret). We can design something different if there are additional need.
> Remove impression interpreter

- ts/packages/dispatcher/src/handlers/requestCommandHandler.ts
- ts/packages/shell/src/main/index.ts
- ts/packages/shell/src/preload/index.ts
- ts/packages/shell/src/renderer/src/settingsView.ts
- ts/packages/shell/src/renderer/src/tts.ts
In the render process the order of message processing send from the main process and invoke completion can be out of order.
That make some of the display message for action comes after the `processShellRequest` is finished.
In the tts case, that means the content is not spoken.
Change from using `invoke` to just message, so that (in theory and manual testing) that the completion of `processShellRequest` will be in the same order as other message.
Also
- fix the case where the browser voices get loaded after the setting view is construction.
- chat view get the tts when the settings are loaded.
> Shell: switch processShellRequest from invoke to just message response/reply

- ts/packages/shell/src/renderer/src/chatView.ts
- ts/packages/shell/src/renderer/src/main.ts
When streaming chat generate text, it doesn't auto scroll to content.
Change how we enable "auto scroll":
- Auto scroll to the bottom by default.
- Stop auto scrolling if user scroll away.
- Resume auto scroll on a new request.
> Shell: fix auto scroll on streaming

- ts/packages/dispatcher/src/handlers/common/appAgentManager.ts
When checking if a translatorName exists, it should look at the translator configs instead of the app agent map.
> Fix sub domain activation

- ts/.vscode/settings.json
- ts/packages/agentSdk/README.md
- ts/packages/cli/src/commands/constructions.ts
- ts/packages/cli/src/commands/data/add.ts
- ts/packages/cli/src/commands/data/diff.ts
- ts/packages/cli/src/commands/data/list.ts
- ts/packages/cli/src/commands/data/regenerate.ts
- ts/packages/cli/src/commands/data/split.ts
- ts/packages/cli/src/commands/data/stat.ts
- ts/packages/cli/src/commands/interactive.ts
- ts/packages/cli/src/commands/run/explain.ts
- ts/packages/cli/src/commands/run/request.ts
- ts/packages/cli/src/commands/run/translate.ts
- ts/packages/cli/src/commands/schema.ts
- ts/packages/dispatcher/package.json
- ts/packages/dispatcher/src/action/actionHandlers.ts
- ts/packages/dispatcher/src/dispatcher/dispatcher.ts
- ts/packages/dispatcher/src/handlers/common/commandHandlerContext.ts
- ts/packages/dispatcher/src/index.ts
- ts/packages/dispatcher/src/internal.ts
- ts/packages/shell/src/main/index.ts
- ts/packages/shell/src/preload/electronTypes.ts
- ts/packages/shell/src/preload/index.ts
- ts/packages/shell/src/renderer/src/chatView.ts
- Clean up main dispatcher API, hide internal behind an interface
- Expose internals via `agent-dispatcher/internal` exports.
- Fix `initialCommandHandlerContext` call from the CLI, missing the new `hostSettings` parameter.
- Clean up more of the NYI `partialInput` code in preparation to re-implementing them.
> Dispatcher API

- ts/packages/agentSdk/README.md
- ts/packages/agentSdk/src/agentInterface.ts
- ts/packages/agentSdk/src/index.ts
- ts/packages/dispatcher/src/agent/agentConfig.ts
- ts/packages/dispatcher/src/agent/agentProvider.ts
- ts/packages/dispatcher/src/command.ts
- ts/packages/dispatcher/src/handlers/common/appAgentManager.ts
- ts/packages/dispatcher/src/handlers/common/commandHandlerContext.ts
- ts/packages/dispatcher/src/handlers/constructionCommandHandlers.ts
- ts/packages/dispatcher/src/handlers/requestCommandHandler.ts
- ts/packages/dispatcher/src/translation/agentTranslators.ts
- ts/packages/shell/src/main/agent.ts
- Renames
- `TopLevelTranslatorConfig`  -> `AppAgentManifest`
- `HierarchicalTranslatorConfig` -> `TranslatorDefinition`
- Add type name `SchemaDefinition` to the schema field in `TranslatorDefinition`
-  Clean up unused fields in `SchemaDefinition`
- Make naming of `AppAgentManager` more consistent.
> Cleanup and rename

- ts/packages/dispatcher/src/handlers/common/commandHandlerContext.ts
PR #131 accidentally remove the code to initialize the "transient" translator state.
Reintroduced the code.
> Fix transient translator toggle

- ts/packages/shell/src/renderer/src/chatView.ts
DOMPurify was stripping target attributes so any links in the shell were opening within the shell browser window.
> Updated dompurify to not strip "target" attributes.

- ts/packages/dispatcher/src/action/actionHandlers.ts
- ts/packages/dispatcher/src/handlers/requestCommandHandler.ts
- ts/packages/shell/src/renderer/src/main.ts
- Need to capture the right requestId now that requestIO does not automatically use the captured requestIO when forwarding notifications.
- session context's notify need to pass in `undefined` for the requestId (the parameter was missing)
- Fix the content type for the notification displays.
> Fix app event and explained notification issues

- ts/packages/shell/src/main/shellSettings.ts
- ts/packages/shell/src/main/shellSettingsType.ts
- ts/packages/shell/src/renderer/assets/styles.less
- ts/packages/shell/src/renderer/src/chatView.ts
- ts/packages/shell/src/renderer/src/settingsView.ts
- ts/pnpm-lock.yaml
Hide the perf metrics by default and show only on hover.
Add `devUI` shell settings to allow it always show the perf metrics  (any additional dev time UI can be added under that flag in the future).
> Shell dev UI mode

- ts/packages/dispatcher/src/handlers/common/appAgentManager.ts
Fix the problem where dispatcher session context didn't get reinitialized on `@session new`
> Mark commands as disabled as well when closing all session contexts

- ts/packages/agents/code/README.md
- ts/packages/coda/README.md
- ts/packages/coda/src/handleCodeEditorActions.ts
- ts/packages/dispatcher/src/agent/agentProcessShim.ts
- ts/packages/dispatcher/src/agent/agentProcessTypes.ts
- Fix `AgentContextCallFunctions` function signatures for setDisplay and appendDisplay to use content instead of message
- Fix typo in code agent handler
- Minor readme update.
> Fix marshalling issue that caused the cli/shell to crash when running the vscode agent

- ts/packages/dispatcher/src/action/actionHandlers.ts
- ts/packages/dispatcher/src/handlers/common/commandHandlerContext.ts
- ts/packages/dispatcher/src/session/session.ts
Also fix an issue where "translator" overrides get overwritten on load when "undefined" initialize option is passed in.
> Prevent action context from being used after action is done

- ts/packages/agentSdk/src/agentInterface.ts
- ts/packages/agentSdk/src/helpers/commandHelpers.ts
- ts/packages/agentSdk/src/index.ts
- ts/packages/agents/code/src/codeActionHandler.ts
- ts/packages/commonUtils/src/rpc.ts
- ts/packages/dispatcher/src/agent/agentProcess.ts
- ts/packages/dispatcher/src/agent/agentProcessShim.ts
- ts/packages/dispatcher/src/agent/agentProcessTypes.ts
Improve some of the `any` typing.
Add type on the rpc `invoke` and `call` functions, to ensure the RPC calls are using the right param structures.
> Improve Typing

- ts/packages/shell/src/main/index.ts
Add back Ctrl+0 to reset zoom now that the menu is gone.
> Shell: Reset Zoom

- ts/packages/agents/player/src/agent/playerHandlers.ts
The check should be "all query terms" are valid, instead of "any one of the query terms are valid"
> Fix player wildcard validation with multiple queries

- ts/packages/dispatcher/src/translation/unknownSwitcher.ts
we should try hard to get chat to be selected on the first pass, but there are some tough cases like "mares eat oats and does eat oats..." where the LLM decides it's not sure enough about chat
> add chat into schemas considered by switcher

- ts/packages/agents/browser/src/agent/actionsSchema.mts
- ts/packages/agents/browser/src/agent/commerce/schema/userActions.mts
- ts/packages/agents/browser/src/electron/agentActivation.ts
- ts/packages/agents/browser/src/extension/contentScript.ts
- ts/packages/shell/src/preload/webView.ts
- Added actions to reload page and close window for inline browser scenarios
- Updated crossword schema caching in local storage
- Add logic to disable transient agent when inline browser window is closed
> Fixing gaps in crossword and commerce automation in inline browser

- ts/packages/knowledgeProcessor/test/conversation.spec.ts
Use `tmpdir` instead of root of the drive.
> Fix EACCES: permission denied, mkdir '/data' in conversation tests

- ts/packages/agentSdk/src/agentInterface.ts
- ts/packages/agentSdk/src/helpers/parameterHelpers.ts
- ts/packages/agentSdk/test/flags.spec.ts
- ts/packages/agents/browser/src/agent/manifest.json
- ts/packages/agents/calendar/src/calendarManifest.json
- ts/packages/agents/chat/src/chatManifest.json
- ts/packages/agents/code/src/codeManifest.json
- ts/packages/agents/desktop/src/manifest.json
- ts/packages/agents/email/src/emailManifest.json
- ts/packages/agents/greeting/src/greetingManifest.json
- ts/packages/agents/image/src/imageManifest.json
- ts/packages/agents/list/src/listManifest.json
- ts/packages/agents/photo/src/photoManifest.json
- ts/packages/agents/player/src/agent/playerCommands.ts
- ts/packages/agents/player/src/agent/playerManifest.json
- ts/packages/dispatcher/data/config.json
- ts/packages/dispatcher/src/agent/inlineAgentHandlers.ts
- ts/packages/dispatcher/src/command.ts
- ts/packages/dispatcher/src/handlers/common/appAgentManager.ts
- ts/packages/shell/src/main/agent.ts
- Add app agent description and show it with "@help"
- Print usage and parameter description with "@help"
Also:
- Add agent name in partial completion at first level "@"
- Detect duplicate flags when it is not a multiple flag.
- Simplified `parseParams` by reusing `resolveFlags`, improve quote handling (support starting with both " or ' after a space)
> Improve help and command usage using the parameter definitions

- ts/packages/agentSdk/src/helpers/commandHelpers.ts
- ts/packages/agentSdk/src/helpers/parameterHelpers.ts
- ts/packages/dispatcher/src/handlers/common/appAgentManager.ts
- ts/packages/dispatcher/src/handlers/configCommandHandlers.ts
- ts/packages/dispatcher/src/handlers/constructionCommandHandlers.ts
- ts/packages/dispatcher/src/handlers/sessionCommandHandlers.ts
This is the last of the "NoParse" commands, so removing the option.
Also fix the `isCommandEnabled` state for partial completion.
> Use declarative parameters for config model sets.

- ts/packages/cache/src/explanation/requestAction.ts
- ts/packages/commonUtils/src/command.ts
- ts/packages/dispatcher/src/handlers/common/interactiveIO.ts
- ts/packages/dispatcher/src/handlers/requestCommandHandler.ts
- ts/packages/dispatcher/src/translation/actionInfo.ts
- ts/packages/shell/src/main/index.ts
- ts/packages/shell/src/preload/electronTypes.ts
- ts/packages/shell/src/preload/index.ts
- ts/packages/shell/src/renderer/assets/styles.less
- ts/packages/shell/src/renderer/src/ActionCascade.ts
- ts/packages/shell/src/renderer/src/chatView.ts
- ts/packages/shell/src/renderer/src/main.ts
- ts/packages/shell/src/renderer/src/messageContainer.ts
- Initial wiring of propose action using existing `ActionCascade`. 
- Finishing the field editing UI in ActionCascade. 
- Add per field edit button.
- Accept/Replace flow and send back for replacement.
- TODO: adding and deleting of optional fields and array items, switching translator and action name.
Additional cleanup:
- Separate the data vs schema in the action template.
- Separate proposeAction and askYesNo.
- Remove the dispatcher driven SearchMenu and Action Command.  For additional action templates, will switch to having host request action templates when we need it.
> Enable field edits and action replacement.

- ts/packages/dispatcher/src/handlers/requestCommandHandler.ts
- ts/packages/shell/src/renderer/assets/styles.less
- ts/packages/shell/src/renderer/src/ActionCascade.ts
- ts/packages/shell/src/renderer/src/messageContainer.ts
Add capability to add and delete optional fields and array entries.
Additionally:
- Add option to cancel the action entirely.
- Use different input/drop-box for different field types.
- Refactor the `ActionCascade` and break it into different kind of rows
> Shell translation confirm/replace flow: add/delete array entries and optional properties

- ts/packages/dispatcher/src/handlers/common/appAgentManager.ts
- ts/packages/dispatcher/src/handlers/requestCommandHandler.ts
- ts/packages/dispatcher/src/index.ts
- ts/packages/dispatcher/src/translation/actionInfo.ts
- ts/packages/dispatcher/src/translation/actionTemplate.ts
- ts/packages/dispatcher/src/translation/unknownSwitcher.ts
- ts/packages/shell/src/renderer/src/fieldEditor.ts
- Instead of getting all action info to generate the template sequence, do a look up instead.
- Change the underlying data structure and API to enable the look up.
- Also rename the ActionInfo's parameter type names
> Look up ActionInfo

- ts/packages/shell/src/main/agent.ts
- ts/packages/shell/src/main/index.ts
- ts/packages/shell/src/main/shellSettings.ts
- Remove previous code that opened inline browser as a separate browserwindow
- Resize main window when browser pane is opened or closed. Also resize the chat and browser views if the window is resized
- Update calls that would post message to mainWindow.webContents to now post to chatView.webContents
> Launch inline browser as a view in the current browserwindow

- ts/examples/playground/src/main.ts
Just call `lookupAnswersOnWeb` for each lookup in the response.
Nothing fancy (could fork off queries in parallel, but usually there's just one lookup anyway).
> Add web search to playground

- ts/examples/playground/src/main.ts
- ts/packages/interactiveApp/src/interactiveApp.ts
At the start of a session, there's a message `Type quit OR exit to exit`.
However, if you type `quit`, it's an error.
The reason is that this is a command prefixed with `@` (though handled specially in the command parser).
My fix changes this to `Type @quit OR @exit to exit`,
taking the configured command prefix and list of stopcommands into account.
While I was here, I also fixed a missing quote in the final welcome message (`'hello`).
> Fix for 'Type quit OR exit to exit' which omits the @ prefix

- ts/packages/shell/electron.vite.config.mts
- ts/packages/shell/src/main/index.ts
- ts/packages/shell/src/renderer/viewHost.html
- Add hostHtml page with a divider element. This is loaded into the mainwindow
- Enable divider to update relative width of the chatview and browserview when both are visible. Hide divider if browserview is not visible.
> Enable resizing chat view and browser view when they are both visible

- ts/packages/shell/src/main/index.ts
- F12 now works again, and will bring up separate devtools panels for chatView and browserView depending on which one the user was on when they hit F12.
- Zoom in/out works with both keyboard shortcuts and mouse scrollwheel. Users can independently zoom on the chat window or the browser view.
> Fix devtools and zoom regressions in shell

- ts/packages/shell/src/main/index.ts
- ts/packages/shell/src/main/shellSettings.ts
- Use getContentBounds instead of getBounds for the view contents.
- Use "resize" event in linux instead of "will-resize"
> Fix chat view size in WSL/OSX, replace custom margin for windows and not resizing in WSL.

- ts/packages/shell/src/renderer/assets/styles.less
- ts/packages/shell/src/renderer/src/partial.ts
- ts/packages/shell/src/renderer/src/search.ts
- ts/packages/shell/src/renderer/src/templateEditor.ts
Reducing the amount of mouse click needed to edit the schema:
- Remove edit save/cancel button, just auto save when moved off the field
- "Enter" key will move to the next field to edit.
- Track editing field on array reordering, and default to next scalar field on array entry deletion.
- Always show optional fields that can be filled in fill in (instead of clicking the + side and choose the field to add)
- Use search menu for string-union fields. (in preparation for field auto-complete as well)
- Buttons are lightgray except on hover or the field it is editing.
> Shell confirm/replace flow: Improve template editor UI

- ts/packages/dispatcher/src/handlers/common/appAgentManager.ts
- ts/packages/dispatcher/src/translation/actionTemplate.ts
- ts/packages/shell/src/renderer/assets/styles.less
- ts/packages/shell/src/renderer/src/search.ts
- ts/packages/shell/src/renderer/src/templateEditor.ts
- Search Menu can be selected by mouse.
- Search Menu select (mouse click or enter) will move to the next field.
- Schema refresh on field change will advance to the next field.
- Fix the bug of not able to get schema when the translator name is invalid.
- Fix the bug where schema doesn't refresh when changing action name when it was invalid before.
- Fix the UI bug where search menu should adopt the "missing" style when the optional field is empty
- Close the search menu when input lose focus.
> Shell confirm/replace flow: Allow search menu to be clicked and serval bug fixes

- ts/packages/shell/src/renderer/src/templateEditor.ts
An undefined object value in the data is ok, as we generate the value based on it field.   Object property will be marked as error in that case.  For object without property, it shouldn't mark as an error since we will create an empty object.
> Shell confirm/replace flow: Fix bug of empty object marked as error

- ts/examples/chat/src/codeChat/codeChat.ts
- ts/examples/chat/src/codeChat/commandTransformer.ts
- ts/examples/chat/src/memory/chatMemory.ts
Add `dispatch` and `transformAndDispatch` methods to `CommandTransformer`.
- `dispatch()` takes the output from `transform()` and dispatches (this used to be in `inputHandler()`).
- `transformAndDispatch()` calls `transform()` and then `dispatch()`.
These two return an error message if something went wrong, else `undefined`.
Also:
- Make the non-failure return type of `transform()` into `NamedArgs`, which is assumed everywhere else anyway.
- Combined the construction and completion of `CommandTransformer`.
- Move its construction and the slimmed-down `inputHandler()` towards the end of `runCodeChat`.
- Remove some overenthusiastic `| NamedArgs` from various signatures.
- Strictly type the TypeChatJsonTransformer to use `<NamedArgs>`
> Clean up the command transformer

- ts/examples/chat/src/codeChat/codeChat.ts
- ts/examples/chat/src/codeChat/codeMemory.ts
This adds the same inputHandler pattern to codeMemory.ts that I added to codeChat.ts.
Also move the addStandardHandlers in the latter file to the top, where it used to be.
> Add command transformer to codeMemory.ts

- ts/packages/agents/browser/src/electron/agentActivation.ts
- ts/packages/agents/browser/src/extension/serviceWorker.ts
- ts/packages/shell/src/main/index.ts
- ts/packages/shell/src/preload/webView.ts
- Skip iframes that are unlikely to contain user-visible html e.g. those with src="about:blank", those that are hidden or have 0 width and height etc.
- Enable exisging commerce schemas to work for instacart
- Add user agent string to inlineBrowser view
> Speed up HTML extraction in inline browser

- ts/packages/cache/src/explanation/explainer.ts
- ts/packages/cache/src/explanation/v5/propertyExplainationV5.ts
- ts/packages/cache/src/explanation/v5/subPhraseExplanationV5.ts
- ts/packages/cache/src/index.ts
- ts/packages/cli/src/commands/data/regenerate.ts
- ts/packages/dispatcher/test/data/calendar/v5/complex.json
- ts/packages/dispatcher/test/data/calendar/v5/simple.json
- ts/packages/dispatcher/test/data/player/v5/changeVolume.json
- ts/packages/dispatcher/test/data/player/v5/full.json
- ts/packages/dispatcher/test/data/player/v5/nextAction.json
- ts/packages/dispatcher/test/data/player/v5/param.json
- ts/packages/dispatcher/test/data/player/v5/pauseAction.json
- ts/packages/dispatcher/test/data/player/v5/previousAction.json
- ts/packages/dispatcher/test/data/player/v5/resumeAction.json
- ts/packages/dispatcher/test/data/player/v5/searchTracks.json
- ts/packages/dispatcher/test/data/player/v5/simple.json
GPT4o has the propensity to explain empty parameters, even thought that is not a property listed.
Add instruction to explicitly ignore explaining empty properties.
Also:
- Add flag `--request` to command `cli data regenerate` to filter to specified request pattern
-  clean up unused code path.
> Explainer: add instruction to ignore explaining empty parameters

- ts/packages/agents/browser/src/extension/contentScript.ts
- ts/packages/shell/src/main/index.ts
- ts/packages/shell/src/preload/webView.ts
- Fix bug where zoom level was not getting updated in the window title
- use webFrame to enable the zoom browser action to work in the inline browser
> Update zoom handling for inline browser

- ts/packages/agents/browser/src/electron/agentActivation.ts
- ts/packages/agents/browser/src/electron/manifest.json
- ts/packages/shell/package.json
- ts/packages/shell/src/main/browserIpc.ts
- ts/packages/shell/src/main/index.ts
- ts/packages/shell/src/main/shellSettings.ts
- ts/packages/shell/src/preload/webView.ts
- Some sites have content security policies that limit connections to a set of known domains. This was blocking the websocket connection on localhost. To fix this, I moved the websocket logic from render process to the main process.
- Improve robustness of site agent initialization for inline browser.  Use the "did-finish-load" event to detect when all frames in the inline browser are loaded.
> Update inline browser to support sites with strict CSPs

- ts/packages/agents/player/src/agent/playerHandlers.ts
- ts/packages/agents/player/src/client.ts
- ts/packages/agents/player/src/endpoints.ts
- ts/packages/agents/player/src/search.ts
- ts/packages/agents/player/src/trackCollections.ts
- When finding track and album, match the artist first and only match tracks of those artists.
- Apply expand movements heuristics to `playTrack` and `playGenre` Actions
- Clean up TrackCollection and play API.
> Music play: Expand movements

- ts/packages/agents/player/src/search.ts
- Don't use exact name match to prioritize which one is more likely to be the right artist.  Only use known and then popularity.
- Fix a bug that we should only expand movement tracks if it is not an exact match already.
- Limit the movement expansion.
> Music player: adjust heuristics

- ts/packages/cache/src/explanation/v5/propertyExplainationV5.ts
- ts/packages/cli/src/commands/run/explain.ts
- ts/packages/dispatcher/src/handlers/common/interactiveIO.ts
- ts/packages/dispatcher/src/handlers/requestCommandHandler.ts
- ts/packages/dispatcher/src/index.ts
- ts/packages/shell/src/main/index.ts
- ts/packages/shell/src/preload/electronTypes.ts
- ts/packages/shell/src/preload/index.ts
- ts/packages/shell/src/renderer/src/chatView.ts
- ts/packages/shell/src/renderer/src/main.ts
- ts/packages/shell/src/renderer/src/messageContainer.ts
- ts/packages/shell/src/renderer/src/messageGroup.ts
- ts/packages/shell/src/renderer/src/webSocketAPI.ts
- Disable entity constructions, those that reference context, and just let model handle them for now.
- Add notification when explanation error (like when there is a reference in the request)
> Disable entity constructions

- ts/packages/cache/src/explanation/v5/propertyExplanationSchemaV5WithContext.ts
Add instruction to make sure the explainer prefer matching property value from the request even if it is in the history.
> Explainer: prefer request over conversation history.

- ts/packages/dispatcher/src/action/actionHandlers.ts
- ts/packages/dispatcher/src/agent/inlineAgentHandlers.ts
- ts/packages/dispatcher/src/dispatcher/command.ts
- ts/packages/dispatcher/src/handlers/common/appAgentManager.ts
- ts/packages/dispatcher/src/handlers/common/commandHandlerContext.ts
- ts/packages/dispatcher/src/handlers/requestCommandHandler.ts
- ts/packages/dispatcher/src/translation/actionTemplate.ts
- ts/packages/dispatcher/src/translation/agentTranslators.ts
Also move the tracking of transient state into the `AppAgentManger`.
> Restrict `@action` translator completion to active ones

- ts/packages/cache/src/constructions/constructionMatch.ts
- ts/packages/cache/src/explanation/v5/propertyExplainationV5.ts
- ts/packages/cache/src/explanation/v5/subPhraseExplanationV5.ts
- ts/packages/cache/src/utils/language.ts
- ts/packages/dispatcher/test/construction.spec.ts
- ts/packages/dispatcher/test/data/player/v5/full.json
- Both explainer and cache matching will reject phrases that looks like reference.
- Initial reference phrases is probably overboard/has gaps, and will improve it overtime.
> Cache: Reject reference phrases

- ts/packages/cache/src/cache/cache.ts
- ts/packages/cache/src/constructions/constructionCache.ts
- ts/packages/cache/src/constructions/constructionMatch.ts
- ts/packages/cache/src/constructions/constructionPrint.ts
- ts/packages/cache/src/constructions/constructionValue.ts
- ts/packages/cache/src/constructions/constructions.ts
- ts/packages/cache/src/constructions/importConstructions.ts
- ts/packages/cache/src/explanation/explainer.ts
- ts/packages/cache/src/explanation/genericExplainer.ts
- ts/packages/cache/src/explanation/typeChatAgent.ts
- ts/packages/cache/src/explanation/v5/alternativesExplanationV5.ts
- ts/packages/cache/src/explanation/v5/explanationV5.ts
- ts/packages/cache/src/explanation/v5/propertyExplainationV5.ts
- ts/packages/cache/src/explanation/v5/subPhraseExplanationV5.ts
- ts/packages/cache/src/utils/language.ts
- ts/packages/cache/test/reference.spec.ts
- ts/packages/dispatcher/src/agent/agentConfig.ts
- ts/packages/dispatcher/test/construction.spec.ts
- ts/packages/dispatcher/test/constructionCacheTestCommon.ts
- ts/packages/dispatcher/test/data/player/v5/full.json
- Add option to disable reference rejection so that we can continue to purely test explanation/construction round trips without interference.
- Expand reference detection for possessive that are can be just part of the phrase.
> Explainer option to disable reference rejection

- ts/examples/viewList/package.json
- ts/examples/viewList/src/route/route.ts
- ts/examples/viewList/src/site/tsconfig.json
- ts/pnpm-lock.yaml
- Update the code to read the lists.json file from the latest session folder. Users can override this value by setting an environment variable when launching the viewList service.
> Set default file search path for lists visualization tool

- ts/packages/aiclient/src/openai.ts
- ts/packages/aiclient/src/tokenCounter.ts
- ts/packages/commonUtils/src/jsonTranslator.ts
- ts/packages/dispatcher/src/handlers/tokenCommandHandler.ts
- ts/packages/dispatcher/src/session/session.ts
- Implement streaming token count.
- Track count and max for token count for tags.
- Add type name to the tags for translators.
- Fix counting for tags (it was always counting twice the latest value)
- debug trace now include the translator type name.
> Streaming token count

- ts/packages/cache/src/cache/cache.ts
- ts/packages/cache/src/explanation/requestAction.ts
- ts/packages/cli/src/commands/run/explain.ts
- ts/packages/dispatcher/src/handlers/common/chatHistoryPrompt.ts
- ts/packages/dispatcher/src/handlers/requestCommandHandler.ts
- ts/packages/dispatcher/src/session/session.ts
If we fail to translate to the same result without history context, Then it is likely that the translation is context sensitive, and we shouldn't cache it.
> Explanation: Filter caching with contextless translation

- ts/packages/aiclient/src/models.ts
- ts/packages/aiclient/src/openai.ts
- ts/packages/commonUtils/src/incrementalJsonParser.ts
- ts/packages/commonUtils/src/jsonTranslator.ts
- ts/packages/dispatcher/src/handlers/common/chatHistoryPrompt.ts
- ts/packages/dispatcher/src/handlers/common/commandHandlerContext.ts
- ts/packages/dispatcher/src/handlers/requestCommandHandler.ts
- ts/packages/dispatcher/src/translation/agentTranslators.ts
The current method of extending the TypeChat translator to include history context for request prompt creation, and streaming callback on each translation invocation, makes the translator unable to handle multiple call at the same time.   Now that we use the agent translators to detect context usage for the explainer with will cause overlapping calls and might cause the override to go across the call and cause random errors.
Change the method of extending by:
- For agent translation, expand request prompt with chat history upfront using a wrapped `TypeAgentTranslator` before passing it to the TypeChat translator.
- For the streaming, it needs to pass the incremental parser to the model, and the only way to do so thru TypeChat is hiding it in the prompt premble.
Additional changes:
- …
> Fix translator override

- ts/examples/spelunker/src/codeDocSchema.ts
- ts/examples/spelunker/src/main.ts
- ts/examples/spelunker/src/pythonChunker.ts
- ts/examples/spelunker/src/pythonImporter.ts
New indexing approach:
Instead of asking a documenter to produce a comment for each chunk separately (and without other chunks as context),
ask a different documenter to produce comments for the whole file, but only at points where a chunk starts.
Then extract those comments and add them to the chunk to which they apply.
Use some hackery to pass the relevant comments (with correct line numbers, even!) to the code index
(so it no longer needs an LLM roundtrip to summarize the chunk).
I struggled a bit to get the chunk comments brief, but not too brief --
if you ask for "a paragraph" it explains the `@dataclass` decorator each time it is used. :-)
Also improve the search UX and logging a bit (maybe logging is a bit too verbose, we'll take it down later).
I believe that this improves the …
> Changed embedding tactics for chunks (again!)

- ts/examples/spelunker/package.json
- ts/examples/spelunker/src/chunker.py
- ts/examples/spelunker/src/dumper.py
- ts/examples/spelunker/src/main.ts
- ts/examples/spelunker/src/pythonChunker.ts
- ts/examples/spelunker/src/pythonImporter.ts
- ts/examples/spelunker/src/queryInterface.ts
- ts/examples/spelunker/src/sample.py.txt
- ts/packages/codeProcessor/src/codeIndex.ts
- ts/pnpm-lock.yaml
- Add -v/--verbose flag to command line
- Many logging improvements (but still no color)
- Catch errors when documenting a file (e.g. file too large)
- Introduce one-line "breadcrumb blobs" in chunks for sub-chunks, e.g. `def foo...`
- Switch to @-prefixed commands, e.g. @search --query "why is the sky blue" --maxHits 10 --minScore 0.7 --verbose false
> Spelunker omnibus PR: tweak indexing, logging, use interactiveApp

- ts/packages/cache/src/utils/language.ts
- Conjunctions and pronouns are also force to not merge and not use synonyms.
- Add more pronouns for reference detections.
> Constructions: detect additional pronouns and conjunction for explanation/merging 

- ts/examples/viewMarkdown/src/route/route.ts
- ts/examples/viewMarkdown/src/site/index.ts
- SSE treats newlines and colons as special characters. These characters are likely to appear in HTML, so we need to encode the HTML when sending it in a message.
> Fix encoding of HTML when sent in SSE

- ts/package.json
- ts/packages/agentSdk/src/command.ts
- ts/packages/agentSdk/src/helpers/commandHelpers.ts
- ts/packages/agents/calendar/src/calendarActionHandler.ts
- ts/packages/agents/email/src/emailActionHandler.ts
- ts/packages/agents/player/src/agent/playerCommands.ts
- ts/packages/cache/src/cache/cache.ts
- ts/packages/cache/src/explanation/genericExplainer.ts
- ts/packages/cache/src/explanation/v5/propertyExplainationV5.ts
- ts/packages/cache/src/index.ts
- ts/packages/cli/src/commands/interactive.ts
- ts/packages/cli/src/commands/run/explain.ts
- ts/packages/cli/src/commands/run/request.ts
- ts/packages/dispatcher/src/agent/inlineAgentHandlers.ts
- ts/packages/dispatcher/src/dispatcher/command.ts
- ts/packages/dispatcher/src/dispatcher/commandHelp.ts
- ts/packages/dispatcher/src/handlers/common/commandHandler.ts
- ts/packages/dispatcher/src/handlers/common/commandHandlerContext.ts
- ts/packages/dispatcher/src/handlers/configCommandHandlers.ts
- ts/packages/dispatcher/src/handlers/constructionCommandHandlers.ts
- ts/packages/dispatcher/src/handlers/historyCommandHandler.ts
- ts/packages/dispatcher/src/handlers/notifyCommandHandler.ts
- ts/packages/dispatcher/src/handlers/randomCommandHandler.ts
- ts/packages/dispatcher/src/handlers/requestCommandHandler.ts
- ts/packages/dispatcher/src/handlers/serviceHost/localWhisperCommandHandler.ts
- ts/packages/dispatcher/src/handlers/serviceHost/serviceHostCommandHandler.ts
- ts/packages/dispatcher/src/handlers/sessionCommandHandlers.ts
- ts/packages/dispatcher/src/handlers/tokenCommandHandler.ts
- ts/packages/dispatcher/src/session/session.ts
- ts/packages/shell/src/main/agent.ts
- Add flags to control filtering for explainer  `@config explainer filter *`
- `... multiple`: don't explain multiple actions (default: enabled)
- `... reference list`: don't explain action with property value in the list of reference words (default: enabled)
- `... reference value`: don't explain action whose property value isn't found in the request (default: enabled)
- ``...reference translation`: don't explain action whose result changed after retranslation with the LLM without history context (default: enabled)
- To toggle all filters
- `@config explainer filter`
- `@config explainer filter on`
- `@config explainer filter off`
- To toggle reference filters
- `@config explainer filter reference`
- `@config explainer filter reference on` 
- `@config explainer filter reference off` …
> Add flags to control filtering for explainer.

- ts/packages/dispatcher/data/config.json
- ts/packages/dispatcher/src/dispatcher/dispatcherAgent.ts
- ts/packages/dispatcher/src/dispatcher/schema/clarifyActionSchema.ts
- ts/packages/dispatcher/src/dispatcher/schema/dispatcherActionSchema.ts
- ts/packages/dispatcher/src/handlers/requestCommandHandler.ts
So that it can be disabled independently.
> Split the clarify action into a separate translator

- ts/packages/cache/src/explanation/v5/explanationV5.ts
- ts/packages/cache/src/explanation/v5/subPhraseExplanationSchemaV5.ts
They are usually not useful, and interfere with subphrase boundaries.
> Explainer: disable synonym generation for parameters

- ts/packages/cache/src/cache/cache.ts
- ts/packages/cache/src/constructions/constructionPrint.ts
- ts/packages/cache/src/constructions/matchPart.ts
- ts/packages/cache/src/constructions/transforms.ts
- ts/packages/cache/src/explanation/requestAction.ts
- ts/packages/cache/src/explanation/v5/explanationV5.ts
- ts/packages/cache/src/explanation/v5/propertyExplainationV5.ts
- ts/packages/cache/src/explanation/v5/subPhraseExplanationV5.ts
- ts/packages/cache/src/index.ts
- ts/packages/dispatcher/src/handlers/requestCommandHandler.ts
- ts/packages/dispatcher/test/construction.spec.ts
- ts/packages/dispatcher/test/constructionCacheTestCommon.ts
LLM might fix the diacritic mark for entity it knows about from the request.  It should be ok to just ignore those when matching user requests or comparing LLM output
> Ignore diacritic difference (on top of case) when comparing LLM output

- ts/examples/memoryProviders/src/sqlite/textTable.ts
- ts/examples/spelunker/src/pythonImporter.ts
- ts/examples/spelunker/src/queryInterface.ts
- ts/packages/knowledgeProcessor/src/knowledgeIndex.ts
This extends the TextTable interface and its two known implementations to support nearestNeighborsPairs, which returns scored pairs of (entry text, array of source ids) for the nearest matches.
I needed this for detailed logging what was going in. (I found that "ast" is somehow a universal attractor in embedding space!)
Also add some clarifying (for me!) comments to createTextIndex (in knowledgeIndex.js) and added some extra (redundant) types that made the meaning of various variables clearer to me (I was mightily confused by the two uses of strings, for entry values and for internal Ids created by the semantic index's put() method).
And some cleanup in spelunker (notably removing a special case to avoid double-scoring exact matches that was based on a misunderstanding) and of course use …
> [spelunker] Add nearestNeighborsPairs to TextTable and createTextIndex

- ts/examples/spelunker/src/pythonImporter.ts
This saves us from 429 errors on the embedding operations.
In practice a 1ms timeout is enough, but I figured I might as well keep trying a few more time with larger timeouts.
> [spelunker] Add exponential backoff to every index.put call

- ts/packages/cache/src/explanation/v5/explanationV5.ts
- ts/packages/cache/src/utils/language.ts
Optional phrases don't impact translation, so it is ok if it has closed class words, but only disallow it if it exactly matches the closed class words
> Constructions: Allow optional phrases to merge and use synonyms with closed class words

- ts/.vscode/launch.json
- ts/examples/chat/src/tests/test.ts
- ts/packages/typeagent/src/async.ts
- ts/packages/typeagent/src/index.ts
- ts/packages/typeagent/src/vector/semanticList.ts
- ts/packages/typeagent/src/vector/semanticMap.ts
- ts/packages/typeagent/src/vector/vectorIndex.ts
- ts/packages/typeagent/test/async.spec.ts
- ts/packages/typeagent/test/vector.vectorIndex.spec.ts
Semantic map & list:
* setMultiple and putMultiple now use Batching embedding Api
* Built in retry that goes beyond default retry at model level
* Generic "callWithRetry" function that retries any async function with exponential backoff.
* Unit tests
> Batching and retry support for Semantic map + list

- ts/examples/spelunker/src/chunkyIndex.ts
- ts/examples/spelunker/src/fileDocumenter.ts
- ts/examples/spelunker/src/pythonImporter.ts
- ts/examples/spelunker/src/queryInterface.ts
This lets us get rid of the whole "fake code documenter" concept and we are no longer dependent on code-processor at all.
(TODO: Refactor FileDocumenter now that it no longer needs to fit the CodeDocumenter interface.)
> [spelunker] Rationalize the index objects -- use TextIndex everywhere

- ts/examples/spelunker/src/chunkyIndex.ts
- ts/examples/spelunker/src/makeAnswerSchema.ts
- ts/examples/spelunker/src/makeQuerySchema.ts
- ts/examples/spelunker/src/pythonImporter.ts
- ts/examples/spelunker/src/queryInterface.ts
The new default query approach is as follows:
- Ask an LLM for suggested queries to send to each index, based on the user's query input.
- Execute those queries (this uses embeddings and is fast, especially after all the indexes are loaded and embeddings cached).
- Send their results, together with the chunks referenced, to another LLM, which is requested to answer the original question.
- Print the answer.
Note that there is no conversational memory -- each question is answered solely based on the indexed information.
Example session:
```
🤖> what is a breadcrumb
Answer (confidence 0.9):
In the context of the provided code, a breadcrumb is a flag associated with a
Blob instance. It indicates whether the blob should be ignored during the
reconstruction process. This flag is used to mark …
```
> [spelunker] Implement LLM-guided answering of questions about a code base

- ts/packages/cli/src/commands/run/request.ts
- ts/packages/cli/src/commands/run/translate.ts
Also
- explicit exit the process after `cli run request` and `cli run translate`
- `cli run request` don't explain by default.  Use `--explainer <name>` to enable it.
> Fix `cli run translate`.

- ts/packages/cli/src/commands/run/explain.ts
Also, disable actions and commands to avoid the expense of loading the agents.
> `cli run explain` disable filter by default

- ts/examples/playground/src/main.ts
- ts/packages/agents/greeting/src/greetingActionHandler.ts
- ts/packages/aiclient/src/azureSettings.ts
- ts/packages/aiclient/src/common.ts
- ts/packages/aiclient/src/index.ts
- ts/packages/aiclient/src/modelResource.ts
- ts/packages/aiclient/src/ollamaModels.ts
- ts/packages/aiclient/src/openai.ts
- ts/packages/aiclient/src/openaiSettings.ts
- ts/packages/aiclient/src/restClient.ts
- ts/packages/cli/src/commands/data/add.ts
- ts/packages/cli/src/commands/data/regenerate.ts
- ts/packages/cli/src/commands/interactive.ts
- ts/packages/cli/src/commands/prompt.ts
- ts/packages/cli/src/commands/run/request.ts
- ts/packages/cli/src/commands/run/translate.ts
- ts/packages/commonUtils/src/indexNode.ts
- ts/packages/dispatcher/src/dispatcher/command.ts
- ts/packages/dispatcher/src/handlers/common/commandHandlerContext.ts
- ts/packages/dispatcher/src/handlers/configCommandHandlers.ts
- ts/packages/dispatcher/src/handlers/randomCommandHandler.ts
- ts/packages/dispatcher/src/handlers/requestCommandHandler.ts
- ts/packages/dispatcher/src/handlers/sessionCommandHandlers.ts
- ts/packages/dispatcher/src/session/session.ts
Add ollama model support.  Their API and response are different then OAI.  Soadd a new provide and model implementation.
Add flags to control translation model for `cli run request` and `cli run translation` in addition to `cli interactive`
Change the commands `@config translation model <name>` to set translation model.  `@config explainer model <name>` to set the explainer model.
Also group other translation options and command under "translation" .
> Ollama support

- ts/packages/aiclient/src/ollamaModels.ts
Use the env var OLLAMA_USE_OAI_ENDPOINT = 0 to use the ollama native endpoints instead of the OAI compat endpoints.
> Ollama use OAI endpoints

- ts/packages/actionSchema/src/creator.ts
- ts/packages/actionSchema/src/generator.ts
- ts/packages/actionSchema/src/index.ts
- ts/packages/actionSchema/src/parser.ts
- ts/packages/actionSchema/src/type.ts
- ts/packages/actionSchema/test/regen.spec.ts
- ts/packages/cache/src/explanation/v5/alternativesExplanationV5.ts
- ts/packages/cache/src/explanation/v5/politenessGeneralizationV5.ts
- ts/packages/cache/src/explanation/v5/propertyExplainationV5.ts
- ts/packages/cache/src/explanation/v5/subPhraseExplanationV5.ts
- ts/packages/cache/src/tsconfig.json
- ts/packages/cli/src/commands/schema.ts
- ts/packages/commonUtils/src/jsonTranslator.ts
- ts/packages/dispatcher/src/handlers/configCommandHandlers.ts
- ts/packages/dispatcher/src/handlers/requestCommandHandler.ts
- ts/packages/dispatcher/src/translation/actionJsonValidator.ts
- ts/packages/dispatcher/src/translation/agentTranslators.ts
- ts/packages/dispatcher/src/translation/unknownSwitcher.ts
Implement dynamic schema create API.  Switch large assistant switcher to use it.
Also:
- refactor `createJsonTranslatorFromSchemaDef` to allow for creating translator with an alternate validator, in preparation for using action schema based validator.
- Stop adding the history system prompt section when there is no history.
- Simply createJsonTranslator* parameters with option object.
- Allow generation of schema that are not `Action`.
> Dynamic schema creation API

- ts/examples/spelunker/src/chunkyIndex.ts
- ts/examples/spelunker/src/main.ts
- ts/examples/spelunker/src/pythonImporter.ts
- ts/examples/spelunker/src/queryInterface.ts
- Add @chunk command to display individual chunks.
- Make @search just a verbose version of the same querying that happens when a non-command is executed.
- Add @import command that takes --fileName or --files (a file containing a list of files).
- Add @clearMemory to erase the spelunker part of the database.
- Do the expensive part of import (asking the model to write a summary for each chunk in a file) concurrently.
- Various other small improvements, refactorings, code moves etc.
> [spelunker] Many refactorings and improvements

- ts/examples/spelunker/src/pythonImporter.ts
- ts/examples/spelunker/src/queryInterface.ts
Limit context for answer generation to 20 chunks. This seems to work okay.
> [spelunker] Use TF*IDF, refactor processQuery, fix concurrency issues in embedChunk

- ts/packages/actionSchema/src/creator.ts
- ts/packages/actionSchema/src/generator.ts
- ts/packages/actionSchema/src/index.ts
- ts/packages/actionSchema/src/parser.ts
- ts/packages/actionSchema/src/type.ts
- ts/packages/actionSchema/src/utils.ts
- ts/packages/actionSchema/src/validate.ts
- ts/packages/actionSchema/test/regen.spec.ts
- ts/packages/agentSdk/README.md
- ts/packages/agentSdk/src/agentInterface.ts
- ts/packages/agentSdk/src/index.ts
- ts/packages/cli/src/commands/schema.ts
- ts/packages/dispatcher/src/agent/agentConfig.ts
- ts/packages/dispatcher/src/handlers/common/appAgentManager.ts
- ts/packages/dispatcher/src/handlers/common/commandHandlerContext.ts
- ts/packages/dispatcher/src/translation/actionSchema.ts
- ts/packages/dispatcher/src/translation/actionSchemaJsonTranslator.ts
- ts/packages/dispatcher/src/translation/actionTemplate.ts
- ts/packages/dispatcher/src/translation/agentTranslators.ts
- ts/packages/dispatcher/src/translation/multipleActionSchema.ts
- ts/packages/dispatcher/src/translation/unknownSwitcher.ts
- ts/packages/dispatcher/src/utils/loadSchemaConfig.ts
Inline switcher and multiple action schema to use dynamic action schema creation API, whether we use the in-memory validator or type script validate.   
Also, leveraging the above implemented a function to generate composite schema that is sent to the LLM (that includes the injected, inline switcher and multiple action) and wired that to `agent-cli schema --generated`.  It is not used in the actual action translation yet, and will be in a follow up PR.
Additional change:
- Add capability to have type reference that is not resolved (for the multiple action case), with the assumption that the definition will be somewhere.  
- During generation, it will error out by default if there are unresolved type reference, but will ignore if { strict: false} is passed in to the generation function.
- …
> Switch inline switcher and multiple action schema to use dynamic action schema creation API

- ts/packages/actionSchema/src/creator.ts
- ts/packages/actionSchema/src/generator.ts
- ts/packages/actionSchema/src/index.ts
- ts/packages/actionSchema/src/parser.ts
- ts/packages/actionSchema/src/type.ts
- ts/packages/agents/player/src/trackFilter.ts
- ts/packages/cli/src/commands/schema.ts
- ts/packages/dispatcher/src/agent/inlineAgentHandlers.ts
- ts/packages/dispatcher/src/handlers/common/appAgentManager.ts
- ts/packages/dispatcher/src/translation/actionSchema.ts
- ts/packages/dispatcher/src/translation/actionSchemaJsonTranslator.ts
- ts/packages/dispatcher/src/translation/actionTemplate.ts
- ts/packages/dispatcher/src/translation/agentTranslators.ts
- ts/packages/dispatcher/src/translation/unknownSwitcher.ts
Use dynamically composed action schema in the main code path, instead of generating the composed schema text and parse.
- Add capability to maintain order for composed schema.
- Separate out the order information from the schema, so that we can remap the order for the composite.
- Detect duplicate type and duplicate action names.
> Composed Action Schema

- ts/examples/spelunker/package.json
- ts/examples/spelunker/src/chunkyIndex.ts
- ts/examples/spelunker/src/makeQuerySchema.ts
- ts/examples/spelunker/src/pythonImporter.ts
- ts/examples/spelunker/src/queryInterface.ts
Redesigned how we provide context to the LLM: use PromptSection[] instead of one big string, and reduce amount of data sent.
Conversation context is modeled by sending the 5 most recent user queries and answers (without extra fluff) as "user" and "assistant" prompt sections.
Also rewrote wordWrap without copilot's or ChatGPT's misguided "help".
There's also a check for missing chunks (i.e., chunks mentioned in an index but not found in the chunks folder -- this can happen if a purge operation was interrupted). I now count until I have 20 *existing* chunks rather than 20 unverified chunk IDs.
Also reorder purge so that situation shoudn't happen anymore.
Various logging tweaks.
> [spelunker] Prompt engineering and limited conversation history

- ts/packages/actionSchema/src/validate.ts
- ts/packages/agents/markdown/src/agent/markdownActionHandler.ts
- ts/packages/dispatcher/src/handlers/common/appAgentManager.ts
- ts/packages/dispatcher/src/utils/exceptions.ts
Agent implementation might not always throw `Error` as exception.  Make sure we convert wherever they throw during initialization.
Ensure markdown agent initialization rejects the promise with an error on timeout.
Also on action validation, allow "translatorName" that is not part of the schema.
> Ensure error object on initialization

- ts/packages/agents/player/src/client.ts
- ts/packages/agents/player/src/userData.ts
- ts/packages/dispatcher/src/agent/agentProcess.ts
- ts/packages/dispatcher/src/dispatcher/dispatcher.ts
- ts/packages/dispatcher/src/handlers/common/appAgentManager.ts
- ts/packages/dispatcher/src/handlers/common/commandHandlerContext.ts
- ts/packages/dispatcher/src/handlers/requestCommandHandler.ts
- ts/packages/dispatcher/src/translation/actionSchemaFileCache.ts
- ts/packages/dispatcher/test/basic.spec.ts
- Need to handle if there isn't existing cache file to add to when writing to cache.
- Fix second round trip for parsed schema, where we need to write it out before resolve reference.
- Disable action semantic map if there is no embedding model keys.
Also:
- Add basic startup and shutdown dispatcher test, (with no keys).
> Action schema parse cache fixes

- ts/packages/dispatcher/src/handlers/common/commandHandlerContext.ts
- ts/packages/dispatcher/src/handlers/common/interactiveIO.ts
- ts/packages/shell/src/main/index.ts
Ensure orderly shutdown. Also move the session save inside the close instead of using the unsupported API that exposed CommandHandlerContext.
> Shell close dispatcher on exit

- ts/packages/agents/calendar/src/calendarActionHandler.ts
- ts/packages/agents/test/src/handler.ts
- ts/packages/dispatcher/src/command/command.ts
- ts/packages/dispatcher/src/handlers/common/commandHandlerContext.ts
- ts/packages/dispatcher/src/handlers/configCommandHandlers.ts
- ts/packages/dispatcher/src/session/session.ts
- ts/packages/dispatcher/test/basic.spec.ts
Add command to set a different agent to totally to take over natural language request, bypassing dispatcher.
The agent implements `request` command handler at the top level with a single `implicitQuotes` parameter.
User can use the command `@config request <appAgentName>` to switch to direct natural language request to that agent.
Also, add output validation for dispatcher tests.
> Alternate natural language request handler

- ts/packages/aiclient/src/restClient.ts
- ts/packages/cli/src/commands/schema.ts
- ts/packages/dispatcher/src/context/commandHandlerContext.ts
- ts/packages/dispatcher/src/context/dispatcher/dispatcherAgent.ts
- ts/packages/dispatcher/src/context/dispatcher/handlers/requestCommandHandler.ts
- ts/packages/dispatcher/src/context/dispatcher/schema/clarifyActionSchema.ts
- ts/packages/dispatcher/src/context/session.ts
- ts/packages/dispatcher/src/context/system/handlers/configCommandHandlers.ts
- ts/packages/dispatcher/src/translation/actionSchemaJsonTranslator.ts
- ts/packages/dispatcher/src/translation/agentTranslators.ts
- ts/packages/dispatcher/src/utils/test/testData.ts
- `@config translation switch embedding [on|off]` to toggle the initial schema pick using embedding
- `@config translation switch fix <agentName>` command to turn off switching and set the schema to use.
- Fix the problem of missing injected schema (including `unknown`) when inline switcher is off, 
- Split the clarify schema into 3 to better drive change of thought for each case for the clarification question. This also help make sure it doesn't overly generalized and generate clarification when it should just go to `unknown` action.
- Add additional message to the unknown action to indicate if the likely action for the request (using embedding) is not active, or if the switching of action is completely off.
- Improve fetch error by pulling out the inner exception's message (e.g. …
> Switch to turn off initial schema pick using embedding.

- ts/packages/cache/src/cache/cache.ts
- ts/packages/cache/src/cache/explainWorkQueue.ts
- ts/packages/cache/src/explanation/explainer.ts
- ts/packages/cache/src/index.ts
- ts/packages/cache/src/utils/print.ts
- ts/packages/cli/src/commands/interactive.ts
- ts/packages/cli/src/commands/run/explain.ts
- ts/packages/dispatcher/src/command/command.ts
- ts/packages/dispatcher/src/context/appAgentManager.ts
- ts/packages/dispatcher/src/context/dispatcher/handlers/explainCommandHandler.ts
- ts/packages/dispatcher/src/context/system/handlers/displayCommandHandler.ts
- ts/packages/dispatcher/src/helpers/console.ts
- ts/packages/dispatcher/src/internal.ts
- Stop exposing internal `CommandHandlerContext` APIs. 
- Switch to use `createDispatcher` and use the `@dispatcher explain` command
- Move some of the additional functionality from the CLI to the command handler.
- Fix consoleIO input hanging the CLI in `run explain`
> `cli run explain` use `createDispatcher` API

- ts/packages/dispatcher/src/command/command.ts
Don't rollback if there is no app agent name parsed.
> Fix completion rollback

- ts/packages/commonUtils/src/jsonTranslator.ts
This pull request includes a small but important correction to a typo in the `createJsonTranslatorWithValidator` function within the `jsonTranslator.ts` file. The typo fix improves the clarity of the message provided to the LLM.
Typo correction:
* [`ts/packages/commonUtils/src/jsonTranslator.ts`](diffhunk://#diff-bb6ecd66e24575fbb78e5f5d6474b8feff1845f9e15c2fb23450fb3fb5fe7f29L339-R339): Corrected the word "previoiusly" to "previously" in the user request translation message.
> Fix typo in translator request prompt

- ts/examples/viewList/src/route/route.ts
- ts/packages/agentSdk/README.md
- ts/packages/agentSdk/src/agentInterface.ts
- ts/packages/agents/desktop/src/actionHandler.ts
- ts/packages/agents/desktop/src/connector.ts
- ts/packages/agents/player/src/agent/playerCommands.ts
- ts/packages/agents/player/src/agent/playerHandlers.ts
- ts/packages/agents/player/src/client.ts
- ts/packages/agents/player/src/userData.ts
- ts/packages/cacheExplorer/src/route/route.ts
- ts/packages/cli/src/commands/run/explain.ts
- ts/packages/cli/src/commands/run/request.ts
- ts/packages/cli/src/commands/run/translate.ts
- ts/packages/dispatcher/src/agentProvider/process/agentProcess.ts
- ts/packages/dispatcher/src/agentProvider/process/agentProcessShim.ts
- ts/packages/dispatcher/src/agentProvider/process/agentProcessTypes.ts
- ts/packages/dispatcher/src/context/commandHandlerContext.ts
- ts/packages/dispatcher/src/context/session.ts
- ts/packages/dispatcher/src/context/system/handlers/constructionCommandHandlers.ts
- ts/packages/dispatcher/src/context/system/handlers/sessionCommandHandlers.ts
- ts/packages/dispatcher/src/execute/actionHandlers.ts
- ts/packages/dispatcher/src/explorer.ts
- ts/packages/dispatcher/src/utils/defaultAppProviders.ts
- ts/packages/dispatcher/src/utils/userData.ts
- ts/packages/knowledgeVisualizer/src/route/visualizationNotifier.ts
Enable e2e tests to create dispatcher without any persistence to avoid conflicting lock.
> Enable dispatcher to be created without any persistence

- ts/packages/agentSdk/src/agentInterface.ts
- ts/packages/agents/oracle/src/oracleManifest.json
- ts/packages/dispatcher/src/context/appAgentManager.ts
- ts/packages/dispatcher/src/translation/agentTranslators.ts
Oracle is in conflict with the chat agent.   Disable the schema by default.
Also rename the setting to `schemaDefaultEnabled` to align terminology
> Disable oracle schema by default

- .github/workflows/build-ts.yml
- ts/packages/dispatcher/src/command/commandHelp.ts
- ts/packages/dispatcher/src/context/dispatcher/dispatcherAgent.ts
- ts/packages/dispatcher/src/context/system/action/configActionHandler.ts
- ts/packages/dispatcher/src/context/system/action/historyActionHandler.ts
- ts/packages/dispatcher/src/context/system/action/notificationActionHandler.ts
- ts/packages/dispatcher/src/context/system/schema/configActionSchema.ts
- ts/packages/dispatcher/src/context/system/schema/historyActionSchema.ts
- ts/packages/dispatcher/src/context/system/schema/notificationActionSchema.ts
- ts/packages/dispatcher/src/context/system/systemAgent.ts
- fixed some @ command actions
- added some more @ command actions
- help command now outputs things as a table
> Tightened up help output & added action commands for some system commands

- ts/packages/dispatcher/src/context/session.ts
The `Session` constructor expects the full path to the sessions dir. `newSessionDir` was only returning the session name, causing an error when trying to create the session file. This fix corrects the issue by returning the full session directory from `newSessionDir`
> Correct session directory

- ts/examples/spelunker/design.md
- ts/examples/spelunker/src/chunkyIndex.ts
- ts/examples/spelunker/src/fileDocSchema.ts
- ts/examples/spelunker/src/fileDocumenter.ts
- ts/examples/spelunker/src/makeQuerySchema.ts
- ts/examples/spelunker/src/pythonImporter.ts
- ts/examples/spelunker/src/queryInterface.ts
* Use larger chatModel for queryMaker; it definitely works better
* Fix subtle bug in purging (too many distinct types resolve to 'string', so the type checker didn't catch this!)
* Root out the last mentions of topics and goals
* Make it easier to change index names; (topics, goals) -> (tags, synonyms).
* Tweak presentation of TF*IDF (no change in the formula)
* Add description of hit and chunk scoring to design.md
* Hoist TF calculation out of inner loop
> [spelunker]: Misc changes from holiday season

- ts/packages/agents/browser/src/agent/instacart/actionHandler.mts
- ts/packages/agents/browser/src/agent/instacart/schema/pageComponents.mts
- ts/packages/agents/browser/src/extension/contentScript.ts
- ts/packages/agents/browser/src/extension/loadingDetector.ts
- ts/packages/agents/browser/src/extension/serviceWorker.ts
- use a mutation observer to check for page elements that are placeholders (e.g. elements with the aria-busy="true" acccessibility attribute).
- use an intersection observer to ensure we only consider placeholder elements that are visible in the viewport. Many websites would have placeholders for product lists or search results until the user scrolls the page section into view.
> Account for incrementally loading pages that have placeholders

- ts/packages/agents/chat/src/chatResponseActionSchema.ts
- ts/packages/dispatcher/src/context/chatHistoryPrompt.ts
Adjust the comment for `chat.generateResponse` to make the scenario that explain common phrase the user type more stable.
Add prompt instruction to avoid clarifying unresolve resolution if there is a possible match (which also currently stop it from activate if there are multiple ambiguity. Will continue to rebalance over time). 
> Prompt rebalancing

- ts/packages/agentRpc/src/client.ts
- ts/packages/agentRpc/src/rpc.ts
- ts/packages/agents/browser/package.json
- ts/packages/agents/browser/src/agent/webTypeAgent.mts
- ts/packages/dispatcher/src/context/appAgentManager.ts
- ts/packages/dispatcher/src/translation/actionSchemaSemanticMap.ts
- ts/pnpm-lock.yaml
Make sure all the state that got modified are cleaned up, including the channel we created.
Make sure the browser agent process doesn't crash when an unexpected disconnect web agent message comes in.
> Clean up all the states when adding dynamic agent failed

- ts/packages/agents/calendar/src/calendarActionsSchema.ts
- ts/packages/dispatcher/src/context/dispatcher/handlers/requestCommandHandler.ts
- ts/packages/dispatcher/src/translation/actionSchemaJsonTranslator.ts
- ts/packages/dispatcher/src/translation/actionSchemaSemanticMap.ts
Fix the scenario: 
- `add the ingredients for chess pie to my grocery list`
- `don't need the sugar`  
Couple of issues:
1. When picking the initial schema group to use, both request's embedding matches the calendar actions because the calendar schema description with the embedding is included in the embedding, and the action itself doesn't have description.  That diluted the focus and let it match much different range of requests.
2. Even if the initial pick is wrong, the actual translation prompt ends up choosing the "removeEvent" action, instead of switching to calendar.   The issue here is that when we pare down the schema to only the top 5 likely actions, it loses the context that these are calendar actions.
The changes are:
1. Remove descriptions from the action embedding. (Fixes 1 …
> Improve embedding heuristics and pared downed prompt context

- ts/packages/actionSchema/src/parser.ts
- ts/packages/actionSchema/test/parse.spec.ts
- ts/packages/agents/test/src/handler.ts
- ts/packages/agents/test/src/manifest.json
- ts/packages/agents/test/src/schema.ts
- ts/packages/dispatcher/src/translation/actionSchemaFileCache.ts
We already have strict checks on cached schemas.  Turns it on when we first parse as well to have consistent behavior between parsing and loading from cache.
Improve error message for entry comment error.
Added test for some of the error conditions.
> Turn on strict checks when parsing action schema

- ts/packages/agentRpc/src/client.ts
- ts/packages/dispatcher/src/context/dispatcher/handlers/requestCommandHandler.ts
- ts/packages/dispatcher/src/context/dispatcher/schema/clarifyActionSchema.ts
- ts/packages/dispatcher/src/context/dispatcher/schema/dispatcherActionSchema.ts
- ts/packages/dispatcher/src/context/session.ts
- ts/packages/dispatcher/src/context/system/handlers/traceCommandHandler.ts
- ts/packages/dispatcher/src/translation/actionSchemaJsonTranslator.ts
- ts/packages/dispatcher/src/translation/agentTranslators.ts
- Disable partial schema group optimization by default.
- Add `Partial` to the type name when we do translation with partial schema group.  
- Make sure we retry the full current schema for subactions in multiple action if needed.
- Rename `changeAssistantAction` to `additionalActionLookup` to be more direct with what it does.
- Make sure clarify flow doesn't try to clarify unknown actions.
- trace command will automatically set `maxStringLength`, `depth` and `maxArrayLength` to `null` to show everything.
> Disable partial schema group optimization by default.

- ts/packages/dispatcher/src/context/interactiveIO.ts
- ts/packages/dispatcher/src/execute/actionHandlers.ts
- ts/packages/dispatcher/src/helpers/console.ts
- ts/packages/dispatcher/src/rpc/clientIOClient.ts
- ts/packages/dispatcher/src/rpc/clientIOServer.ts
- ts/packages/dispatcher/src/rpc/clientIOTypes.ts
- ts/packages/shell/src/renderer/assets/styles.less
- ts/packages/shell/src/renderer/src/chatView.ts
- ts/packages/shell/src/renderer/src/main.ts
- ts/packages/shell/src/renderer/src/messageContainer.ts
- ts/packages/shell/src/renderer/src/messageGroup.ts
Instead of adding the action name to every message.
Now, the whole action object is provided, so the shell can display it when hovering the source.
> Add clientIO to set the source and action for a message container.

- ts/examples/spelunker/src/pythonChunker.ts
- ts/packages/agents/spelunker/src/pythonChunker.ts
(Note: there are two copies of the files related to python chunking. TODO: Refactor to share the code.)
> Spelunker: Pass '-X utf8' to python3 to avoid coding errors on Windows

- ts/examples/memoryProviders/test/tsconfig.json
- ts/packages/knowledgeProcessor/test/tsconfig.json
testData.ts don't need to be rebuild in the test directory in memory provider and knowledge processor.
It interferes with incremental building.
> Remove tsc compiler reference same source twice

- ts/packages/coda/package.json
esbuild should only output when there is warning.
> Reduce build message

- ts/packages/agents/player/src/agent/playerHandlers.ts
- ts/packages/agents/player/src/agent/playerSchema.ts
- ts/packages/agents/player/src/client.ts
- ts/packages/agents/player/src/endpoints.ts
- ts/packages/agents/player/src/search.ts
- ts/packages/dispatcher/test/data/calendar/v5/complex.json
- ts/packages/dispatcher/test/data/calendar/v5/simple.json
- ts/packages/dispatcher/test/data/player/v5/changeVolume.json
- ts/packages/dispatcher/test/data/player/v5/full.json
- ts/packages/dispatcher/test/data/player/v5/nextAction.json
- ts/packages/dispatcher/test/data/player/v5/param.json
- ts/packages/dispatcher/test/data/player/v5/pauseAction.json
- ts/packages/dispatcher/test/data/player/v5/previousAction.json
- ts/packages/dispatcher/test/data/player/v5/resumeAction.json
- ts/packages/dispatcher/test/data/player/v5/searchTracks.json
- ts/packages/dispatcher/test/data/player/v5/simple.json
Allow genre to be specified with playArtist action.
Merge `playAlbumTrack` action with `playTrack` action to avoid confusion.
Also spotify deprecated genre APIs.  Turn genre specification to just a query for now.
> Improve player schema stability by almost 2%

- ts/packages/agents/code/src/codeActionHandler.ts
Fix regression from #583 
The `data.id` is actually a number in this case (which is just round trip from the agent), and a plain "truthy" check would reject call id of 0, causing the remote call to not be resolved.
Do an explicit `undefined` check instead.
> Fix vscode agent hang

- ts/packages/agents/agentUtils/graphUtils/package.json
- ts/packages/aiclient/package.json
- ts/packages/api/package.json
- ts/pnpm-lock.yaml
- ts/tools/package.json
- Change version of `@azure/identity` to version 4.2.1 instead of 4.5.0.
- The issue with version 4.5.0 is documented in AzureAD [issues](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/7303)
- Without this fix the token is not being read from the cache and we need to login every single time event. (Even when the token is valid and does not need to be refreshed.)
> Fix graph client login regression

- ts/.vscode/launch.json
- ts/packages/agents/spelunker/TODO.md
- ts/packages/agents/spelunker/src/chunker.py
- ts/packages/agents/spelunker/src/pythonChunker.ts
- ts/packages/agents/spelunker/src/searchCode.ts
- ts/packages/agents/spelunker/src/spelunkerActionHandler.ts
- ts/packages/agents/spelunker/src/spelunkerSchema.ts
Includes an update to the chunker to return the function/class/module name as a new field (codeName).
The entity work is incomplete, I produce entities, and they end up in the session history, but I am having a hard time having them passed back into spelunker. At least they can be used by the translator sometimes.
Example of what works:
- "spelunker describe tracing in more detail": produces a long bullet list, and some entities
- "spelunker describe the first two bullets in more detail" : makes two separate calls to Spelunker:
- "Describe the initialization and loading in the ConfigurationReader class in more detail."
- "Describe the flattening and merging in the ConfigurationReader class in more detail."
It is passing stuff to each of the last two spelunker calls, but it uses the …
> [Spelunker] Try to work with entities

- ts/packages/coda/src/handleCodeEditorActions.ts
- ts/packages/coda/src/wsConnect.ts
- Was using Promise.race which causes non-deterministic behavior. The code path uses separate async function to handle actions, updated to Promise.all.
- Fixed code handle actions objects where parameter property is undefined.
> Bug fix when handling promises.

- ts/packages/defaultAgentProvider/test/data/translate-e2e.json
- ts/packages/dispatcher/src/context/commandHandlerContext.ts
- ts/packages/dispatcher/src/context/dispatcher/handlers/requestCommandHandler.ts
- ts/packages/dispatcher/src/context/dispatcher/handlers/translateCommandHandler.ts
- ts/packages/dispatcher/src/context/session.ts
- ts/packages/dispatcher/src/context/system/handlers/configCommandHandlers.ts
- ts/packages/dispatcher/src/execute/actionHandlers.ts
- ts/packages/dispatcher/src/translation/actionSchemaJsonTranslator.ts
- ts/packages/dispatcher/src/translation/agentTranslators.ts
- ts/packages/dispatcher/src/translation/confirmTranslation.ts
- ts/packages/dispatcher/src/translation/matchRequest.ts
- ts/packages/dispatcher/src/translation/multipleActionSchema.ts
- ts/packages/dispatcher/src/translation/pendingRequest.ts
- ts/packages/dispatcher/src/translation/translateRequest.ts
- ts/packages/dispatcher/src/utils/test/testData.ts
If an action requires the content of the result from previous action, multiple action will generate a pending request entry.
The pending request entry is converted into a "PendingRequestAction", and during execute, the request will be translated again with the current history context.
- A lot of the diff is from breaking apart the file `requestCommandHandler.ts`
- `executeActions` is not a queue to allow pending request action to be expanded to more actions.
- streaming now allow different `actionIndex` as the streaming target so that translation for pending request can be streamed too, but if the translation is not a multiple action.
- Add toggles for result id and pending for multiple actions.
> Pending action support in multiple actions

- .github/workflows/shell-tests.yml
- .github/workflows/smoke-tests.yml
- ts/packages/shell/src/main/index.ts
- ts/packages/shell/test/simple.spec.ts
- ts/packages/shell/test/testHelper.ts
Fixes `pnpm run start` for Linux/WSL2 for shell.  Should fix the playwright shell test as well.
- Need to use `WebContent.loadFile` instead of `WebContent.loadUrl` API.
- Ubuntu 24.04 needs `--no-sandbox`
- Make sure we catch any error from loading those files instead of just hanging.
- Fix the smoke test pipeline to clean up the .env file after everything is done (instead of right after the shell test)
> Fix electron preview in linux/wsl2

- ts/packages/shell/test/simple.spec.ts
- ts/packages/shell/test/testHelper.ts
- It doesn't like the trailing path separator.
- Add check in simple smoke test to make sure we catch the load error in the future by checking the URL that is loaded.
- Add smoke test to exercise `startShell` which the nightly shell test depends on.
> Fix electron app path

- ts/examples/chat/src/memory/knowproMemory.ts
- ts/packages/knowPro/src/accumulators.ts
- ts/packages/knowPro/src/conversationIndex.ts
- ts/packages/knowPro/src/dataFormat.ts
- ts/packages/knowPro/src/query.ts
- ts/packages/knowPro/src/search.ts
Ongoing experimentation:
* Flexible property matching for query trees...
* Simplified property predicates
* Filter by arbitrary properties; auto-lower property terms
* Simple query builder
* Bug fixes
> knowpro: structured querying

- ts/packages/agents/spelunker/src/typescriptChunker.ts
- ts/packages/codeProcessor/src/tsCode.ts
Still to do: subtract blobs of child chunks from parent chunk. That will happen next.
> [Spelunker] Add interface/type declarations, and nesting

- ts/packages/cli/src/commands/test/translate.ts
- Add `-i` flags to use previous result file as input.
- Change --rerun to --failed with combination of `-i` to indicate only running failed tests.
- Add `--sample [n]` to run a random sample of the input.
> Translate test command improvements

- ts/packages/actionSchema/src/generator.ts
- ts/packages/actionSchema/src/index.ts
- ts/packages/actionSchema/src/jsonSchemaGenerator.ts
- ts/packages/aiclient/src/models.ts
- ts/packages/aiclient/src/openai.ts
- ts/packages/aiclient/src/restClient.ts
- ts/packages/cli/src/commands/run/translate.ts
- ts/packages/commonUtils/src/indexNode.ts
- ts/packages/commonUtils/src/jsonTranslator.ts
- ts/packages/dispatcher/src/context/commandHandlerContext.ts
- ts/packages/dispatcher/src/context/session.ts
- ts/packages/dispatcher/src/context/system/handlers/configCommandHandlers.ts
- ts/packages/dispatcher/src/translation/actionSchemaJsonTranslator.ts
- ts/packages/dispatcher/src/translation/agentTranslators.ts
Initial support to generate JSON schema for OAI's structure output. Off by default since the performance hit isn't great, and TS schema in the prompt with json mode already have high accuracy rate. (40s+ with cache miss, 1-2s with cache hit, and cache miss vs cache hit rate is about 50%).
> Add JSON Schema support as an options.

- ts/packages/agents/spelunker/src/searchCode.ts
The endpoint name for the mini model was misspelled, so we quietly got the default model (gpt-4-o-2).
After fixing it, I noticed that the summarizing and selecting phases (which use the mini model) became significantly *slower*. (There's a lot of variability in the measurements but the difference was pretty consistent).
So now the fix is to set the mini model endpoint name to `undefined`, which means it's the same old default model, but there's no misleading misspelled endpoint name, and a comment explaining the reason.
> [Spelunker] Fix mini model endpoint

- ts/packages/agents/spelunker/src/searchCode.ts
- ts/packages/agents/spelunker/src/summarizerSchema.ts
This requires adding a "language" field to the Summaries interface/table (filled in by the AI during summary creation).
Also tweak the translation of the single text string in the Blob table back into a list of lines, all ending in a newline.
> [Spelunker] Improve formatting ("preparation") of summaries sent to oracle

- ts/packages/agents/spelunker/src/searchCode.ts
- ts/packages/agents/spelunker/src/spelunkerActionHandler.ts
In a Spelunker session (after `@config request spelunker`) you can now ask to see the focus by typing `.focus` or change the focus using `focus <folder>`. Folders can start with `~` indicating `$HOME`, or be absolute paths or relative paths (relative to whatever the CLI or Shell uses as its current directory).
> [Spelunker] Add .focus command to set focus directory

- ts/packages/agents/spelunker/src/typescriptChunker.ts
We were failing an assertion when splicing child nodes out of parent nodes in the following case:
```ts
type Foo = ...; // comment
function bar() { 
...
}
```
The TSC `node.getFullStart() ` API would return the location of Foo's comment, and our strategy for moving to the next line didn't work. (This makes `getFullStart()` pretty stupid IMO, but we can't change that.)
This PR is a quick hack to fix this by always moving to the start of the next line if the start position points in the middle of a line (i.e., `character` is > 0).
> [Spelunker] Be less eager to get comments before a declaration

- ts/packages/actionSchema/src/parser.ts
- ts/packages/dispatcher/src/command/completion.ts
- ts/packages/dispatcher/src/translation/actionSchemaFileCache.ts
- ts/packages/shell/src/renderer/src/messageContainer.ts
- Json parameters should do completion of the full "parameter name" instead of the prefix.
- Optimize type-unions that are only string literals into string-unions when parsing (also bump the cache version to invalidate)
- Shell output message container is hidden when first created.
> Improve IntelliSense with json parameters

- ts/packages/agents/player/src/agent/playerHandlers.ts
- ts/packages/agents/player/src/client.ts
- ts/packages/agents/player/src/endpoints.ts
- ts/packages/agents/player/src/playback.ts
- ts/packages/agents/player/src/search.ts
- ts/packages/cache/src/explanation/requestAction.ts
- ts/packages/cache/src/index.ts
- ts/packages/cli/src/commands/data/regenerate.ts
- ts/packages/dispatcher/src/context/chatHistory.ts
- ts/packages/dispatcher/src/context/chatHistoryPrompt.ts
- ts/packages/dispatcher/src/context/dispatcher/handlers/requestCommandHandler.ts
- ts/packages/dispatcher/src/execute/actionHandlers.ts
- ts/packages/dispatcher/src/internal.ts
- If the agent returns entities with uniqueId, and the same "name" is used in the following action, we will put the entity in the EntityMap.   Only entity with uniqueId from the same agent will be populated.
- For the result id reference, change the entity map to include only result that are from the same agent and referenced in the action.
- Change how we determine uniqueness of entities based on name and type only.  Attach a `v<num>` suffix to entities that have same name and type to distinguish each other.  Therefore, entity with the same name and type but different uniqueId will have different suffix.  
-  LLM may change lower/upper case or add/remove diacritical.  When lookup the action result with the entity, use a normalized form that remove those difference for look up.
-  Future …
> Entity with uniqueId roundtrip

- ts/packages/agentRpc/src/client.ts
- ts/packages/agentRpc/src/server.ts
- ts/packages/agentRpc/src/types.ts
- ts/packages/cache/src/cache/cache.ts
- ts/packages/cache/src/cache/explainWorkQueue.ts
- ts/packages/cache/src/constructions/constructions.ts
- ts/packages/cache/src/constructions/importConstructions.ts
- ts/packages/cache/src/explanation/explainer.ts
- ts/packages/cache/src/explanation/requestAction.ts
- ts/packages/cache/src/explanation/schemaInfoProvider.ts
- ts/packages/cache/src/explanation/v5/alternativesExplanationV5.ts
- ts/packages/cache/src/explanation/v5/explanationV5.ts
- ts/packages/cache/src/explanation/v5/propertyExplainationV5.ts
- ts/packages/cache/src/explanation/v5/subPhraseExplanationV5.ts
- ts/packages/cache/src/index.ts
- ts/packages/cli/src/commands/data/regenerate.ts
- ts/packages/cli/src/commands/run/explain.ts
- ts/packages/cli/src/commands/test/translate.ts
- ts/packages/defaultAgentProvider/test/construction.spec.ts
- ts/packages/defaultAgentProvider/test/constructionCacheTestCommon.ts
- ts/packages/defaultAgentProvider/test/requestAction.spec.ts
- ts/packages/defaultAgentProvider/test/validateExplanationTestData.spec.ts
- ts/packages/dispatcher/src/context/dispatcher/handlers/requestCommandHandler.ts
- ts/packages/dispatcher/src/context/system/systemAgent.ts
- ts/packages/dispatcher/src/execute/actionHandlers.ts
- ts/packages/dispatcher/src/translation/actionTemplate.ts
- ts/packages/dispatcher/src/translation/confirmTranslation.ts
- ts/packages/dispatcher/src/translation/pendingRequest.ts
- ts/packages/dispatcher/src/translation/translateRequest.ts
- ts/packages/dispatcher/src/utils/test/testData.ts
- Reduce the number of types we need to deal with related to actions.
- Remove the use of implicit toJson() and toString() from the Action and Actions class.
- Remove hack in RPC to naturally marshal the actions as `FullAction` instead of `JSONAction`
- `JSONAction` preserve `resultEntityId` as well
> Remove Action and Actions class and use FullAction and the new ExecutableActions.

- ts/packages/actionSchema/src/index.ts
- ts/packages/actionSchema/src/toString.ts
- ts/packages/actionSchema/src/validate.ts
- ts/packages/defaultAgentProvider/test/data/translate-history-e2e.json
- ts/packages/defaultAgentProvider/test/translateTestCommon.ts
- ts/packages/defaultAgentProvider/test/translate_history.test.ts
- ts/packages/dispatcher/src/context/chatHistory.ts
- ts/packages/dispatcher/src/context/commandHandlerContext.ts
- ts/packages/dispatcher/src/context/system/handlers/historyCommandHandler.ts
- ts/packages/dispatcher/src/context/system/systemAgent.ts
- ts/packages/dispatcher/src/dispatcher.ts
- ts/packages/dispatcher/src/index.ts
- ts/packages/dispatcher/src/internal.ts
- ts/packages/dispatcher/src/utils/userData.ts
- Add `@history insert` command to insert chat history entries.
- Add the first translation with history test
- Type validation: Improve error message with union type mismatch
> Initialize translate with history tests

- ts/packages/agents/spelunker/src/searchCode.ts
We now create batches dynamically instead of using a fixed number of chunks per batch. Based on an approximate (hopefully slightly over-) estimate of chunk sizes, create batches that are up to 250k characters. Similarly, keep 250k characters worth of chunks to send to the oracle.
We also report the actual token usage for each call.
I am trying to satisfy two constraints:
1. There's a limit of 256k characters somewhere (above that you get nasty warnings)
2. I'm not sure what the input buffer token limit is, but it seems 50-55k tokens is acceptable.
Some example output:
```
0.000 [searchCode question='compare chunker.py and typechatChunker.ts']
0.000 [Step 1: Load database]
0.000   [Using database at /home/gvanrossum/.typeagent/agents/spelunker/codeSearchDatabase.db]
0.000 [Step 1a: Find …
```
> [Spelunker] Better batch creation (dynamic size, allows getting closer to actual limits without worries)

- ts/packages/agents/spelunker/src/searchCode.ts
Experimentally, 40 chunks per batch appears to work.
> Restore summaries. Output limit 4096 so limit the number of chunks.

- ts/packages/agents/spelunker/src/oracleSchema.ts
- ts/packages/agents/spelunker/src/searchCode.ts
The intention is to make breadcrumbs embedded in a class, module or outer function more informative even when the chunk which it represents is not included in the context.
This applies to chunk selection and oracle requests; not to summarize requests (or we'd have a chicken/egg problem).
For example, a breadcrumb of the form
```ts
function beginRefresh ...
```
is replaced with
```ts
// Prevents multiple calls to refresh while one is pending.
function beginRefresh(): Promise<Result<string>> ...
```
Note how the indentation is preserved.
Also made many logging tweaks and one small schema tweak.
> [Spelunker] Adjust breadcrumbs using summaries

- ts/packages/knowPro/src/collections.ts
- ts/packages/knowPro/src/dataFormat.ts
- ts/packages/knowPro/src/query.ts
- ts/packages/knowPro/src/relatedTermsIndex.ts
- ts/packages/knowPro/src/search.ts
- ts/packages/typeagent/src/vector/embeddings.ts
- ts/packages/typeagent/src/vector/vector.ts
- Sundry scoring improvements.
- Better handle _overlapping_ relative terms (which are fuzzily matched)
- Batched fuzzy relative matching
- Term weighting
- Code refactoring
> knowpro: relative term matching improvements

- ts/packages/cli/README.md
- ts/packages/cli/src/commands/data/add.ts
- ts/packages/cli/src/commands/data/stat.ts
- ts/packages/cli/src/commands/interactive.ts
- ts/packages/cli/src/commands/run/explain.ts
- ts/packages/cli/src/commands/run/request.ts
- ts/packages/cli/src/commands/run/translate.ts
- ts/packages/cli/src/commands/test/translate.ts
- ts/packages/dispatcher/src/context/system/systemAgent.ts
Mirror flags with `cli run translate`
- Add `--jsonSchema` to turn on JSON schema mode
- Add `--multiple` (and `--no-multiple`) to turn on/off multiple actions.
- Add `--model` to config the model to use.
Add other flags
- Add `--success` to rerun successful tests.
Add execution time to `cli run translate`
> Add flags to cli test translate

- ts/packages/actionSchema/src/generator.ts
- ts/packages/actionSchema/src/jsonSchemaGenerator.ts
- ts/packages/cli/src/commands/test/translate.ts
- ts/packages/dispatcher/src/context/chatHistoryPrompt.ts
- ts/packages/dispatcher/src/context/session.ts
- ts/packages/dispatcher/src/translation/actionSchemaJsonTranslator.ts
- ts/packages/dispatcher/src/translation/agentTranslators.ts
- ts/packages/dispatcher/src/translation/translateRequest.ts
- Skip including the typescript schema in the main prompt when JsonSchema is enabled.
- Add the schema comments as descriptions to Json schema.
- `cli test translate`, separate skipped requests in its only category that can be controlled using --skipped to regenerate.
- Fix `cli test translate` to count all failed case as processed.
> Skip the Typescript schema by default when JsonSchema is enabled.

- ts/packages/actionSchema/src/generator.ts
- ts/packages/actionSchema/src/index.ts
- ts/packages/actionSchema/src/jsonSchemaGenerator.ts
- ts/packages/aiclient/src/openai.ts
- ts/packages/cli/src/commands/run/translate.ts
- ts/packages/cli/src/commands/test/translate.ts
- ts/packages/dispatcher/src/context/chatHistoryPrompt.ts
- ts/packages/dispatcher/src/context/dispatcher/handlers/requestCommandHandler.ts
- ts/packages/dispatcher/src/context/session.ts
- ts/packages/dispatcher/src/context/system/handlers/configCommandHandlers.ts
- ts/packages/dispatcher/src/translation/actionSchemaJsonTranslator.ts
- ts/packages/dispatcher/src/translation/translateRequest.ts
- Add function calling support (in addition to structure output).  They are very similar except for a little bit different between the schemas, the REST call param and the output location (note that streaming is not implemented yet)
- Fix JSON schema with $ref subschema, where description is not supported (that means that we will miss comments for fields with a type reference).
- When Json schema (either structured output or function calling) is enabled, don't inject the typescript schema from the main prompt and also don't validate the output (assuming the service have validated them already since we have strict mode on).
- Also with `cli test translate` allow number of repeat to change if we process all the data from the `-i` input if specified.
- Fix the incorrect check if history is …
> Add function calling support

- ts/packages/actionSchema/src/index.ts
- ts/packages/actionSchema/src/jsonSchemaGenerator.ts
- ts/packages/aiclient/src/models.ts
- ts/packages/aiclient/src/openai.ts
- ts/packages/cli/src/commands/run/translate.ts
- ts/packages/cli/src/commands/test/translate.ts
- ts/packages/dispatcher/src/translation/actionSchemaJsonTranslator.ts
- Add `--jsonSchemaValidate` flags to validate the output from the LLM for `cli test translate` and `cli run translate`
- Move the conversion of the LLM output for function calling to the validator.
> Add json schema validate flag

- ts/examples/chat/src/memory/knowproMemory.ts
- ts/examples/chat/src/memory/knowproPrinter.ts
- ts/packages/knowPro/src/dataFormat.ts
- ts/packages/knowPro/src/import.ts
- ts/packages/knowPro/src/propertyIndex.ts
- ts/packages/knowPro/src/query.ts
- ts/packages/knowPro/src/search.ts
- ts/packages/knowPro/src/timestampIndex.ts
- Timestamp Scopes without secondary index (now optional)
- Command line improvements.
> knowpro: make secondary indexes optional

- ts/examples/chat/src/memory/knowproMemory.ts
- ts/packages/knowPro/src/dataFormat.ts
- ts/packages/knowPro/src/fuzzyIndex.ts
- ts/packages/knowPro/src/import.ts
- ts/packages/knowPro/src/propertyIndex.ts
- ts/packages/knowPro/src/query.ts
- ts/packages/knowPro/src/relatedTermsIndex.ts
- ts/packages/knowPro/src/search.ts
- ts/packages/knowPro/src/secondaryIndexes.ts
- ts/packages/knowPro/src/timestampIndex.ts
* All secondary index interfaces are optional. 
* Moved interfaces from dataFormat.ts to **secondaryIndex.ts**
* dataFormat.ts goes back to being minimal
* Related term secondary indexes also now fully optional (including embeddings).
* Query processor works when secondary indexes are not available
* Related term resolution skipped when not available.
> knowpro secondary indexes: refactoring etc. 

- ts/packages/agents/player/src/defaultTokenProvider.ts
- ts/packages/agents/player/src/tokenProvider.ts
- ts/packages/cli/src/commands/constructions.ts
- ts/packages/cli/src/commands/data/add.ts
- ts/packages/cli/src/commands/data/diff.ts
- ts/packages/cli/src/commands/data/list.ts
- ts/packages/cli/src/commands/data/regenerate.ts
- ts/packages/cli/src/commands/data/split.ts
- ts/packages/cli/src/commands/data/stat.ts
- ts/packages/cli/src/commands/test/translate.ts
- ts/packages/defaultAgentProvider/test/construction.spec.ts
- ts/packages/defaultAgentProvider/test/constructionCacheTestCommon.ts
- ts/packages/defaultAgentProvider/test/requestAction.spec.ts
- ts/packages/defaultAgentProvider/test/translateTestCommon.ts
- ts/packages/defaultAgentProvider/test/validateExplanationTestData.spec.ts
- ts/packages/dispatcher/src/context/system/handlers/constructionCommandHandlers.ts
- ts/packages/dispatcher/src/internal.ts
- ts/packages/dispatcher/src/utils/test/explanationTestData.ts
- Enable history in translation test, but clear them before each test.
- Rename `TestData` and associated functions/types to `ExplanationTestData`
> Enable history in translation test

- ts/packages/shell/electron.vite.preload-cjs.config.mts
- ts/packages/shell/package.json
- Provide a different root for cjs and esm so the temporary file doesn't overwrite each other.
> Provide a different root of electron-build

- ts/packages/agents/browser/src/extension/contentScript.ts
- ts/packages/agents/browser/src/extension/serviceWorker.ts
- ts/packages/agents/browser/src/extension/sidepanel.html
- ts/packages/agents/browser/src/extension/sidepanel.ts
- Ensure relevant HTML elements have IDs set before action recording starts
- Limit action recording to the top frame on a page. I'll need to generalize the solution to deal with multi-frame pages later.
> Capture screenshot and HTML for recorded actions

- ts/examples/chat/src/memory/knowproMemory.ts
- ts/examples/chat/src/memory/podcastMemory.ts
- ts/packages/knowPro/src/conversationIndex.ts
- ts/packages/knowPro/src/import.ts
- ts/packages/knowledgeProcessor/src/textChunker.ts
Ongoing experiments:
* Import multiple podcasts into single index
* Allow incremental add to conversation index using pre-extracted knowledge.
* Command to export podcast from v1 knowledge processor indexes into knowpro
* Sundry tidying
> knowpro: larger indexes

- ts/packages/cli/src/commands/interactive.ts
- ts/packages/cli/src/commands/run/explain.ts
- ts/packages/cli/src/commands/run/request.ts
- ts/packages/cli/src/commands/run/translate.ts
- ts/packages/cli/src/commands/test/translate.ts
- ts/packages/defaultAgentProvider/test/translateTestCommon.ts
- ts/packages/dispatcher/src/context/appAgentManager.ts
- ts/packages/dispatcher/src/context/commandHandlerContext.ts
- ts/packages/dispatcher/src/context/options.ts
- ts/packages/dispatcher/src/context/session.ts
- ts/packages/dispatcher/src/context/system/handlers/configCommandHandlers.ts
- ts/packages/dispatcher/src/context/system/handlers/sessionCommandHandlers.ts
- ts/packages/dispatcher/src/translation/actionTemplate.ts
- ts/packages/dispatcher/test/options.spec.ts
- ts/packages/dispatcher/test/provider.spec.ts
- Only serialize options that user explicit modified, allow the default to change from builds.
- Dispatcher initialization options are treated as change to the default, where persisted setting can override.
- Improve Dispatcher initialization options to enable/disable agents/schemas/actions/commands.
> Stop serializing all configs

- ts/examples/chat/src/memory/imageMemory.ts
- ts/examples/memoryProviders/src/elastic/simplifiedTextIndex.ts
- ts/examples/memoryProviders/test/sqlite.textTable.spec.ts
- ts/packages/agents/browser/src/extension/serviceWorker.ts
- ts/packages/agents/browser/src/extension/webTypeAgentMain.ts
- ts/packages/agents/greeting/src/greetingCommandHandler.ts
- ts/packages/knowPro/src/importImages.ts
- ts/packages/knowledgeProcessor/src/temporal.ts
There is still one import for `openAIApiSettingsFromEnv` in  `examples/memoryProviders/src/elastic/simplifiedTextIndex.ts` pending reworking the model creation API.
> Cleanup cross package relative path import

- ts/packages/cli/src/commands/run/translate.ts
- ts/packages/cli/src/commands/test/translate.ts
Add the following flags for `cli run translate` and `cli test translate`
- `--switchOptimization` - Enable schema optimization by only present partial schema group based on embedding.  (default: off)
- `--switchEmbedding` - Enable picking the first schema group to use for translation using embedding.   (default: on)
- `--switchInline` - Enable injection of the inline switcher for the translation to choose another schema group (default: on)
- `--switchSearch` - Enable second chance search for schema group if the first translation or inline switcher failed. (default: on)
> More switches for options to CLI translate commands

- ts/packages/commonUtils/src/jsonTranslator.ts
- ts/packages/dispatcher/src/agentProvider/agentProviderUtils.ts
- ts/packages/dispatcher/src/command/command.ts
- ts/packages/dispatcher/src/command/handlerUtils.ts
- ts/packages/dispatcher/src/context/appAgentManager.ts
- ts/packages/dispatcher/src/context/dispatcher/handlers/requestCommandHandler.ts
- ts/packages/dispatcher/src/context/system/action/historyActionHandler.ts
- ts/packages/dispatcher/src/context/system/action/notificationActionHandler.ts
- ts/packages/dispatcher/src/context/system/action/sessionActionHandler.ts
- ts/packages/dispatcher/src/context/system/handlers/configCommandHandlers.ts
- ts/packages/dispatcher/src/context/system/schema/historyActionSchema.ts
- ts/packages/dispatcher/src/context/system/schema/notificationActionSchema.ts
- ts/packages/dispatcher/src/context/system/schema/sessionActionSchema.ts
- ts/packages/dispatcher/src/internal.ts
- ts/packages/dispatcher/src/translation/actionConfigProvider.ts
- ts/packages/dispatcher/src/translation/actionSchemaJsonTranslator.ts
- ts/packages/dispatcher/src/translation/agentTranslators.ts
- ts/packages/dispatcher/src/translation/translateRequest.ts
- ts/packages/dispatcher/src/utils/test/explanationTestData.ts
- If embedding, inline and search switching are off, we will try to combine all the active schema into one single prompt.
- For now, we will error out if there are type name or action name that conflicts between the schemas.
- Require the translator keep track of the `actionName` -> `schemaName` mapping.  The steps to translate the request will keep track of the translator the action is from so that it can resolve the schema name after finalizing.  (This will allow us to do mix and match later).
Additionally:
- Refactor TypeAgentTranslator construction to be more flexible by passing in the inject/switch action config instead of the state to compute it internally.
- Skip the translation optimization of using embedding to choose a subset of action to prompt first when we retry the same …
> Combine all schema when all agent switching methods are off

- ts/packages/shell/src/renderer/assets/styles.less
Removed in #688, the style is needed to show the explanation message.
Change the original style a little bit to look more like a "tooltip"
> Add back explanation message accidentally removed

- ts/packages/defaultAgentProvider/test/data/translate-history-e2e.json
- ts/packages/defaultAgentProvider/test/translateTestCommon.ts
- ts/packages/dispatcher/src/context/appAgentManager.ts
- ts/packages/dispatcher/src/context/commandHandlerContext.ts
- ts/packages/dispatcher/src/context/session.ts
- ts/packages/dispatcher/src/context/system/handlers/sessionCommandHandlers.ts
- ts/packages/dispatcher/src/execute/actionHandlers.ts
- ts/packages/dispatcher/src/translation/actionSchemaSemanticMap.ts
- Use embedding caching to only generate embedding once (instead of 5 times per test file).
- Make sure all the promise is settled before moving on to the next test.
- Add additional history test.
> Translation test improvements

- ts/examples/chat/src/memory/knowproCommon.ts
- ts/examples/chat/src/memory/knowproMemory.ts
- ts/examples/chat/src/memory/knowproPrinter.ts
- ts/packages/knowPro/src/conversationIndex.ts
- ts/packages/knowPro/src/search.ts
Part 1:
- Start by using knowlege-processor to translate natural language queries into TermFilters
- Transforms term filters (terms, date ranges) into know-pro **searchConversation** call
- Execute query
Next check-in will also transform actions.
> knowpro: natural language querying (phase 1)

- ts/examples/chat/src/memory/knowproCommon.ts
- ts/examples/chat/src/memory/knowproMemory.ts
- ts/packages/knowPro/src/dateTimeSchema.ts
- ts/packages/knowPro/src/index.ts
- ts/packages/knowPro/src/search.ts
- ts/packages/knowPro/src/searchSchema.ts
- ts/packages/knowPro/src/searchTranslator.ts
First cut of natural language querying natively in knowpro:
* searchSchema.ts, searchTranslator.ts to translate natural language to query filter
* Compile/transform returned filter to knowpro terms and 'when/scope' filter (time ranges etc.)
* kpSearch command in test app
* Ongoing work, testing/refinement
Testing:
* Also implemented natural language search for knowpro using V1 translators and kpSearchV1 command
> knowpro: Natural Language querying

- ts/packages/agents/browser/src/agent/actionHandler.mts
- ts/packages/agents/browser/src/agent/browserConnector.mts
- ts/packages/agents/browser/src/agent/discovery/actionHandler.mts
- ts/packages/agents/browser/src/agent/discovery/schema/discoveryActions.mts
- ts/packages/agents/browser/src/extension/serviceWorker.ts
- ts/packages/agents/browser/src/extension/sidepanel.ts
- ts/packages/agents/browser/src/extension/storage.ts
- Enable saving type definitions in chrome local storage, per URL
- include use-authored actions in the registered dynamic agent schema
- simplify schema registration
> Sidepanel: persisting type definitions in local storage

- ts/packages/agents/browser/src/agent/browserConnector.mts
- ts/packages/agents/browser/src/agent/discovery/actionHandler.mts
- ts/packages/agents/browser/src/agent/discovery/schema/pageComponents.mts
- ts/packages/agents/browser/src/agent/discovery/schema/recordedActions.mts
- ts/packages/agents/browser/src/agent/discovery/tempAgentActionHandler.mts
- ts/packages/agents/browser/src/extension/contentScript.ts
- ts/packages/agents/browser/src/extension/serviceWorker.ts
- ts/packages/agents/browser/src/extension/sidepanel.ts
- ts/packages/agents/browser/src/extension/uiEventsDispatcher.ts
- the extension relied on `chrome.windows.getCurrent()` to get the current window in view. However, when the devTools view is undocked, it is treated as the active window. This leads to errors where the service worker tries to send events to the devtools view instead of the content window.
-  There was an error where some code paths tried to access chrome.storage apis in the content script, causing the script to crash.
> browser: fix inconsistent automation errors

- ts/packages/agents/browser/src/agent/discovery/actionHandler.mts
- ts/packages/agents/browser/src/agent/discovery/schema/recordedActions.mts
- ts/packages/agents/browser/src/agent/discovery/tempAgentActionHandler.mts
- ts/packages/agents/browser/src/extension/sidepanel.ts
- Fix typos
- Add support for recorded actions that need the exact text on element
> sidepanel: Add support for recorded actions that need the exact text on element

- python/kp/knowpro/convindex.py
- python/kp/knowpro/interfaces.py
- python/kp/memconv/import_podcasts.py
(This is only for the Python port.)
Change TMeta into a base class. We then get:
- IMessage has IKnowledgeSource as a base class, and no longer has a metadata field -- you just call message.get_knowledge().
- IConversation is generic in the message type (TMessage) and its messages field is a list of TMessage.
- add_metadata_to_index() is generic in the message type (I think there's a pattern here :-).
- PodcastMessageMeta becomes base class PodcastMessageBase (but it could easily be just blended into PodcastMessage).
- PodcastMessage derives both from PodcastMessageBase and IMessage.
- Podcast derives from IConversation[PodcastMessage] and its messages field is a list of PodcastMessage.
- assign_message() takes a sequence of PodcastMessage.
> [python/knowpro] Change class structure to suit Python's type system better

- ts/packages/cache/src/constructions/constructionCache.ts
- ts/packages/cache/src/constructions/constructionValue.ts
- ts/packages/cache/src/constructions/constructions.ts
- ts/packages/cache/src/explanation/requestAction.ts
- ts/packages/cache/src/explanation/v5/alternativesExplanationV5.ts
- ts/packages/cache/src/explanation/v5/explanationV5.ts
- ts/packages/cache/src/explanation/v5/politenessGeneralizationV5.ts
- ts/packages/cache/src/explanation/v5/propertyExplainationV5.ts
- ts/packages/cache/src/explanation/v5/subPhraseExplanationV5.ts
- ts/packages/cli/src/commands/data/regenerate.ts
- ts/packages/cli/src/commands/test/translate.ts
- ts/packages/defaultAgentProvider/test/constructionCacheTestCommon.ts
- ts/packages/defaultAgentProvider/test/data/explanations/calendar/v5/complex.json
- ts/packages/defaultAgentProvider/test/data/explanations/calendar/v5/simple.json
- ts/packages/defaultAgentProvider/test/data/explanations/player/v5/changeVolume.json
- ts/packages/defaultAgentProvider/test/data/explanations/player/v5/full.json
- ts/packages/defaultAgentProvider/test/data/explanations/player/v5/nextAction.json
- ts/packages/defaultAgentProvider/test/data/explanations/player/v5/param.json
- ts/packages/defaultAgentProvider/test/data/explanations/player/v5/pauseAction.json
- ts/packages/defaultAgentProvider/test/data/explanations/player/v5/previousAction.json
- ts/packages/defaultAgentProvider/test/data/explanations/player/v5/resumeAction.json
- ts/packages/defaultAgentProvider/test/data/explanations/player/v5/searchTracks.json
- ts/packages/defaultAgentProvider/test/data/explanations/player/v5/simple.json
- ts/packages/dispatcher/src/agentProvider/agentProviderUtils.ts
- ts/packages/dispatcher/src/context/inlineAgentProvider.ts
- ts/packages/dispatcher/src/execute/actionHandlers.ts
- ts/packages/dispatcher/src/internal.ts
- Fix the regression from request+action format in the explanation prompt, which should have `fullActionName` instead of  `translatorName+actionName`.
- Construction support rehydrating empty array value for schema that required array (instead of leaving it optional)
- Properly implement normalization for construction round trip test results for comparison (lower case for example).   The normalization should only do that for values, not property names.
- Add `--cache` for the `cli test translate` command to enable using  imported the constructions for the translation tests.
- Update the explanation test files based on current schema.
> Cache fixes and improvements

- ts/packages/agents/browser/src/agent/discovery/actionHandler.mts
- ts/packages/agents/browser/src/agent/discovery/schema/discoveryActions.mts
- ts/packages/agents/browser/src/agent/discovery/schema/expandDescription.mts
- ts/packages/agents/browser/src/agent/discovery/schema/recordedActions.mts
- ts/packages/agents/browser/src/agent/discovery/translator.mts
- ts/packages/agents/browser/src/extension/serviceWorker.ts
- ts/packages/agents/browser/src/extension/sidepanel.html
- ts/packages/agents/browser/src/extension/sidepanel.ts
- ts/packages/agents/browser/src/extension/uiEventsDispatcher.ts
- add logic to have model expand the user-provided description into a more detailed list of UI actions.
- add dedupe logic to the prompt so that the model generates unique action names
> Sidepanel: Enable users to add new actions schema using descriptions in natural language

- ts/packages/actionSchema/src/index.ts
- ts/packages/actionSchema/src/parser.ts
- ts/packages/actionSchema/src/serialize.ts
- ts/packages/actionSchema/src/type.ts
- ts/packages/actionSchema/test/parse.spec.ts
- ts/packages/actionSchema/test/regen.spec.ts
- ts/packages/actionSchemaCompiler/src/index.ts
- ts/packages/agentSdk/src/agentInterface.ts
- ts/packages/agentSdk/src/index.ts
- ts/packages/agents/browser/src/agent/discovery/actionHandler.mts
- ts/packages/agents/browser/src/extension/sites/paleobiodb.ts
- ts/packages/agents/player/package.json
- ts/packages/agents/player/src/agent/playerManifest.json
- ts/packages/agents/turtle/src/site/index.ts
- ts/packages/dispatcher/src/context/appAgentManager.ts
- ts/packages/dispatcher/src/context/system/handlers/actionCommandHandler.ts
- ts/packages/dispatcher/src/translation/actionConfig.ts
- ts/packages/dispatcher/src/translation/actionConfigProvider.ts
- ts/packages/dispatcher/src/translation/actionSchemaFileCache.ts
- ts/packages/dispatcher/src/translation/actionSchemaJsonTranslator.ts
- ts/packages/dispatcher/src/translation/actionSchemaSemanticMap.ts
- ts/packages/dispatcher/src/translation/actionTemplate.ts
- ts/packages/dispatcher/src/translation/agentTranslators.ts
- ts/packages/dispatcher/src/translation/translateRequest.ts
- ts/packages/dispatcher/src/translation/unknownSwitcher.ts
- Establish "Parsed Action Schema" as the name of the native action schema format that TypeAgent uses.
- Format type change from `json` to `pas`
- File extension change from `.json` to  `.pas.json`
- Move the hash, which is only needed for cache, out of the `action-schema` package.
> Parsed Action Schema

- ts/packages/actionSchema/src/parser.ts
- ts/packages/actionSchema/src/serialize.ts
- ts/packages/actionSchema/test/paramSpec.spec.ts
- ts/packages/actionSchema/test/parse.spec.ts
- ts/packages/actionSchema/test/regen.spec.ts
- ts/packages/dispatcher/src/translation/actionSchemaFileCache.ts
- When processing param spec, type reference needs to be resolved for arrays as well.
- Add tests for paramSpec checks.
- Remove need to pass in schema name to the `action-schema` library.  Caller will add to the error message if exception happens.
> Fix processing param spec for type reference in array 

- ts/packages/agents/chat/src/chatResponseActionSchema.ts
- ts/packages/agents/chat/src/chatResponseHandler.ts
- ts/packages/defaultAgentProvider/test/data/translate-e2e.json
- ts/packages/defaultAgentProvider/test/data/translate-history-e2e.json
- ts/packages/defaultAgentProvider/test/data/translate-image-history-e2e.json
- ts/packages/dispatcher/src/context/chatHistoryPrompt.ts
- Break up `lookupAndResponse` with different information sources (conversation and internet search) to move in the direction that this becomes an extension point.
- Rename to `lookupAndAnswer`
- manually ran tested with `cli test translate` stability test with no regression.
> Refactor lookupAndResponse with different information sources.

- ts/examples/docuProc/package.json
**Solution**: Run pip in user mode.
```
warning during command 'node -e "const { execSync } = require('child_process'); try { execSync('python3 --version', { stdio: 'ignore' }); execSync('python3 -m pip install -qq -r requirements.txt', { stdio: 'inherit' }); } catch { try { execSync('python --version', { stdio: 'ignore' }); execSync('python -m pip install -qq -r requirements.txt', { stdio: 'inherit' }); } catch { console.log('Python not found, skipping...'); } }"'
Python not found, skipping...
error: externally-managed-environment
× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
python3-xyz, where xyz is the package you are trying to
install.
If you wish to install a non-Debian-packaged Python package,
create a virtual environment using …
```
> Fix build warning on debian

- ts/examples/docuProc/package.json
- Running this as part of build was causing:
```
PEP 668, which prevents system-wide Python package installations to protect the integrity of system-managed environments
```
> Install python dependencies in prerun step instead of build

- ts/packages/agentRpc/src/client.ts
- ts/packages/agentRpc/src/server.ts
- ts/packages/agentRpc/src/types.ts
- ts/packages/agentSdk/src/agentInterface.ts
- ts/packages/agents/player/package.json
- ts/packages/agents/player/src/agent/playerCommands.ts
- ts/packages/agents/player/src/agent/playerHandlers.ts
- ts/packages/agents/player/src/client.ts
- ts/packages/agents/player/src/index.ts
- ts/packages/agents/player/src/tokenProvider.ts
- ts/packages/dispatcher/src/execute/storageImpl.ts
If we don't have a refresh token to log into spotify, avoid asking the user to log in (popup window) on load.
Implemented command `@player spotify login` to start the log in flow, and `@player spotify logout` to log out and clear the token cache.
> Implement silent login flow on initialize

- ts/packages/actionSchema/src/index.ts
- ts/packages/actionSchema/src/jsonSchemaGenerator.ts
- ts/packages/actionSchema/src/jsonSchemaParser.ts
- ts/packages/actionSchema/src/jsonSchemaTypes.ts
- ts/packages/agentSdk/src/index.ts
- ts/packages/defaultAgentProvider/data/config.json
- ts/packages/defaultAgentProvider/package.json
- ts/packages/defaultAgentProvider/src/defaultAgentProviders.ts
- ts/packages/defaultAgentProvider/src/mcpAgentProvider.ts
- ts/packages/defaultAgentProvider/src/mcpDefaultAgentProvider.ts
- ts/packages/defaultAgentProvider/src/utils/config.ts
- ts/packages/defaultAgentProvider/test/basic.spec.ts
- ts/packages/dispatcher/src/agentProvider/agentProvider.ts
- ts/packages/dispatcher/src/agentProvider/npmAgentProvider.ts
- ts/packages/dispatcher/src/context/appAgentManager.ts
- ts/packages/dispatcher/src/context/inlineAgentProvider.ts
- ts/packages/dispatcher/src/context/system/handlers/installCommandHandlers.ts
- ts/packages/dispatcher/src/context/system/handlers/runScriptCommandHandler.ts
- ts/packages/dispatcher/src/npmAgentProvider.ts
- ts/packages/dispatcher/src/translation/actionSchemaFileCache.ts
- ts/packages/dispatcher/src/utils/fsUtils.ts
- ts/packages/dispatcher/test/command.spec.ts
- ts/packages/shell/src/main/agent.ts
- ts/packages/shell/src/main/demo.ts
- ts/packages/shell/src/main/index.ts
- ts/pnpm-lock.yaml
Added MCP file system agent (`mcpfilesystem`) as an example of auto MCP integration to TypeAgent.
- The agent `mcpfilesystem` is not enabled by default.  Use `@config agent mcpfilesystem` to enable
- On first run, enabling schema and action will show an error because the allowed directories need to be provided.  Use the command `@mcpfilesystem server <directory>...` to configure.   A restart is needed afterwards.
Details:
- Implement Tools JSON schema converter to our parsed action schema format, which can generate TS or back to JSON schema for prompts.
- Implemented MCP agent provider to automatically wrap a stdio MCP server. (can be extend to other transport in the future.
Other changes: 
- Allow schema parse error to be non-fatal at start up (but disable the schema)
- Shell will catch …
> Example MCP integration.

- python/ta/TODO.md
- python/ta/demo.py
- python/ta/typeagent/aitools/auth.py
- python/ta/typeagent/aitools/embeddings.py
- python/ta/typeagent/aitools/vectorbase.py
- python/ta/typeagent/knowpro/serialization.py
- python/ta/typeagent/podcasts/__main__.py
- python/ta/typeagent/podcasts/podcast.py
Also:
- Centralize dotenv call (now auth.load_dotenv())
- Make sure np.float32 values are converted to Python float.
- read_conversation_data_from_file() has no reason (yet) to be async, and neiter does read_from_file()
- Use all absolute imports in podcasts/__main__.py (so you can run it as a script)
- Add PodcastMessage.deserialize() and use it
- Remove commented-out Podcast._build_caches(), it has vanished from the TS version too
> [python/knowpro] Fix VectorBase.add_key(); improve demo.py output; misc improvements

- ts/packages/agentSdk/src/memory.ts
- ts/packages/agents/calendar/src/calendarActionHandlerV1.ts
- ts/packages/agents/calendar/src/calendarActionHandlerV2.ts
- ts/packages/agents/image/src/imageActionHandler.ts
- ts/packages/agents/montage/src/agent/montageActionHandler.ts
- ts/packages/agents/spelunker/src/searchCode.ts
- ts/packages/agents/spelunker/src/spelunkerActionHandler.ts
It is populated but not used anywhere.   Should use uniqueId for round tripping information.
> Remove additionalEntityText

- ts/packages/shell/src/main/agent.ts
- ts/packages/shell/src/main/index.ts
- ts/packages/shell/src/main/shellSettings.ts
- ts/packages/shell/src/main/shellWindow.ts
- Create `ShellWindow` class to manage the main window and the views.
- ShellAgent have access to the ShellWindow, instead of going thru late bound functions thru ShellSettings (this will allow window to be recreated in the future.
Other fixes:
- Make sure position is saved on linux by listen to "move" instead "moved" event.
- Remove move/resize event on close so it doesn't get updated with wrong value while closing.
> Refactor shell's windowing code.

- ts/packages/agents/greeting/src/greetingCommandHandler.ts
- ts/packages/api/src/webDispatcher.ts
- ts/packages/shell/electron.vite.config.mts
- ts/packages/shell/src/main/agent.ts
- ts/packages/shell/src/main/demo.ts
- ts/packages/shell/src/main/index.ts
- ts/packages/shell/src/main/shellSettings.ts
- ts/packages/shell/src/main/shellWindow.ts
- ts/packages/shell/src/preload/electronTypes.ts
- ts/packages/shell/src/preload/index.ts
- ts/packages/shell/src/preload/main.ts
- ts/packages/shell/src/renderer/src/chatView.ts
- ts/packages/shell/src/renderer/src/main.ts
- ts/packages/shell/src/renderer/src/settingsView.ts
- ts/packages/shell/src/renderer/src/webSocketAPI.ts
- Instead of register handler for each main->renderer call individually, set it up with one "register call" in the reload script.
- Refer to settings in the shellWindow instead of getting it thru ShellSettings.getinstance() when possible.
- Fix greeting agent that if the call the Azure CLI failed to get the current user name, it should still resolve the promise.
- Change the chat history from pushing from main to render, to instead have the render call the main process to get the history.
- The full electronAPI is no longer exposed in the chat view.
> Refactor Client API and others

- ts/packages/dispatcher/src/context/appAgentManager.ts
- ts/packages/dispatcher/src/context/appAgentStateConfig.ts
- ts/packages/dispatcher/src/context/session.ts
- ts/packages/dispatcher/src/context/system/handlers/sessionCommandHandlers.ts
Avoid session.ts depending on the full appAgentManager.ts (which pulls in @azure/msal-node-extensions which require libsecret).
> Reduce dependency of session

- ts/packages/agentRpc/src/client.ts
- ts/packages/agentRpc/src/common.ts
- ts/packages/agentRpc/src/server.ts
- ts/packages/agents/desktop/src/actionHandler.ts
- ts/packages/dispatcher/src/agentProvider/agentProvider.ts
- ts/packages/dispatcher/src/agentProvider/npmAgentProvider.ts
- ts/packages/dispatcher/src/agentProvider/process/agentProcess.ts
- ts/packages/dispatcher/src/agentProvider/process/agentProcessShim.ts
- ts/packages/dispatcher/src/context/appAgentManager.ts
- ts/packages/dispatcher/src/context/system/handlers/traceCommandHandler.ts
When trace settings are modified using `@trace` command, make sure the agent processes are updated as well.
> Agent process inherit trace settings

- ts/packages/agents/browser/src/agent/actionHandler.mts
- ts/packages/agents/browser/src/agent/crossword/actionHandler.mts
- ts/packages/agents/browser/src/agent/crossword/schema/pageComponents.mts
- ts/packages/agents/browser/src/agent/crossword/translator.mts
- If schema initialization is still running, run user actions using a slow path, where we pass the HTML to LLM and ask for the relevant clue element.
> Enable crossword interactions while schema initialization is running

- ts/packages/shell/electron-builder.config.js
`electron-builder` didn't detect `.so.42` extension as binary in `@img/sharp-lib*` packages.  Explicitly for them to be "unpacked"
> Fix linux package

- ts/packages/memory/storage/src/fileSystem.ts
Get occasional failure in `sqliteCommon.ts` createDatabase function in test complaining unable to create database because the path doesn't exist.  That's because in `ensureDir`, it calls the promise version of `mkdir` without await.  So it doesn't guarantee that the directory is actually created before it returns.   Switch to the `sync` version
> Fix test instability

- ts/packages/shell/package.json
- ts/packages/shell/src/main/args.ts
- ts/packages/shell/src/main/commands/update.ts
- ts/packages/shell/src/main/index.ts
- ts/packages/shell/src/main/shellWindow.ts
- ts/pnpm-lock.yaml
- ts/tools/scripts/install-shell.cmd
- Don't need to use @electron-toolkit/utils to watch for shortcut, which only works on the main browser window anyways.  
- Move the F12 handler for web content to be global.
- Clean up usage of @electron-toolkit/utils
- Add more flags to able to debug packaged builds.
- Switch data directory to the electron user data directory.
- Add `--clean` flag to clear all data.
> Shell remove duplicate dev tool handler

- pipelines/azure-build-package-shell.yml
- pipelines/include-install-pnpm.yml
- Cache electron-builder downloads
- Use internal feed for npm packages.
- Pnpm cache should be separate based on arch as well
- Disable manually building 'ci' channel
> Azure package pipeline improvements

- ts/packages/shell/src/renderer/src/chatInput.ts
When not pasting files:
- Call preventDefault on paste.
- Use `getData("text/plain")` api to get only the text from the transfered data.
- Insert the pasted content at cursor/replace selection.  (Instead of always append with HTML, or replace when it is text.)
- Drag and drop will replace the content like before.
> Shell fix paste

- python/ta/Makefile
- python/ta/TODO.md
- python/ta/make.bat
- python/ta/test/test_collections.py
- python/ta/test/test_interfaces.py
- python/ta/typeagent/knowpro/collections.py
- python/ta/typeagent/knowpro/interfaces.py
**In collections.py:**
- In `MatchAccumulator`, implement `get_sorted_by_score`, `_matches_with_min_hit_count`
- In `SemanticRefAccumulator`, implement many methods, from `add_term_matches_if_new` to `get_matches_in_scope`
- Add new classes `TextRangeCollection` and `TextRangesInScope`. (@Umesh: I have some questions about `is_range_in_scope` and `is_in_range`.)
**In interfaces.py:**
- Add correct `__lt__` etc. to `TextRange` (previously, ranges with `end=None` were ordered incorrectly when compared to ranges with `end=TextLocation(...)`.
- Add new definitions in the "Storage" section (`IReadonlyCollection`, `ICollection`, and derived collection types.
**Other:**
- Added `test_collections.py`.
- Updated `test_interfaces.py`.
- Updated `Makefile` and `make.bat` to restrict test collection …
> [python/knowpro] Flesh out collections.py and interfaces.py, add more tests

- ts/packages/defaultAgentProvider/test/data/translate-e2e.json
- ts/packages/dispatcher/src/context/dispatcher/schema/clarifyActionSchema.ts
- ts/packages/dispatcher/src/translation/translateRequest.ts
Avoid clarification with the test case `lookup snowdrop flowers`.
Also add trace on translator creation/caching.
> Adjust clarifyMissingParameter to only clarify if the user is asking for actions.

- ts/packages/defaultAgentProvider/test/data/translate-e2e.json
- ts/packages/defaultAgentProvider/test/data/translate-lookup-e2e.json
- ts/packages/dispatcher/src/context/dispatcher/schema/lookupActionSchema.ts
- ts/packages/dispatcher/src/helpers/userData.ts
- ts/packages/shell/src/main/keys.ts
`on the web` sometimes trigger startLookup action. Add comments to avoid that
Also:
- Clean up unused prod mode for getInstanceDir()
- Silently ignore error when loading from keyvault, and just assume we don't have any data.  This is needed when running against repro zip from other machine on windows (thes ecret is in a file encrypted a per machine key.
> Avoid starting lookup activity if the user specify what to lookup

- ts/packages/actionSchema/src/generator.ts
- ts/packages/actionSchema/src/jsonSchemaParser.ts
- ts/packages/actionSchema/src/parser.ts
- ts/packages/actionSchema/src/serialize.ts
- ts/packages/actionSchema/src/type.ts
- ts/packages/actionSchema/test/parse.spec.ts
- ts/packages/actionSchema/test/regen.spec.ts
- ts/packages/agentSdk/src/agentInterface.ts
- ts/packages/agentSdk/src/index.ts
- ts/packages/agents/list/src/listActionHandler.ts
- ts/packages/agents/list/src/listManifest.json
- ts/packages/agents/list/src/listSchema.ts
- ts/packages/cli/src/commands/schema.ts
- ts/packages/dispatcher/src/context/appAgentManager.ts
- ts/packages/dispatcher/src/context/dispatcher/dispatcherAgent.ts
- ts/packages/dispatcher/src/context/dispatcher/schema/lookupActionSchema.ts
- ts/packages/dispatcher/src/translation/actionSchemaFileCache.ts
- ts/packages/dispatcher/src/translation/actionSchemaJsonTranslator.ts
- ts/packages/dispatcher/src/translation/agentTranslators.ts
- ts/packages/dispatcher/src/translation/translateRequest.ts
- ts/packages/dispatcher/src/utils/test/explanationTestData.ts
- ts/packages/shell/test/testHelper.ts
- Separate the union type for activities and actions.
- If the schema `dispatcher.activity` is disabled, then we disable all activity actions.
> Allow activity to be disabled.

- ts/packages/defaultAgentProvider/test/basic.spec.ts
- ts/packages/shell/test/testHelper.ts
Use 3001 as the base to avoid conflict with running instance of TypeAgent shell.
> fix test port

- ts/packages/agents/email/src/emailActionsSchema.ts
Update comment for GenerateContent, without which the model could set generateBody to false.
``` code
export interface GenerateContent {
// Flag to indicate if body content needs to be generated using a web search based on the user request.
// If the user request can be answered using a web search, set this flag to true and provide the search query.
// For Ex: If the user input is "Send email to Megan with notes about the RLHF on instruction tuning of LLMs",
// the flag should be true and the body should be generated using a web search for "RLHF on instruction tuning of LLMs"
// Ex: If the user input is something to the effect "sending email to Bob with the recipe for a vanilla cake",
// the flag should be true and the body should be generated using a web search for "recipe for a vanilla …
```
> Minor update to the email agent schema

- ts/packages/cli/src/commands/schema.ts
- ts/packages/dispatcher/src/translation/actionSchemaFileCache.ts
- ts/packages/dispatcher/src/translation/actionSchemaJsonTranslator.ts
- ts/packages/dispatcher/src/translation/agentTranslators.ts
- ts/packages/dispatcher/src/translation/unknownSwitcher.ts
With separate activity type, the type name needs to be combined.
This is regression from #1059
> Fix unknown assistant switcher

- ts/packages/agentRpc/src/client.ts
- ts/packages/agentRpc/src/server.ts
- ts/packages/agentRpc/src/types.ts
- ts/packages/agentSdk/src/action.ts
- ts/packages/agentSdk/src/agentInterface.ts
- ts/packages/agentSdk/src/index.ts
- ts/packages/agents/browser/src/agent/actionHandler.mts
- ts/packages/agents/browser/src/agent/commerce/actionHandler.mts
- ts/packages/agents/browser/src/extension/serviceWorker/browserActions.ts
- ts/packages/agents/markdown/src/agent/markdownActionHandler.ts
- ts/packages/agents/markdown/src/agent/markdownManifest.json
- ts/packages/agents/markdown/src/view/route/service.ts
- ts/packages/agents/montage/src/agent/montageActionHandler.ts
- ts/packages/agents/montage/src/agent/montageManifest.json
- ts/packages/agents/montage/src/route/route.ts
- ts/packages/agents/planVisualizer/src/agent/planViewActionHandler.ts
- ts/packages/agents/planVisualizer/src/agent/planViewManifest.json
- ts/packages/agents/planVisualizer/src/view/server/server.ts
- ts/packages/dispatcher/src/context/appAgentManager.ts
- ts/packages/dispatcher/src/context/commandHandlerContext.ts
- ts/packages/dispatcher/src/context/interactiveIO.ts
- ts/packages/dispatcher/src/execute/actionHandlers.ts
- ts/packages/dispatcher/src/helpers/console.ts
- ts/packages/dispatcher/src/rpc/clientIOClient.ts
- ts/packages/dispatcher/src/rpc/clientIOServer.ts
- ts/packages/dispatcher/src/rpc/clientIOTypes.ts
- ts/packages/shell/src/main/agent.ts
- ts/packages/shell/src/main/commands/update.ts
- ts/packages/shell/src/main/index.ts
- ts/packages/shell/src/renderer/src/main.ts
- Activity can indicate whether to open the view for the agent or not.  (used in `startEditMontage` action )
- Manifest declares whether the agent has a localhost view and dispatcher will centralize port assignment for them.
- Experimental API to allow other agent to get the port based on permissions set during dispatcher initialization (e.g. 'shell' can access any local host view), or the agent's manifest can declare who can access it (`browser` can connect to `planVisualizer`
> Enable activites to open view.

- ts/examples/agentExamples/measure/src/database.ts
- ts/examples/memoryProviders/src/sqlite/common.ts
- ts/package.json
- ts/packages/agents/spelunker/src/databaseUtils.ts
- ts/packages/defaultAgentProvider/package.json
- ts/packages/memory/storage/src/sqlite/sqliteCommon.ts
- ts/packages/shell/electron-builder.config.js
- ts/pnpm-lock.yaml
- Repeat `pnpm i` was leaving the node version for electron to use because of .forge-meta indicate that it is set up already.  Delete the build directory everytime to force it to be refresh again.
- Change the location of the node version of the binary for `binding` package to find as well so that an explicit native path is no longer necesary.
- Filter out binaries that doesn't match with packaged installer.
> better-sqlite3 dual node/electron setup for native modules

- azure/README.MD
- ts/packages/dispatcher/package.json
- ts/packages/shell/electron-builder.config.js
- ts/packages/shell/package.json
- ts/packages/shell/src/main/agent.ts
- ts/pnpm-lock.yaml
- Make sure the action schema ts file are included in the installed package.  (Fixes dispatcher and shell actions)
- Make sure we specify the right path for the shell action schema (no matter where it is installed)
- Exclude source map and TS type files from the installed package.
- Don't include the font package in the ASAR.  (it is already in the assets directory)
> Reduce size and fix install packages

- ts/packages/dispatcher/src/execute/actionHandlers.ts
- ts/packages/dispatcher/src/translation/multipleActionSchema.ts
- ts/packages/telemetry/package.json
- ts/pnpm-lock.yaml
- result reference follows the format `${result-<name>}`
- Replace the parameter name when entity or result are referenced by the entity name.
- Don't pass the entity when entity or result is referenced across agents.
- Error when entity and result reference is not resolved.
- Make sure the result is scoped to the single set of "actions" (e.g. the result shouldn't be used by newly translated pending actions.
- Error if result entity is expected but the action didn't return any result entity.
> Improve error checking in entity resolution

- ts/examples/agentExamples/measure/src/database.ts
- ts/examples/memoryProviders/src/sqlite/common.ts
- ts/package.json
- ts/packages/agents/spelunker/src/databaseUtils.ts
- ts/packages/memory/storage/src/sqlite/sqliteCommon.ts
Revert part to #1101.  `binding` package only retry different path if the load error is "not found"
> Reinstate special handler better-sqlite3 to load native module for node

- ts/examples/chat/README.md
- ts/examples/chat/src/memory/knowproConversation.ts
- ts/examples/chat/src/memory/knowproDataFrame.ts
- ts/examples/chat/src/memory/knowproEmail.ts
- ts/examples/chat/src/memory/knowproImage.ts
- ts/examples/chat/src/memory/knowproMemory.ts
- ts/examples/chat/src/memory/knowproPodcast.ts
- ts/examples/chat/src/memory/knowproPrinter.ts
Knowpro example:
* Refactored podcast and image into their own files. Just like email, conversation & dataframe
* knowproMemory now contains standard commands that apply to any conversation
* Updated README
> knowpro: Refactored test apps for clarity

- ts/packages/actionSchema/src/parser.ts
- ts/packages/actionSchema/src/serialize.ts
- ts/packages/actionSchema/src/type.ts
- ts/packages/actionSchema/test/regen.spec.ts
- ts/packages/agentRpc/src/client.ts
- ts/packages/agentRpc/src/server.ts
- ts/packages/agentRpc/src/types.ts
- ts/packages/agentSdk/src/agentInterface.ts
- ts/packages/agents/montage/src/agent/montageActionHandler.ts
- ts/packages/agents/montage/src/agent/montageActionSchema.ts
- ts/packages/agents/montage/src/agent/montageManifest.json
- ts/packages/dispatcher/src/execute/actionHandlers.ts
- ts/packages/dispatcher/src/translation/actionSchemaFileCache.ts
- ts/packages/dispatcher/src/translation/actionSchemaJsonTranslator.ts
- ts/packages/dispatcher/src/translation/agentTranslators.ts
- ts/packages/dispatcher/src/translation/unknownSwitcher.ts
Add the infrastructure to resolve entity before execution.  Setting up for future implementation of clarification flow if the name is not an exact match.
> Resolve Entity before execute

- ts/packages/dispatcher/src/context/system/handlers/serviceHost/service.ts
- ts/packages/shell/src/main/agent.ts
- ts/packages/shell/src/main/browserIpc.ts
- ts/packages/shell/src/main/shellActionSchema.ts
- ts/packages/shell/src/main/shellWindow.ts
- Fix two issues with the message with the result from the dispatcher to the browser doesn't get thru because
- The data sometimes are blobs.
- The Electron IPC channel name is `"received-from-browser-ipc` instead of webView
- Add turtle graphics as one of the sites for shell open action.
- Fix spelling.
> Fix inline browser extension message round trip for WebAgent 

- azure/parameters.json
- azure/template.json
- ts/packages/aiclient/src/azureSettings.ts
- ts/packages/aiclient/src/restClient.ts
- ts/packages/shell/src/main/index.ts
- Make the azure ARM template work with just the command `az deployment sub create --template-file template.json --location eastus` after logged in to AzCLI and chosen the default subscription.
- Remove non-essential services (mongodb and storage accounts for the docker service, will add those separately later if needed)
- Reduce capacity to reasonable level for trying things out to fit the default quota.
- Change it to deploy to a subscription and automatically create everything, including RBAC role assignments, and keyvault value.
- TypeAgent will assume authentication using "identity" when key is missing.
Remaining work not in this PR:
- Need to switch our search API/implementation because Bing search API is going away.
- The key vault is using the same name per region, so will …
> Azure ARM template

- ts/packages/actionSchema/src/utils.ts
- ts/packages/agentSdk/src/agentInterface.ts
- ts/packages/agents/montage/src/agent/montageActionHandler.ts
- ts/packages/agents/montage/src/route/route.ts
- ts/packages/agents/montage/src/site/photo.ts
- ts/packages/dispatcher/src/execute/actionHandlers.ts
- Make sure we track the original type before `resolveReference`, when resolving entity so that we can trigger the `resolveEntity` call to the agent
- Agent will now return possible matches to allow dispatcher to build heuristic in resolving which entity to resolve to (not in this PR)
> Resolve entity

- ts/packages/actionSchema/src/serialize.ts
- ts/packages/dispatcher/src/translation/actionSchemaFileCache.ts
When loading from cache file, we need to clone the data before modifying it, so that the change doesn't get persist back into the cache.
> Fix schema cache

- ts/packages/agents/browser/src/agent/actionHandler.mts
- ts/packages/agents/browser/src/agent/actionsSchema.mts
- ts/packages/agents/browser/src/agent/manifest.json
- ts/packages/defaultAgentProvider/test/data/translate-browser-e2e.json
- ts/packages/defaultAgentProvider/test/translate_browser.test.ts
- ts/packages/dispatcher/src/context/appAgentManager.ts
- ts/packages/dispatcher/src/execute/actionHandlers.ts
- ts/packages/dispatcher/src/execute/pendingActions.ts
- Add comment in the action schema to push the model to not translate the URL based on trained data, which could be outdated, and allow the agent to resolve the URL based on current grounded information instead  (also added test)
- Test if the input for site is already an URL and directly return it.
- Restore the try/catch around the local port resolution so that it doesn't throw if the input is not an agent name
- Add status message when resolving entities (which can take a while for web pages)
> Improve unknown page open experience.

- ts/packages/cli/src/commands/replay.ts
- ts/packages/cli/src/commands/test/translate.ts
- ts/packages/dispatcher/src/context/system/handlers/constructionCommandHandlers.ts
- ts/packages/dispatcher/src/context/system/handlers/historyCommandHandler.ts
- ts/packages/dispatcher/src/execute/pendingActions.ts
- ts/packages/dispatcher/src/utils/commandHandlerUtils.ts
- Add command `@history save` to save chat history.
- Add CLI command `cli replay` to replay from the chat history.
Also,
- Fix entity array resolution to not add array of undefined values.
- Fix CLI command argument description for `cli test translate`
- Fix `@history insert` output message when only one assistant entry object it provided instead of an array.
> Save and replay from chat history

- python/ta/make.bat
- python/ta/typeagent/demo/ui.py
Several fixups in make.bat, and make readline optional in ui.py.
> [python/knowpro] Make '.\make.bat demo' actually work (on Windows)

- python/ta/typeagent/knowpro/interfaces.py
- python/ta/typeagent/knowpro/query.py
- python/ta/typeagent/knowpro/search.py
- python/ta/typeagent/knowpro/searchlang.py
There was a one-line bugfix in searchlang.py (compile_when() wasn't returning what it had computed).
The rest was implementing missing things in query.py and search.py. (There's still more missing, but not exercised much.)
Oh, and one tweak to interfaces.py: Fix the repr() of DateRange to enclose the arguments in string quotes, so pretty_print() can handle it.
> [python/knowpro] Queries including a time range work!

- ts/packages/agentRpc/src/client.ts
- ts/packages/agentRpc/src/rpc.ts
- ts/packages/agentRpc/src/server.ts
- ts/packages/agents/browser/src/agent/actionHandler.mts
- ts/packages/agents/browser/src/agent/interface.mts
- ts/packages/agents/browser/src/agent/rpc/externalBrowserControlClient.mts
- ts/packages/agents/browser/src/agent/webTypeAgent.mts
- ts/packages/agents/browser/src/extension/serviceWorker/externalBrowserControlServer.ts
- ts/packages/agents/browser/src/extension/serviceWorker/websocket.ts
- ts/packages/dispatcher/src/rpc/clientIOClient.ts
- ts/packages/dispatcher/src/rpc/clientIOServer.ts
- ts/packages/dispatcher/src/rpc/dispatcherClient.ts
- ts/packages/dispatcher/src/rpc/dispatcherServer.ts
- ts/packages/shell/src/main/inlineBrowserControl.ts
- ts/packages/shell/src/preload/webView.ts
Also, add names to RPC debug trace
> Browser RPC: change `siteTranslatorStatus` to RPC call `setAgentStatus`

- ts/packages/agentSdk/src/helpers/actionHelpers.ts
- ts/packages/agents/browser/src/agent/actionHandler.mts
- ts/packages/agents/browser/src/agent/browserControl.mts
- ts/packages/agents/browser/src/agent/rpc/externalBrowserControlClient.mts
- ts/packages/agents/browser/src/common/contentScriptRpc/client.mts
- ts/packages/agents/browser/src/common/contentScriptRpc/types.mts
- ts/packages/agents/browser/src/extension/contentScript/eventHandlers.ts
- ts/packages/agents/browser/src/extension/serviceWorker/browserActions.ts
- ts/packages/agents/browser/src/extension/serviceWorker/externalBrowserControlServer.ts
- ts/packages/agents/list/src/listActionHandler.ts
- ts/packages/agents/montage/src/agent/montageActionHandler.ts
- ts/packages/agents/spelunker/src/searchCode.ts
- ts/packages/dispatcher/src/context/dispatcher/dispatcherAgent.ts
- ts/packages/dispatcher/src/execute/actionHandlers.ts
- ts/packages/shell/src/main/inlineBrowserControl.ts
- ts/packages/shell/src/preload/webView.ts
- ts/packages/shell/src/renderer/src/setContent.ts
- Implement follow link actions using RPC.  
- Show result to the user, including link not found.
- Fix `exitActivity`, clear the activity context before queueing `additionalAction`
- Add `literalString` parameter to `createActionResultFromMarkdownDisplay`
- Links in markdown for display should open in a new browser, in the chat display context.
> Browser RPC: follow link

- ts/packages/agentRpc/src/client.ts
- ts/packages/agents/browser/src/agent/actionHandler.mts
- ts/packages/agents/browser/src/agent/actionsSchema.mts
- ts/packages/agents/browser/src/agent/browserControl.mts
- ts/packages/agents/browser/src/agent/rpc/externalBrowserControlClient.mts
- ts/packages/agents/browser/src/common/contentScriptRpc/client.mts
- ts/packages/agents/browser/src/common/contentScriptRpc/types.mts
- ts/packages/agents/browser/src/extension/contentScript/eventHandlers.ts
- ts/packages/agents/browser/src/extension/serviceWorker/browserActions.ts
- ts/packages/agents/browser/src/extension/serviceWorker/externalBrowserControlServer.ts
- ts/packages/agents/browser/src/extension/serviceWorker/websocket.ts
- ts/packages/agents/browser/src/extension/sites/paleobiodb.ts
- ts/packages/shell/src/main/inlineBrowserControl.ts
- ts/packages/shell/src/preload/inlineBrowserRendererRpcServer.ts
- ts/packages/shell/src/preload/webView.ts
- Move `zoomIn`, `zoomOut`, `zoomReset` to use browser RPC.
- Fix the problem with changing active tab while a browser control is being run, by create a different RPC object per tab. Enable detection of disconnection error when tab get closed during a call.
- Change all external browser control to throw error if there is no active tab or active tab doesn't have id.
- Provide the "this" object when invoking a remote RPC call on the initialization option object provided by the client.
- Fix the spelling of `paleobiodb` in the open action schema
> Browser RPC: Move zoom functionalities

- ts/packages/agents/browser/src/agent/tsconfig.json
- ts/packages/agents/browser/src/common/tsconfig.json
- ts/packages/agents/browser/src/puppeteer/tsconfig.json
- ts/packages/agents/browser/src/views/server/tsconfig.json
- ts/packages/agents/browser/src/views/shared/tsconfig.json
- ts/packages/agents/browser/tsconfig.json
- ts/packages/agents/markdown/package.json
- ts/packages/agents/markdown/src/agent/tsconfig.json
- ts/packages/agents/markdown/src/view/route/tsconfig.json
- ts/packages/agents/markdown/src/view/site/mermaid-plugin.ts
- ts/packages/agents/markdown/src/view/site/tsconfig.json
- ts/pnpm-lock.yaml
- Remove the unnecessary `tsBuildInfoFile` location. Currently `fluid-build` doesn't support specifying custom `tsBuildInfoFile`. location.  Fluid repro [PR pending](https://github.com/microsoft/FluidFramework/pull/24911)
- Also, this fix a problem where two `tsc` command output to the same `tsBuildInfo` location.
- Remove duplicate `src/view/shared` files in browser agents `tsconfig.json` in `src/view/server`, resulting mismatch of `tsc` thinking those files as input, but not included in the `tsBuildInfo`. `fluid-build` detected that and trigger the build, as those could be "new" files for the build that needs to be process.
- Markdown agent's `src/view/site` 
- must be `composite` for `incremental` to be enabled in `tsc` (which `fuild-build` relies on).  
- Fix typing errro after …
> Fix `tsc` incremental build in browser and markdown agent

- ts/packages/agents/browser/scripts/prepare.mjs
In case that the path has space.
> Fix browser extension build: make sure the node executable path in the build script is quoted 

- ts/packages/agents/browser/src/agent/actionHandler.mts
- ts/packages/agents/browser/src/agent/browserConnector.mts
- ts/packages/agents/browser/src/agent/crossword/actionHandler.mts
- ts/packages/agents/browser/src/agent/crossword/cachedSchema.mts
- ts/packages/agents/browser/src/agent/crossword/commandHandler.mts
- ts/packages/agents/browser/src/extension/contentScript/eventHandlers.ts
- ts/packages/agents/browser/src/extension/serviceWorker/browserActions.ts
- ts/packages/agents/browser/src/extension/serviceWorker/contextMenu.ts
- ts/packages/agents/browser/src/extension/serviceWorker/storage.ts
- ts/packages/agents/browser/test/serviceWorker/contextMenu.test.ts
- ts/packages/shell/src/preload/webView.ts
- Save the crossword schema cache storage with the agent instead of browser's session/local storage.
- Add `@browser crossword` commands `state init`, `state show`and `state clear` for the schema state, and `schema clear` for schema cache.
> Move crossword schema cache storage locally

- ts/packages/agents/browser/scripts/buildExtension.mjs
Set `configFile: false`  in the vite config for building extension to not load the config file (which only applies to the view.
> Browser extension build fix

- ts/packages/agentRpc/src/client.ts
- ts/packages/agentRpc/src/server.ts
- ts/packages/agentRpc/src/types.ts
- ts/packages/agentSdk/src/agentInterface.ts
- ts/packages/agents/browser/src/agent/actionHandler.mts
- ts/packages/agents/browser/src/agent/manifest.json
- ts/packages/agents/browser/src/agent/rpc/externalBrowserControlClient.mts
- ts/packages/agents/browser/src/common/browserControl.mts
- ts/packages/agents/browser/src/extension/serviceWorker/externalBrowserControlServer.ts
- ts/packages/dispatcher/src/command/command.ts
- ts/packages/dispatcher/src/context/commandHandlerContext.ts
- ts/packages/dispatcher/src/execute/actionContext.ts
- ts/packages/shell/src/main/inlineBrowserControl.ts
- ts/packages/shell/src/main/shellWindow.ts
- ts/packages/shell/src/preload/webView.ts
Also add API so that we can queue toggle transient agent at the end of the command (instead of using `toggleTransientAgent` which is for background call, and cannot be call "in command"
> Browser RPC: Move external browser window close to use RPC

- ts/packages/dispatcher/package.json
- ts/packages/dispatcher/src/context/commandHandlerContext.ts
- ts/packages/dispatcher/src/context/dispatcher/handlers/requestCommandHandler.ts
- ts/packages/dispatcher/src/context/memory.ts
- ts/packages/dispatcher/src/execute/actionHandlers.ts
- ts/packages/dispatcher/src/translation/confirmTranslation.ts
- ts/packages/dispatcher/src/translation/matchRequest.ts
- ts/packages/dispatcher/src/translation/translateRequest.ts
- ts/packages/memory/conversation/src/conversationMemory.ts
- ts/pnpm-lock.yaml
- Using `conversation-memory` to start remembering conversation (in addition to conversation manager, which we will deprecate in the future). The data is not used yet.  
- Refactor the translation flow to use exception for error and record it in the conversation history and memory if it failed.
> Dispatcher knowpro initial integration

- ts/packages/dispatcher/src/context/memory.ts
- ts/packages/knowPro/src/index.ts
- ts/packages/knowPro/src/knowledge.ts
- ts/packages/knowPro/src/knowledgeMergeEx.ts
- ts/packages/knowPro/test/knowledgeMerge.spec.ts
- ts/packages/memory/conversation/src/memory.ts
- Create a new function `mergeConcreteEntitiesEx` (based on current `mergeConcretEntities`
- won't force data to be lower case regardless of whether merge is case-sensitive or not.  
- In the case-insensitive case, it will pick the first version it encountered.
- The new code avoid extra conversion of concrete entity to merged entity for the RHS and directly merge to and existing merged entity compare to the old code.
- Added unit test for this new function.
- TOOD: after more testing for stability, replace `mergeConcreteEntities` which currently forces all the resulting entity data to be lower case.
-
> Conversation memory entity merge stop forcing data to become lower case.

- ts/examples/chat/src/memory/knowproMemory.ts
- ts/examples/chat/src/memory/knowproPrinter.ts
- ts/examples/chat/src/memory/knowproTest.ts
- ts/packages/knowPro/src/search.ts
- ts/packages/knowPro/src/searchLang.ts
- ts/packages/knowProTest/src/common.ts
- ts/packages/knowProTest/src/index.ts
- ts/packages/knowProTest/src/knowproCommands.ts
- ts/packages/knowProTest/src/knowproContext.ts
- ts/packages/knowProTest/src/logging.ts
- ts/packages/knowProTest/src/searchTest.ts
- ts/packages/knowProTest/src/types.ts
- ts/packages/typeagent/src/dateTime.ts
For debugging, testing and co-dev with Python:
* Automatically dump kpSearch and kpAnswer results with timestamps in log folder
*  kpSearch: Run previously saved, or hand edited NLP SearchQuery expr from file
* Better search expression comparison - for diffs
* Save validation run report
* Some comments
* Wrapper API to run multiple searches
> knowpro: Better diagnostics, replayability

- ts/packages/cache/src/constructions/constructionCache.ts
- ts/packages/cache/src/constructions/constructionMatch.ts
- ts/packages/cache/src/constructions/constructionPrint.ts
- ts/packages/cache/src/constructions/constructionValue.ts
- ts/packages/cache/src/constructions/constructions.ts
- ts/packages/cache/src/constructions/importConstructions.ts
- ts/packages/cache/src/constructions/matchPart.ts
- ts/packages/cache/src/constructions/parsePart.ts
- ts/packages/cache/src/index.ts
- ts/packages/defaultAgentProvider/test/construction.spec.ts
- ts/packages/defaultAgentProvider/test/constructionCacheTestCommon.ts
- ts/packages/dispatcher/src/command/completion.ts
- ts/packages/dispatcher/src/context/dispatcher/dispatcherAgent.ts
- ts/packages/dispatcher/src/context/dispatcher/handlers/requestCommandHandler.ts
- ts/packages/dispatcher/src/translation/translateRequest.ts
Initial version only provide completion for "matched" parts.
Use the cache to provide completions for natural language request by configuration to match algorithm to allow a prefix match.
> Cache completion

- python/ta/NOTES.md
- python/ta/typeagent/demo/ui.py
- python/ta/typeagent/knowpro/query.py
- python/ta/typeagent/knowpro/reltermsindex.py
- python/ta/typeagent/knowpro/searchlang.py
- python/ta/typeagent/podcasts/podcast.py
- python/ta/typeagent/podcasts/podcastVerbs.json
A 1000 thanks to @umeshma who spent nearly all day helping me debug these (and the previous commit).
- searchlang.py: Issues with datetime conversions. We established that the podcast is claimed to start on May 1st 2023 at midnight (00:00) US Pacific Time. We don't ask the LLM for a timezone and it just gives times in local time (i.e., US Pacific Time). Our query engine works in UTC so we must convert DateTimes given by the LLM in US Pacific Time to UTC. Simple once you know what the problem is.
- podcast.py: Add synonyms from podcastVerbs.json (store a copy from the TS tree in the Python tree).
- query.py: Fix bugs in how we were calling intersect() -- it returns a value which was never assigned.
- Also some little tweaks, add my NOTES.md, fix a docstring, and reformat a line in ui.py
> [python/knowpro] Fixed three more query bugs

- python/ta/TODO.md
- python/ta/tools/utool.py
- python/ta/typeagent/knowpro/convindex.py
- python/ta/typeagent/knowpro/convknowledge.py
- python/ta/typeagent/knowpro/convutils.py
- python/ta/typeagent/knowpro/interfaces.py
- python/ta/typeagent/knowpro/messageindex.py
- python/ta/typeagent/knowpro/searchlang.py
- python/ta/typeagent/knowpro/secindex.py
- python/ta/typeagent/knowpro/serialization.py
- python/ta/typeagent/knowpro/storage.py
By feeding the question-generating LLM times in UTC that aren't marked with a timezone, and assuming that times we receive back (which can't be marked with a timezone) are also in UTC, we get consistent times in time-range when-clauses, and we can answer questions like "which books were mentioned in the first 15 minutes".
Also some cleanup of TODO.md and removed redundant `# type: inore` directives. Of the latter, we now only have 8 left in podcast.py and one in convindex.py (and some in tests that I didn't look at yet).
> [python/knowpro] Solve the "first 15 minutes" problem by switching to timezone-unaware times in stage 1

- ts/packages/agents/player/src/endpoints.ts
- ts/packages/agents/player/src/userData.ts
Spotify API sometimes return 502.  Don't abort updating the user data when there are errors for only part of the calls
> player: Ignore error when updating user data

- ts/packages/shell/src/main/shellWindow.ts
- ts/packages/shell/src/preload/electronTypes.ts
- ts/packages/shell/src/preload/index.ts
- ts/packages/shell/src/renderer/assets/styles.less
- ts/packages/shell/src/renderer/src/chatInput.ts
- ts/packages/shell/src/renderer/src/chatView.ts
- ts/packages/shell/src/renderer/src/main.ts
- ts/packages/shell/src/renderer/src/messageContainer.ts
- ts/packages/shell/src/renderer/src/partial.ts
- ts/packages/shell/src/renderer/src/templateEditor.ts
- Wait for dispatcher initialized before enabling the input box and getting the first completion.
- After dispatcher initialized, get the chat view to focus to be ready for input.
- Fix the bug where input doesn't get updated after partial completion on empty input in `replaceAtCursor`
- Fix the explain hover message clipping because of the `overflow-x: auto` by attaching it to the outer container.
> Partial completion fixes

- ts/packages/agentSdk/src/display.ts
- ts/packages/agentSdk/src/helpers/actionHelpers.ts
- ts/packages/agentSdk/src/memory.ts
- ts/packages/agents/player/src/agent/playerHandlers.ts
- ts/packages/agents/player/src/agent/playerSchema.json
- ts/packages/agents/player/src/agent/playerSchema.ts
- ts/packages/agents/player/src/client.ts
- ts/packages/agents/player/src/debug.ts
- ts/packages/agents/player/src/devices.ts
- ts/packages/agents/player/src/endpoints.ts
- ts/packages/agents/player/src/playback.ts
- ts/packages/agents/player/src/settings.ts
- ts/packages/agents/player/src/volume.ts
- ts/packages/dispatcher/src/execute/actionHandlers.ts
- Make max volume for device a setting (instead of hard coded to 50)
- Player agent keep track of a user defined default device to use.
- Track the current device as user change it explicitly (instead of relying on "active" device from the server).   
- User configurable maximum volume per "device".   
- Add action to change the user defined default device, and maximum volume
> Player: improve device management and max volume settings

- ts/packages/actionSchema/src/index.ts
- ts/packages/actionSchema/src/utils.ts
- ts/packages/actionSchemaCompiler/src/index.ts
- ts/packages/agentRpc/src/client.ts
- ts/packages/agentRpc/src/server.ts
- ts/packages/agentRpc/src/types.ts
- ts/packages/agentSdk/src/agentInterface.ts
- ts/packages/agents/player/package.json
- ts/packages/agents/player/src/agent/playerHandlers.ts
- ts/packages/agents/player/src/agent/playerManifest.json
- ts/packages/agents/player/src/agent/playerSchema.ts
- ts/packages/agents/player/src/client.ts
- ts/packages/agents/player/src/devices.ts
- ts/packages/dispatcher/src/context/system/handlers/actionCommandHandler.ts
- ts/packages/dispatcher/src/execute/pendingActions.ts
- ts/packages/dispatcher/src/translation/actionTemplate.ts
- ts/packages/dispatcher/src/translation/requestCompletion.ts
- Make player music device an entity to enable action completion.
- Provide entity type (if any) to the action completion as a category on top of specific action and parameter name combo.
- Add type union support for parameter name (for `@action` flag name completion)
- Unified parameter completion between template, action command and request completions.  Better support for string literal types with entity types.
- Add support to specify entity entry type in action schema compiler.
- Make sure default device setting is saved after changed.
> Player: music device entity and completion

- ts/examples/chat/src/memory/knowproTest.ts
- ts/packages/textPro/src/common.ts
- ts/packages/textPro/src/html.ts
Html to markdown conversion:
- Now converts nested Wikipedia articles correctly
- Reworked table conversion
- Handle nested tables, lists etc. better
- Escape reserved markdown characters found in html
> Doc Memory: Html to Markdown improvements

- ts/packages/agentSdk/src/action.ts
- ts/packages/agentSdk/src/helpers/actionHelpers.ts
- ts/packages/agents/browser/src/agent/actionHandler.mts
- ts/packages/agents/chat/src/chatResponseHandler.ts
- ts/packages/agents/greeting/src/greetingCommandHandler.ts
- ts/packages/agents/player/src/agent/playerHandlers.ts
- ts/packages/agents/player/src/client.ts
- ts/packages/agents/player/src/playback.ts
- ts/packages/dispatcher/src/context/dispatcher/dispatcherAgent.ts
- ts/packages/dispatcher/src/context/memory.ts
- ts/packages/dispatcher/src/execute/actionHandlers.ts
- ts/packages/dispatcher/src/search/internet.ts
- ts/packages/dispatcher/src/search/search.ts
- Action result display content should be appended as block so that it can work with using `actionIO` within the action.  Other display option can be access thru `actionIO`
- Make sure the chat `generateResponse` and `lookupAndAnswer` doesn't display twice.
- Rename the action result's `literalText` to `historyText` to indicate that the text is used for chat history.
- Change `lookupAndAnswer` to return the resulting text in `historyText` as well along with the entities for used for chat history.
> Change action result to display as append block

- ts/packages/dispatcher/src/context/dispatcher/dispatcherAgent.ts
- ts/packages/dispatcher/src/context/dispatcher/handlers/matchCommandHandler.ts
- ts/packages/dispatcher/src/context/dispatcher/handlers/translateCommandHandler.ts
Add `@dispatcher match` command to go thru the match request code path only similar to `@dispatcher translate`.
Reuse the same completion using the cache used by the request command handler for translate and match command.
> Match command and completion for match and translate commands

- python/ta/tools/utool.py
- python/ta/tools/vizcmp.py
- python/ta/typeagent/knowpro/answer_response_schema.py
- python/ta/typeagent/knowpro/answers.py
* a35b42af vizcmp.py: Add --color={never,auto,always} flag
* 16c0aaac Percolate TypeChat errors up specially, so we can avoid printing their score
> [python/knowpro] Add --color={auto,never,always} to vizcmp.py; show TypeChat errors as N/A

- docs/content/help/commandReference.md
- ts/examples/schemaStudio/src/urlCommands.ts
- ts/examples/websiteAliases/src/main.ts
- ts/packages/agentSdk/src/helpers/displayHelpers.ts
- ts/packages/agents/browser/src/agent/actionHandler.mts
- ts/packages/agents/browser/src/agent/websiteMemory.mts
- ts/packages/agents/chat/src/chatResponseHandler.ts
- ts/packages/azure-ai-foundry/src/urlResolver.ts
- ts/packages/dispatcher/src/context/chatHistory.ts
- ts/packages/dispatcher/src/context/system/handlers/historyCommandHandler.ts
- ts/packages/dispatcher/src/execute/pendingActions.ts
- ts/packages/dispatcher/src/translation/entityResolution.ts
- Keyword lookups for URLs happens first and can short circuit other lookups
- URL lookups happen in parallel
- Also fixed a display bug in chatResponse.
- Added @history entites commands to show/delete history entities
- Removed entity reference from openWebPage, polluted by irrelevant entities being resolved
> ResolveWebPage now returns multiple URLs to allow for Clarification (if enabled)

- ts/packages/agentSdk/src/agentInterface.ts
- ts/packages/agentSdk/src/index.ts
- ts/packages/agents/browser/src/agent/manifest.json
- ts/packages/cache/src/cache/cache.ts
- ts/packages/cache/src/cache/explainWorkQueue.ts
- ts/packages/cache/src/constructions/importConstructions.ts
- ts/packages/cache/src/explanation/requestAction.ts
- ts/packages/dispatcher/src/context/dispatcher/handlers/requestCommandHandler.ts
- ts/packages/dispatcher/src/translation/actionConfig.ts
- ts/packages/dispatcher/src/translation/actionSchemaFileCache.ts
- ts/packages/dispatcher/src/translation/matchRequest.ts
- ts/packages/dispatcher/src/translation/requestCompletion.ts
- ts/packages/dispatcher/src/translation/translateRequest.ts
For now, add capability to enable caching during activity.
- By default, use of cache is disabled during activity.   
- Add property under `cachedActivites` in the agent manifest to enable cache.   
- Activity name is used as the property name.
- If the value is true then cache is enable (and shared with non-activity cache).
- If the value is `separate` then it will have a separate namespace in the cache. for the activity.
- Enable matching using activity app agent's cache (separate or shared based on config).
- PENDING: Second chance translation (with non-activity app agent) doesn't use cache yet.
- Completion will resolve completion for both activity (based on config) and non-activity cache.  (And will disable completion for the activity agent if config say to not cache)
> Allow cache behavior to be specified during activity.

- ts/packages/agents/browser/src/agent/actionHandler.mts
- ts/packages/agents/browser/src/agent/browserConnector.mts
- ts/packages/agents/browser/src/extension/serviceWorker/externalBrowserControlServer.ts
- ts/packages/agents/browser/src/extension/serviceWorker/messageHandlers.ts
- ts/packages/shell/src/main/index.ts
- ts/packages/shell/src/main/inlineBrowserControl.ts
- ts/packages/shell/src/renderer/newTab.html
- FIx https://github.com/microsoft/TypeAgent/issues/1483
- Propagate error messages from inlinebrowsercontrol and show the message to the user.
- Fix codescan warning https://github.com/microsoft/TypeAgent/security/code-scanning/181
> Fix: Shell: Browser action hang when no inline browser open

- ts/packages/shell/src/main/shellWindow.ts
NOTE: only the zoom factor of the chat canvas is saved/restored when the shell opens/closes.
> Chat canvas and tabs all independently zoom of each other.

- ts/packages/agents/browser/src/agent/actionHandler.mts
- ts/packages/agents/browser/src/agent/actionsSchema.mts
- ts/packages/agents/browser/src/agent/lookupAndAnswerSchema.mts
- ts/packages/agents/browser/src/agent/manifest.json
- ts/packages/agents/browser/src/common/browserControl.mts
- ts/packages/agents/image/src/imageManifest.json
- ts/packages/shell/src/main/inlineBrowserControl.ts
- Search tab opens by default in current tab but you can override by saying "in a new tab"
- Changed "SwitchTab" action to "ChangeTab"
- Inject only LookupAndAnswerInternet action and not all browser actions (stops taking over play action)
> Finding balance

- ts/packages/shell/src/main/agent.ts
- ts/packages/shell/src/main/browserViewManager.ts
- ts/packages/shell/src/main/index.ts
- ts/packages/shell/src/main/shellSettings.ts
- ts/packages/shell/src/main/shellWindow.ts
- ts/packages/shell/src/preload/electronTypes.ts
- ts/packages/shell/src/preload/index.ts
- ts/packages/shell/src/renderer/src/main.ts
- Shell browser tab manager view bound should be set by the mainWindow instead of detecting the chat input and set based on it.  This is so that we can move the layout around easier later
- Shell save settings for values that the user explicitly set, allow following the default that can change from build to build.
- Fix the focus input code, that might pick the wrong text area if the chat history has other text input box.
> Shell browser tab manager view bound and focus input fixes.

- ts/packages/cache/src/explanation/requestAction.ts
- ts/packages/cache/src/index.ts
- ts/packages/cli/src/commands/replay.ts
- ts/packages/commonUtils/src/objectProperty.ts
- ts/packages/defaultAgentProvider/src/mcpAgentProvider.ts
- ts/packages/defaultAgentProvider/src/mcpDefaultAgentProvider.ts
- ts/packages/defaultAgentProvider/test/constructionCacheTestCommon.ts
- ts/packages/defaultAgentProvider/test/data/translate-browser-e2e.json
- ts/packages/defaultAgentProvider/test/data/translate-e2e.json
- ts/packages/defaultAgentProvider/test/data/translate-gate-e2e.json
- ts/packages/defaultAgentProvider/test/data/translate-history-e2e.json
- ts/packages/defaultAgentProvider/test/data/translate-image-history-e2e.json
- ts/packages/defaultAgentProvider/test/data/translate-lookup-e2e.json
- ts/packages/defaultAgentProvider/test/data/translate-mcpfs-e2e.json
- ts/packages/defaultAgentProvider/test/data/translate-player-e2e.json
- ts/packages/defaultAgentProvider/test/translateTestCommon.ts
- ts/packages/dispatcher/src/context/session.ts
- LLM may generate slight variation of the translate value.  Update the test step format to allow that to be specified.
- Fix the MCP provider to not use the cached instance if config is provided.
> Translate test: enable specifying alternate values

- ts/packages/memory/conversation/src/docMemory.ts
- ts/packages/memory/website/src/websiteCollection.ts
When indexing web pages through the browser agent, knowledge extraction happens twice:
- First extraction: In indexWebPageContent(), the browser agent extracts knowledge using BrowserKnowledgeExtractor
- Second extraction: In addToConversationIndex(), the KnowPro library re-extracts knowledge if autoExtractKnowledge is true
The fix is to pass customized conversationSettings for the addToConversationIndex() call
> Fix: remove redundant knowledge extraction for web doc parts

- ts/packages/agents/browser/src/agent/actionHandler.mts
- ts/packages/agents/browser/src/agent/knowledge/knowledgeHandler.mts
- ts/packages/agents/browser/src/extension/interfaces/knowledgeExtraction.types.ts
- ts/packages/agents/browser/src/extension/serviceWorker/messageHandlers.ts
- ts/packages/agents/browser/src/extension/serviceWorker/websocket.ts
- ts/packages/agents/browser/src/extension/views/extensionServiceBase.ts
- ts/packages/agents/browser/src/extension/views/knowledgeUtilities.ts
- ts/packages/agents/browser/src/extension/views/pageKnowledge.html
- ts/packages/agents/browser/src/extension/views/pageKnowledge.ts
- Add a new mode for page knowledge extraction that streams incremental knowledge (entities, topics, actions) to the UI as it is extracted. This goes through the various knowledge extraction modes from basic (no LLM involved) to the full LLM-enabled analysis if the user selects it.
- Added progress reporting callbacks to enable agent to send incremental progress info to the UI
> Enable progressive enhancement on the page knowledge sidepanel

- ts/packages/cache/src/constructions/constructionMatch.ts
Make sure we process last matched wildcard part or trailing spaces during partial match as well.
> Cache: Fix request completion after wildcard

- ts/packages/shell/src/main/electronSearchMenuUI.ts
- ts/packages/shell/src/main/index.ts
- ts/packages/shell/src/main/shellWindow.ts
- ts/packages/shell/src/main/speech.ts
- ts/packages/shell/src/main/webViewIpcHandlers.ts
- Check IPC call sender, and use the current shell window instead of the first shell window (to eventually enable reactivation in MacOS).
- Reorganize shell init code.
> Refactor shell init code and check IPC sender

- .github/workflows/build-dotnet.yml
For PR, the dotnet solution build needs to be skipped when files in dotnet directory didn't change.
> Fix dotnet pipeline

- ts/packages/dispatcher/src/context/system/handlers/serviceHost/service.ts
- ts/packages/dispatcher/src/context/system/handlers/serviceHost/serviceHostCommandHandler.ts
- ts/packages/shell/src/main/agent.ts
- ts/packages/shell/src/main/browserIpc.ts
- ts/packages/shell/src/main/debug.ts
- ts/packages/shell/src/main/electronSearchMenuUI.ts
- ts/packages/shell/src/main/index.ts
- ts/packages/shell/src/main/instance.ts
- ts/packages/shell/src/main/shellWindow.ts
- ts/packages/shell/src/main/speech.ts
- ts/packages/shell/src/main/webViewIpcHandlers.ts
- ts/packages/shell/src/preload/chatView.ts
- Improve instance management/lifecycle to enable reloading the shell window and instance.
- Add `@shell reload` command which is the same with macOS activate after window is closed.
- Fix BrowserIpc reconnect logic to clear the promise when resolving it so that it doesn't get stuck.
> Shell: reload

- ts/packages/agents/browser/src/agent/actionHandler.mts
- ts/packages/agents/browser/src/agent/agentWebSocketServer.mts
- ts/packages/agents/browser/src/agent/browserActions.mts
- ts/packages/agents/browser/src/agent/browserConnector.mts
- ts/packages/agents/browser/src/agent/contentService.mts
- ts/packages/agents/browser/src/agent/import/importWebSocketHandler.mts
- ts/packages/agents/browser/src/agent/knowledge/knowledgeHandler.mts
- ts/packages/agents/browser/src/agent/knowledge/knowledgeWebSocketBridge.mts
- ts/packages/agents/browser/src/agent/knowledge/schema/knowledgeExtraction.mts
- ts/packages/agents/browser/src/agent/rpc/externalBrowserControlClient.mts
- ts/packages/agents/browser/src/agent/webTypeAgent.mts
- ts/packages/agents/browser/src/extension/serviceWorker/storage.ts
- ts/packages/agents/browser/src/extension/serviceWorker/websocket.ts
- ts/packages/agents/browser/src/extension/views/options.html
- ts/packages/agents/browser/src/extension/views/options.ts
- ts/packages/commonUtils/src/webSockets.ts
- ts/packages/shell/src/main/browserIpc.ts
- Update websocket clients to identify the source as extension or inline electron browser
- Use the `@browser external on/off` command to determine which client to prefer
- Implement the websocket host in the agent process to make it easier to track and route to clients
> Fix message routing when both the external browser and inline browser are active

- ts/packages/shell/src/main/shellWindow.ts
- ts/packages/shell/test/configCommands.spec.ts
- ts/packages/shell/test/sessionCommands.spec.ts
- ts/packages/shell/test/simple.spec.ts
- ts/packages/shell/test/testHelper.ts
- Fix the window detection to not check number windows (currently is 3 since we default create browser pane, but there is not much point to we have only 2 windows.)
- Use the chat view title explicitly for the window detection
- Close application in startShell smoke test.
- throw when timeout during waitForAgentMessage (instead of just return and error when the test condition is not met.
- Ignore history messages in waitForAgentMessage
- ShellWindow.startChatServer needs to return when one is already started.
> Shell: improve playwright tests stability

- ts/packages/defaultAgentProvider/test/data/translate-gate-e2e.json
- ts/packages/defaultAgentProvider/test/data/translate-history-e2e.json
- ts/packages/defaultAgentProvider/test/translateTestCommon.ts
- Fix some alternate spec to point to the right property (with array index).
- Add validation code to makes sure alternates are replacing the same type as the property
> Smoke test: Fix alternate spec

- ts/packages/shell/src/main/instance.ts
- ts/packages/shell/src/main/shellWindow.ts
- ts/packages/shell/src/preload/chatView.ts
- ts/packages/shell/src/preload/electronTypes.ts
- ts/packages/shell/src/renderer/src/chat/chatView.ts
- ts/packages/shell/src/renderer/src/main.ts
- ts/packages/shell/src/renderer/src/webSocketAPI.ts
- ts/packages/shell/test/testHelper.ts
- Title of the chat view changes after dispatcher is initialized. Use URL to identify the chat view instead.
- Make sure we sent the dispatcher-initialized signal to the chat view after chat-view is ready, and make sure the chat input is enabled synchronously (instead of waiting on the promise).  
- This improve stability of the playwright test, which uses the greeting message to indicate that finish initialization and the chat input is ready. (whereas before, because of the promise, the input might not be enabled before the greeting message is displayed)
> Shell test: Use URL to detect chat view

- ts/packages/agents/browser/src/agent/actionHandler.mts
- ts/packages/agents/markdown/src/agent/markdownActionHandler.ts
- ts/packages/agents/montage/src/agent/montageActionHandler.ts
- ts/packages/dispatcher/src/context/appAgentManager.ts
Agent has a reasonable expectation that if action is enabled with `updateAgentContext`, that it will get a call for disable on close as well.
Fix montage initialization exception if there are no image index.
> Update agent context with disable on close
