microsoft/TypeAgent

ts/packages/agentSdk/src/agentInterface.ts, ts/packages/dispatcher/src/action/actionHandlers.ts, ts/packages/dispatcher/src/action/system/configActionHandler.ts, ts/packages/dispatcher/src/action/system/sessionActionHandler.ts, ts/packages/dispatcher/src/agent/agentConfig.ts, ts/packages/dispatcher/src/agent/agentProcess.ts, ts/packages/dispatcher/src/agent/agentProcessShim.ts, ts/packages/dispatcher/src/agent/agentProcessTypes.ts, ts/packages/dispatcher/src/agent/inlineAgentHandlers.ts, ts/packages/dispatcher/src/handlers/common/commandHandlerContext.ts
Agent shouldn't able to issue random commands, except for system (inline) ones.
=> Remove issueCommand 

ts/packages/agentSdk/src/agentInterface.ts, ts/packages/dispatcher/src/action/actionHandlers.ts, ts/packages/dispatcher/src/agent/agentProcess.ts, ts/packages/dispatcher/src/agent/agentProcessShim.ts, ts/packages/dispatcher/src/agent/agentProcessTypes.ts, ts/packages/dispatcher/src/handlers/common/interactiveIO.ts, ts/packages/shell/src/main/index.ts
It shouldn't be use in a sessionContext. Instead, use the one on requestIO.
=> remove agentIO's setActionStatus

ts/packages/aiclient/src/openai.ts
Use default endpoint detection for "" and undefined.
=> Default model

ts/packages/agentSdk/src/agentInterface.ts, ts/packages/agentSdk/src/index.ts, ts/packages/agents/player/src/agent/playerHandlers.ts, ts/packages/dispatcher/src/action/actionHandlers.ts, ts/packages/dispatcher/src/agent/agentProcess.ts, ts/packages/dispatcher/src/agent/agentProcessShim.ts, ts/packages/dispatcher/src/agent/agentProcessTypes.ts, ts/packages/dispatcher/src/handlers/common/interactiveIO.ts, ts/packages/shell/src/main/index.ts
Remove remaining usage of agentIO and switch to notify API (no more IO outside of actions from the agent)
=> Switch to notify API

ts/packages/agents/chat/src/config.json, ts/packages/aiclient/src/openai.ts
enable use of open ai endpoints/model names for lookup and embeddings cases
=> Openai env

ts/packages/dispatcher/src/action/storageImpl.ts
await so that the catch will catch the exception.
=> Add missing await when token persistence fail

ts/packages/shell/src/main/index.ts, ts/packages/shell/src/main/shellSettings.ts
Make sure settings has appropriate defaults, even when we have partial setting saved.
=> Shell setting defaults

ts/examples/siteSchemas/package.json, ts/examples/siteSchemas/src/commerce/translator.ts, ts/packages/agents/browser/src/agent/commerce/schema/userActions.json, ts/packages/agents/browser/src/agent/commerce/translator.mts, ts/packages/agents/browser/src/agent/crossword/actionHandler.mts, ts/packages/agents/browser/src/extension/contentScript.ts, ts/packages/agents/browser/src/extension/htmlReducer.ts, ts/packages/agents/browser/src/extension/serviceWorker.ts, ts/pnpm-lock.yaml
- Reduce HTML size by removing empty div, span and paragraph nodes
- Remove empty/whitespace-only nodes
=> Further reductions in HTML size

ts/packages/agentSdk/src/agentInterface.ts, ts/packages/dispatcher/src/command.ts, ts/packages/dispatcher/src/handlers/common/commandHandlerContext.ts, ts/packages/dispatcher/src/handlers/common/interactiveIO.ts, ts/packages/dispatcher/src/handlers/notifyCommandHandler.ts, ts/packages/dispatcher/src/handlers/randomCommandHandler.ts, ts/packages/dispatcher/src/handlers/requestCommandHandler.ts, ts/packages/shell/src/main/index.ts, ts/packages/shell/src/main/shellSettings.ts, ts/packages/shell/src/main/shellSettingsType.ts, ts/packages/shell/src/preload/electronTypes.ts, ts/packages/shell/src/preload/index.ts, ts/packages/shell/src/renderer/assets/styles.less, ts/packages/shell/src/renderer/src/chatView.ts, ts/packages/shell/src/renderer/src/main.ts
=> Added @notify command to show notifications

ts/packages/shell/src/main/azureSpeech.ts, ts/packages/shell/src/main/index.ts, ts/packages/shell/src/main/shellSettings.ts, ts/packages/shell/src/main/shellSettingsType.ts, ts/packages/shell/src/preload/electronTypes.ts, ts/packages/shell/src/preload/index.ts, ts/packages/shell/src/renderer/src/chatInput.ts, ts/packages/shell/src/renderer/src/chatView.ts, ts/packages/shell/src/renderer/src/main.ts, ts/packages/shell/src/renderer/src/settingsView.ts, ts/packages/shell/src/renderer/src/speech.ts, ts/packages/shell/src/renderer/src/speechToken.ts, ts/packages/shell/src/renderer/src/tabView.ts, ts/packages/shell/src/renderer/src/tts.ts
Add Azure TTS and settings to choose the provider and voice.
=> Shell: azure tts.

ts/packages/aiclient/src/openai.ts
PR #112  introduce a regression for streaming.   That is because the "content" field of the first chunk is "undefined", and so the code end up returning `<multimodel content>`.   
The non-streaming `complete` function has a laxer requirement for the response, which skips any text before the first "{" and after the last "}" thus avoiding the error (probably a hold over when LLM JSON mode doesn't exist).  The incremental JSON is more strict and bailed on trying parse, and broke streaming.
Looking at both OpenAI and Azure API reference, unlike the input, the response messages are not a complete `PromptSection`. The content for the response can only be string currently. 
The change introduce more accurate typing for the response, and revert the logic change from PR#112
=> Fix streaming

pipelines/azure-build-ts.yml
This will automatically trigger the ADO pipeline when main is updated.
=> Change trigger to run ADO pipeline when main is updated

ts/packages/agentSdk/src/memory.ts, ts/packages/agents/browser/src/agent/actionHandler.mts, ts/packages/agents/calendar/src/calendarActionHandler.ts, ts/packages/agents/chat/src/chatResponseHandler.ts, ts/packages/agents/desktop/src/actionHandler.ts, ts/packages/agents/email/src/emailActionHandler.ts, ts/packages/agents/list/src/listActionHandler.ts, ts/packages/agents/photos/src/photoActionHandler.ts, ts/packages/agents/player/src/agent/playerHandlers.ts, ts/packages/agents/player/src/client.ts, ts/packages/agents/player/src/playback.ts, ts/packages/dispatcher/src/action/actionHandlers.ts
Also fix player's searchTracks action to not restrict the search string to only match track names.
=> Rename TurnImpression to ActionResult

ts/packages/shell/src/main/agent.ts, ts/packages/shell/src/main/index.ts, ts/packages/shell/src/main/shellSettings.ts, ts/packages/shell/src/main/shellSettingsType.ts, ts/packages/shell/src/renderer/src/helpView.ts, ts/packages/shell/src/renderer/src/main.ts, ts/packages/shell/src/renderer/src/settingsView.ts, ts/packages/shell/src/renderer/src/tabView.ts
Added all menu items to @ shell command
Fixed a zoom in/out keyboard shortcut bug
Removed tabs
=> Updated @shell commands

ts/packages/dispatcher/src/handlers/historyCommandHandler.ts, ts/packages/dispatcher/src/handlers/sessionCommandHandlers.ts
Added clear history command and also clear chat history when creating new session
=> Added clear history command and also clear chat history when creating new session

ts/packages/agentSdk/src/agentInterface.ts, ts/packages/agentSdk/src/commands.ts, ts/packages/agentSdk/src/display.ts, ts/packages/agentSdk/src/memory.ts, ts/packages/agents/chat/src/chatResponseHandler.ts, ts/packages/dispatcher/src/action/actionHandlers.ts, ts/packages/dispatcher/src/agent/agentProcess.ts, ts/packages/dispatcher/src/agent/agentProcessShim.ts, ts/packages/dispatcher/src/agent/agentProcessTypes.ts, ts/packages/dispatcher/src/agent/inlineAgentHandlers.ts, ts/packages/dispatcher/src/command.ts, ts/packages/dispatcher/src/handlers/configCommandHandlers.ts, ts/packages/dispatcher/src/handlers/constructionCommandHandlers.ts, ts/packages/dispatcher/src/handlers/displayCommandHandler.ts, ts/packages/dispatcher/src/handlers/sessionCommandHandlers.ts, ts/packages/dispatcher/src/utils/args.ts, ts/packages/shell/src/renderer/src/chatView.ts, ts/packages/shell/src/renderer/src/tts.ts
- Add flags for display to explicit state whether it can be spoken or not.
- Add ability to cancel TTS (when a new request comes in).
- Prevent multiple TTS to overlap.
Other changes
- Fix resolve command when the command doesn't exist and give better error messages.
=> TTS improvements

ts/packages/agentSdk/package.json
- Add "types": "./dist/index.d.ts",
=> Update @typeagent/agent-sdk package.json

ts/examples/whisperClient/src/tsconfig.json, ts/packages/agentSdk/src/tsconfig.json, ts/packages/agents/calendar/src/calendarActionHandler.ts, ts/packages/agents/calendar/src/tsconfig.json, ts/packages/agents/code/src/tsconfig.json, ts/packages/agents/email/src/tsconfig.json, ts/packages/agents/list/src/tsconfig.json, ts/packages/agents/photos/src/tsconfig.json, ts/packages/cacheExplorer/src/route/tsconfig.json, ts/packages/cacheExplorer/src/site/tsconfig.json, ts/packages/cli/tsconfig.json, ts/packages/codeProcessor/src/code.ts, ts/packages/codeProcessor/src/tsconfig.json, ts/packages/dispatcher/src/handlers/common/interactiveIO.ts
Clean that up as much as possible.
=> Reenable noUnusedLocals

ts/packages/agentSdk/src/action.ts, ts/packages/agentSdk/src/agentInterface.ts, ts/packages/agentSdk/src/helpers/actionHelpers.ts, ts/packages/agentSdk/src/index.ts, ts/packages/agentSdk/src/memory.ts
- Separate Action related interface in a separate file.
- Delete unused `relationship` from sdk.
=> Reorganize sdk interface definition 

ts/.vscode/launch.json, ts/examples/chat/src/codeChat/codeChat.ts, ts/examples/chat/src/main.ts, ts/packages/codeProcessor/src/codeIndex.ts, ts/packages/codeProcessor/src/codeReviewer.ts, ts/packages/interactiveApp/src/interactiveApp.ts
* Code Index now stores code & source path
* Namespace qualify code block "names"
* Improved example app. Better printing, help etc. 
* Bug fixes
=> Updates to Code Processor, Code Chat examples

ts/packages/shell/src/renderer/assets/styles.less, ts/packages/shell/src/renderer/src/chatView.ts, ts/packages/shell/src/renderer/src/tts.ts
Measure delay experienced by the user by tracking first response to a request, from the time it is submitted, to the first message (or audio speaking).
Also fix TTS timing (hide it under devUI), and clean up the metrics layout.
=> Measure first response

ts/packages/dispatcher/src/utils/metrics.ts, ts/packages/shell/src/renderer/assets/styles.less, ts/packages/shell/src/renderer/src/chatInput.ts, ts/packages/shell/src/renderer/src/chatView.ts
- The "parse" time should include the request translation if it measurement exists.
- set cursor to end on input when navigating with history using up/down keys
=> Shell: Include LLM translation time in `parse`

ts/packages/dispatcher/src/agent/inlineAgentHandlers.ts, ts/packages/dispatcher/src/utils/metrics.ts, ts/packages/shell/src/renderer/src/chatView.ts
Make sure total time is shown at the last message (even if there are no action)
=> Shell: show total time for non-action.

ts/packages/commonUtils/src/types.ts, ts/packages/dispatcher/src/agent/inlineAgentHandlers.ts, ts/packages/dispatcher/src/handlers/common/appAgentManager.ts, ts/packages/dispatcher/src/handlers/common/commandHandlerContext.ts, ts/packages/dispatcher/src/handlers/sessionCommandHandlers.ts, ts/packages/dispatcher/src/session/options.ts, ts/packages/dispatcher/src/session/session.ts
Fix the problem where the `@session reset` command doesn't reset the agent enable/disable overrides.
=> Fix `@session reset`

ts/packages/shell/src/renderer/src/chatView.ts
Including block, inline prefix and inline flush.
=> Shell: make sure TTS metrics are reported on all code paths

ts/.vscode/launch.json, ts/examples/chat/src/codeChat/codeChat.ts, ts/examples/chat/src/codeChat/codeMemory.ts, ts/examples/chat/src/codeChat/codePrinter.ts, ts/examples/chat/src/codeChat/common.ts, ts/examples/chat/src/main.ts, ts/packages/codeProcessor/README.md, ts/packages/codeProcessor/package.json, ts/packages/codeProcessor/src/code.ts, ts/packages/codeProcessor/src/codeIndex.ts, ts/packages/codeProcessor/src/developerMemory.ts, ts/packages/codeProcessor/src/index.ts, ts/packages/interactiveApp/src/interactiveApp.ts, ts/packages/knowledgeProcessor/README.md, ts/packages/knowledgeProcessor/src/knowledgeIndex.ts, ts/pnpm-lock.yaml
Continuing exploration of applying Structured RAG & TypeChat to developer tools.
=> Developer tooling + Structured RAG

ts/packages/dispatcher/src/handlers/common/chatHistoryPrompt.ts, ts/packages/shell/src/main/shellSettingsType.ts
Added timestamp to chatprompt.  
Enabled multi-modal content by default.
=> Added time to chatprompt & turned on multi modal content by default

ts/packages/dispatcher/src/command.ts, ts/packages/dispatcher/src/dispatcher/dispatcher.ts, ts/packages/dispatcher/src/handlers/common/interactiveIO.ts, ts/packages/dispatcher/src/index.ts, ts/packages/shell/src/main/index.ts, ts/packages/shell/src/main/shellSettings.ts, ts/packages/shell/src/main/shellSettingsType.ts, ts/packages/shell/src/preload/electronTypes.ts, ts/packages/shell/src/preload/index.ts, ts/packages/shell/src/renderer/src/chatInput.ts, ts/packages/shell/src/renderer/src/chatView.ts, ts/packages/shell/src/renderer/src/main.ts, ts/packages/shell/src/renderer/src/partial.ts, ts/packages/shell/src/renderer/src/search.ts, ts/packages/shell/src/renderer/src/settingsView.ts
- Only allow completion at the end of the input
- Only provide completion for `@` commands for now.
=> Initial Partial Completion (a.k.a. Intellisense) capability

ts/.vscode/launch.json, ts/.vscode/settings.json, ts/examples/chat/src/memory/chatMemory.ts, ts/packages/dispatcher/src/handlers/requestCommandHandler.ts, ts/packages/knowledgeProcessor/package.json, ts/packages/knowledgeProcessor/src/cluster.ts, ts/packages/knowledgeProcessor/src/conversation/conversation.ts, ts/packages/knowledgeProcessor/src/conversation/conversationManager.ts, ts/packages/knowledgeProcessor/src/diagnostics.ts, ts/packages/knowledgeProcessor/src/knowledgeIndex.ts, ts/packages/knowledgeProcessor/test/conversation.spec.ts, ts/packages/knowledgeProcessor/test/store.spec.ts, ts/packages/typeagent/package.json, ts/packages/typeagent/src/lib/queue.ts, ts/packages/typeagent/src/objStream.ts, ts/packages/typeagent/src/storage/objectFolder.ts, ts/pnpm-lock.yaml
* Conversation Manager: added update queue for background updates to conversation
* Fixed concurrency issue how Shell added conversation memory
* Storage bugs
* Bug in id generation 
* Error logging
* Unit tests
=> (a) Update queue for conversation manager (b) bug fixes

ts/packages/agents/chat/src/chatResponseHandler.ts, ts/packages/commonUtils/src/image.ts, ts/packages/typeagent/src/textProcessing.ts
Added additional logging to chatresponse.
=> Added additional logging to chatresponse

ts/packages/commonUtils/src/index.ts, ts/packages/commonUtils/src/mimeTypes.ts, ts/packages/shell/src/renderer/src/chatInput.ts
=> Addressing issues identified by github bots

ts/packages/shell/src/renderer/assets/styles.less, ts/packages/shell/src/renderer/src/chatView.ts
Make sure there is enough padding for the last chat message to show perf result.
=> Shell layout

pipelines/azure-build-ts.yml
=> Fix the build pipeline for @typeagent/agent-sdk

ts/.vscode/launch.json, ts/examples/chat/src/codeChat/codeChat.ts, ts/examples/chat/src/codeChat/codeMemory.ts, ts/examples/chat/src/codeChat/common.ts, ts/packages/codeProcessor/src/code.ts, ts/packages/codeProcessor/src/codeGenSchema.ts, ts/packages/codeProcessor/src/codeGenerator.ts, ts/packages/codeProcessor/src/codeReviewer.ts, ts/packages/codeProcessor/src/index.ts, ts/packages/typeagent/src/chat.ts
First cut of Code Generation in codeProcessor + code memory.
=> Code generation

ts/packages/agentSdk/src/command.ts, ts/packages/agentSdk/src/helpers/commandHelpers.ts, ts/packages/agentSdk/src/helpers/parameterHelpers.ts, ts/packages/agentSdk/test/args.spec.ts, ts/packages/agentSdk/test/flags.spec.ts, ts/packages/dispatcher/src/handlers/configCommandHandlers.ts, ts/packages/dispatcher/src/handlers/constructionCommandHandlers.ts, ts/packages/dispatcher/src/handlers/displayCommandHandler.ts, ts/packages/dispatcher/src/handlers/historyCommandHandler.ts
Declarative argument definition and parsing.
=> Argument parsing

ts/packages/agentSdk/src/command.ts, ts/packages/dispatcher/src/handlers/common/commandHandler.ts, ts/packages/dispatcher/src/handlers/constructionCommandHandlers.ts, ts/packages/dispatcher/src/handlers/sessionCommandHandlers.ts, ts/packages/shell/src/main/agent.ts
Parameter parser provide more robost parameter checking.
=> Convert more command to use the parameter parser instead of custom parsing.

ts/packages/agentSdk/src/command.ts, ts/packages/agentSdk/src/helpers/commandHelpers.ts, ts/packages/agentSdk/src/helpers/parameterHelpers.ts, ts/packages/agentSdk/test/flags.spec.ts, ts/packages/dispatcher/src/agent/inlineAgentHandlers.ts, ts/packages/dispatcher/src/command.ts, ts/packages/dispatcher/src/handlers/configCommandHandlers.ts, ts/packages/dispatcher/src/handlers/constructionCommandHandlers.ts, ts/packages/dispatcher/src/handlers/displayCommandHandler.ts, ts/packages/dispatcher/src/handlers/sessionCommandHandlers.ts
- Remove short form for flags declaration.
- Force description to be provided.
=> Print command usage with @help

ts/packages/agentSdk/src/command.ts, ts/packages/agentSdk/src/helpers/parameterHelpers.ts, ts/packages/agentSdk/test/args.spec.ts, ts/packages/dispatcher/src/agent/inlineAgentHandlers.ts, ts/packages/dispatcher/src/handlers/correctCommandHandler.ts, ts/packages/dispatcher/src/handlers/explainCommandHandler.ts, ts/packages/dispatcher/src/handlers/requestCommandHandler.ts, ts/packages/dispatcher/src/handlers/translateCommandHandler.ts
Allow an argument to consume the rest of the parameter input without quotes.
=> Implicit quote arguments

ts/packages/dispatcher/src/handlers/common/appAgentManager.ts, ts/packages/dispatcher/src/handlers/configCommandHandlers.ts, ts/packages/dispatcher/src/session/options.ts
- Change the agent toggles to use parameter declaration and parsing
- Enable toggling of commands.
=> Parameter declaration and parsing for agent toggles

ts/packages/agentSdk/src/parameters.ts, ts/packages/dispatcher/src/dispatcher/command.ts, ts/packages/dispatcher/src/dispatcher/commandHelp.ts, ts/packages/dispatcher/src/dispatcher/parameters.ts
For non-multiple flags, don't show it in thepartial complete choice if it is already used.
=> Filter flag choices in partial complete if it already used.

ts/packages/agents/greeting/src/greetingActionSchema.ts
This causes a failure in validation because of the multiple UknownActions in schema.
@steveluc and @robgruen, jfyi.
=> Remove interface for UnknownAction from injected agents like greeting agent

ts/packages/shell/src/renderer/assets/styles.less, ts/packages/shell/src/renderer/src/chatInput.ts, ts/packages/shell/src/renderer/src/chatView.ts, ts/packages/shell/src/renderer/src/choicePanel.ts
Bring it back into a usable state.
=> Shell: Restore the askYesNo UI

ts/packages/agentSdk/src/display.ts, ts/packages/agentSdk/src/helpers/actionHelpers.ts, ts/packages/agents/image/src/imageActionHandler.ts, ts/packages/shell/src/main/shellSettings.ts, ts/packages/shell/src/main/shellSettingsType.ts, ts/packages/shell/src/preload/electronTypes.ts, ts/packages/shell/src/renderer/assets/carousel.less, ts/packages/shell/src/renderer/src/chatInput.ts, ts/packages/shell/src/renderer/src/chatView.ts, ts/packages/shell/src/renderer/src/main.ts, ts/packages/shell/src/renderer/src/messageContainer.ts, ts/packages/shell/src/renderer/src/messageGroup.ts, ts/packages/shell/src/renderer/src/setContent.ts, ts/packages/shell/src/renderer/src/settingsView.ts
=> Agents that supply script with their HTML content are now rendered in sandboxed Iframes

ts/packages/cache/src/explanation/requestAction.ts, ts/packages/commonUtils/src/command.ts, ts/packages/dispatcher/src/handlers/requestCommandHandler.ts, ts/packages/shell/src/preload/electronTypes.ts, ts/packages/shell/src/renderer/assets/styles.less, ts/packages/shell/src/renderer/src/chatView.ts, ts/packages/shell/src/renderer/src/fieldEditor.ts, ts/packages/shell/src/renderer/src/messageContainer.ts
- Click to edit field instead of pen button.
- overlay edit and editing button.
- Use a different character for delete
=> Shell confirm/replace flow UI improvement

ts/packages/shell/src/renderer/assets/styles.less, ts/packages/shell/src/renderer/src/templateEditor.ts
Also fix cancel replacement with overwritten action template because of translator/action name change.
=> Shell confirm/replace flow: Reorder array

ts/examples/chat/src/memory/chatMemory.ts, ts/packages/aiclient/src/openai.ts, ts/packages/knowledgeProcessor/src/conversation/answerGenerator.ts, ts/packages/typeagent/src/schema.ts
* Optional env AZURE_OPENAI_MAX_CHARS variable
* When supplied, requests whose total prompt length exceeds this will be rejected.
=> Open AI client: (optional) throttle of excessively long prompts

ts/examples/chat/src/memory/chatMemory.ts, ts/examples/chat/src/memory/common.ts, ts/packages/aiclient/src/openai.ts, ts/packages/knowledgeProcessor/src/conversation/conversationManager.ts, ts/packages/knowledgeProcessor/src/email/email.ts, ts/packages/knowledgeProcessor/src/textChunker.ts, ts/packages/typeagent/test/objectPage.spec.ts
* Break large emails into chunk
* OAI client: Log large prompt requests
=> Email Import: Chunking of emails

ts/packages/agentSdk/src/agentInterface.ts, ts/packages/agents/player/src/agent/playerHandlers.ts, ts/packages/api/src/webSocketServer.ts, ts/packages/dispatcher/src/action/actionHandlers.ts, ts/packages/dispatcher/src/agent/agentProcess.ts, ts/packages/dispatcher/src/agent/agentProcessShim.ts, ts/packages/dispatcher/src/agent/agentProcessTypes.ts, ts/packages/dispatcher/src/agent/inlineAgentHandlers.ts, ts/packages/dispatcher/src/dispatcher/command.ts, ts/packages/dispatcher/src/dispatcher/dispatcher.ts, ts/packages/dispatcher/src/index.ts, ts/packages/dispatcher/src/translation/actionTemplate.ts, ts/packages/shell/src/main/index.ts, ts/packages/shell/src/preload/electronTypes.ts, ts/packages/shell/src/preload/index.ts, ts/packages/shell/src/renderer/src/partial.ts, ts/packages/shell/src/renderer/src/templateEditor.ts, ts/packages/shell/src/renderer/src/webSocketAPI.ts
- Add API to get parameter completion for actions.
- Wire out the template editor UI ask for the data for the search menu.
=> Shell confirm/replace flow: parameter completion

ts/examples/chat/src/codeChat/codeMemory.ts, ts/examples/chat/watchdata.py
Add `cd` and `cwd` commands to codeMemory.ts.
Add a Python tool for watching /data/code in a separate terminal window.
=> Updates for chat example

ts/examples/chat/src/codeChat/codeChat.ts, ts/examples/chat/src/codeChat/codeMemory.ts, ts/examples/chat/src/memory/chatMemory.ts, ts/examples/chat/src/tests/test.ts, ts/examples/playground/src/main.ts, ts/examples/schemaStudio/src/studio.ts, ts/packages/agents/browser/src/agent/commerce/translator.mts, ts/packages/agents/browser/src/agent/crossword/translator.mts, ts/packages/agents/chat/src/chatResponseHandler.ts, ts/packages/agents/email/src/emailActionHandler.ts, ts/packages/agents/greeting/src/greetingActionHandler.ts, ts/packages/aiclient/src/index.ts, ts/packages/aiclient/src/openai.ts, ts/packages/aiclient/src/tokenCounter.ts, ts/packages/api/src/webServer.ts, ts/packages/cache/src/explanation/v5/explanationV5.ts, ts/packages/cli/src/commands/interactive.ts, ts/packages/cli/src/commands/prompt.ts, ts/packages/codeProcessor/src/codeGenerator.ts, ts/packages/codeProcessor/src/codeReviewer.ts, ts/packages/commonUtils/src/jsonTranslator.ts, ts/packages/dispatcher/data/config.json, ts/packages/dispatcher/src/agent/inlineAgentHandlers.ts, ts/packages/dispatcher/src/handlers/randomCommandHandler.ts, ts/packages/dispatcher/src/handlers/tokenCommandHandler.ts, ts/packages/dispatcher/src/session/session.ts, ts/packages/dispatcher/src/utils/interactive.ts, ts/packages/knowledgeProcessor/src/conversation/conversationManager.ts, ts/packages/knowledgeProcessor/test/testCore.ts, ts/packages/shell/src/main/index.ts
=> Added @token summary/details command to get LLM usage stats.

ts/packages/agents/player/README.md
Added clarification statement to the documentation.
=> Added clarification statement to the documentation.

ts/examples/chat/src/memory/chatMemory.ts, ts/packages/knowledgeProcessor/src/conversation/answerGenerator.ts, ts/packages/knowledgeProcessor/src/conversation/conversation.ts, ts/packages/knowledgeProcessor/src/conversation/entities.ts, ts/packages/knowledgeProcessor/src/conversation/searchProcessor.ts, ts/packages/knowledgeProcessor/src/conversation/topics.ts, ts/packages/knowledgeProcessor/src/email/email.ts, ts/packages/knowledgeProcessor/src/knowledgeIndex.ts, ts/packages/knowledgeProcessor/src/setOperations.ts, ts/packages/knowledgeProcessor/src/text.ts, ts/packages/knowledgeProcessor/test/conversation.spec.ts, ts/packages/knowledgeProcessor/test/knowlege.spec.ts, ts/packages/knowledgeProcessor/test/searchProcessor.spec.ts, ts/packages/knowledgeProcessor/test/testCore.ts, ts/packages/typeagent/src/lib/array.ts
* Bug fixes
* Better index specificity for emails
* Topic search
* Ranker improvements
* Refactoring 
* Setting up more unit tests
=> Email processing & search improvements

ts/examples/chat/src/codeChat/codeChat.ts, ts/examples/chat/src/codeChat/codeMemory.ts, ts/examples/chat/src/memory/chatMemory.ts, ts/examples/schemaStudio/src/studio.ts, ts/packages/codeProcessor/src/codeGenerator.ts, ts/packages/codeProcessor/src/codeReviewer.ts
Changes to aiclient introduced issues in dependent apps.
=> Fix issues introduced by changes to aiclient

ts/packages/agents/player/src/agent/playerHandlers.ts, ts/packages/agents/player/src/agent/playerSchema.json, ts/packages/agents/player/src/agent/playerSchema.ts, ts/packages/agents/player/src/client.ts, ts/packages/agents/player/src/endpoints.ts, ts/packages/dispatcher/data/explainer/v5/constructions.json, ts/packages/dispatcher/data/explainer/v5/data/player/basic.json, ts/packages/dispatcher/test/data/calendar/v5/complex.json, ts/packages/dispatcher/test/data/calendar/v5/simple.json, ts/packages/dispatcher/test/data/player/v5/changeVolume.json, ts/packages/dispatcher/test/data/player/v5/full.json, ts/packages/dispatcher/test/data/player/v5/nextAction.json, ts/packages/dispatcher/test/data/player/v5/param.json, ts/packages/dispatcher/test/data/player/v5/pauseAction.json, ts/packages/dispatcher/test/data/player/v5/previousAction.json, ts/packages/dispatcher/test/data/player/v5/resumeAction.json, ts/packages/dispatcher/test/data/player/v5/searchTracks.json, ts/packages/dispatcher/test/data/player/v5/simple.json
=> Player schema update

ts/examples/chat/src/codeChat/codeChat.ts, ts/examples/chat/src/codeChat/codeMemory.ts, ts/examples/chat/src/memory/chatMemory.ts, ts/examples/chat/src/tests/test.ts, ts/examples/playground/src/main.ts, ts/examples/schemaStudio/src/studio.ts, ts/packages/agents/browser/src/agent/commerce/translator.mts, ts/packages/agents/browser/src/agent/crossword/translator.mts, ts/packages/agents/chat/src/chatResponseHandler.ts, ts/packages/agents/email/src/emailActionHandler.ts, ts/packages/agents/greeting/src/greetingActionHandler.ts, ts/packages/aiclient/src/openai.ts, ts/packages/cache/src/explanation/v5/explanationV5.ts, ts/packages/cli/src/commands/prompt.ts, ts/packages/codeProcessor/src/codeGenerator.ts, ts/packages/codeProcessor/src/codeReviewer.ts, ts/packages/commonUtils/src/jsonTranslator.ts, ts/packages/dispatcher/src/handlers/randomCommandHandler.ts, ts/packages/knowledgeProcessor/src/conversation/conversationManager.ts, ts/packages/knowledgeProcessor/test/testCore.ts
Tag paramter is now optional and the final parameter
=> Updated model api when supplying tags

ts/packages/agents/player/src/agent/playerHandlers.ts, ts/packages/agents/player/src/client.ts, ts/packages/agents/player/src/search.ts
Also fix the following:
- make sure play random honor the quantity count.
- play album with track name only plays that track instead of the album.
=> Music Player: Stricter wildcard validation.

ts/packages/agents/player/src/client.ts, ts/packages/cache/src/cache/factory.ts, ts/packages/cache/src/explanation/v5/explanationV5.ts, ts/packages/dispatcher/src/dispatcher/dispatcherAgent.ts, ts/packages/dispatcher/src/handlers/requestCommandHandler.ts
The field of unknown has change, but because of not using the right type, the code hasn't change.
Also:
- fix some of the error message for player.
- Reuse the default explainer instead of creating one per translator.
=> Fix unknown action

ts/examples/chat/package.json, ts/examples/chat/src/memory/chatMemory.ts, ts/examples/memoryProviders/src/sqlite/common.ts, ts/examples/memoryProviders/src/sqlite/index.ts, ts/examples/memoryProviders/src/sqlite/keyValueTable.ts, ts/examples/memoryProviders/src/sqlite/temporalTable.ts, ts/examples/memoryProviders/src/sqlite/textTable.ts, ts/examples/memoryProviders/test/sqlite.temporalTable.spec.ts, ts/examples/memoryProviders/test/sqlite.textTable.spec.ts, ts/examples/memoryProviders/test/testCore.ts, ts/packages/knowledgeProcessor/src/temporal.ts, ts/pnpm-lock.yaml
* Temporal Log over Sqlite
* Bug fixes
=> Memory Provider Temporal Log using Sqlite

ts/packages/typeagent/src/storage/objectFolder.ts
Simplified to make it easier to implement on other backend stores. 
- Removed sub-folder support which creates unnecessary complexity
=> Simplified ObjectFolder interface

ts/packages/agentSdk/src/action.ts, ts/packages/cache/src/explanation/requestAction.ts, ts/packages/cli/src/commands/data/regenerate.ts, ts/packages/dispatcher/src/action/actionHandlers.ts, ts/packages/dispatcher/src/dispatcher/dispatcherActionSchema.ts, ts/packages/dispatcher/src/dispatcher/dispatcherAgent.ts, ts/packages/dispatcher/src/handlers/common/chatHistory.ts, ts/packages/dispatcher/src/handlers/common/chatHistoryPrompt.ts, ts/packages/dispatcher/src/handlers/requestCommandHandler.ts, ts/packages/dispatcher/src/session/session.ts
Also use this as an indication that the next user request probably isn't cachable.
=> Improve clarify response by injecting additional instructions

ts/packages/dispatcher/src/handlers/common/chatHistory.ts, ts/packages/dispatcher/src/handlers/requestCommandHandler.ts
Should check for empty array as well.
=> Fix detection of additional instruction

ts/examples/chat/src/chalkWriter.ts, ts/examples/chat/src/chatPrinter.ts, ts/examples/chat/src/memory/chatMemory.ts, ts/examples/chat/src/memory/chatMemoryPrinter.ts, ts/examples/chat/src/memory/common.ts, ts/examples/chat/src/memory/emailMemory.ts, ts/packages/interactiveApp/src/InteractiveIo.ts, ts/packages/interactiveApp/src/core.ts, ts/packages/interactiveApp/src/interactiveApp.ts, ts/packages/knowledgeProcessor/src/conversation/conversation.ts, ts/packages/typeagent/src/index.ts, ts/packages/typeagent/src/objStream.ts, ts/packages/typeagent/src/storage/workQueue.ts, ts/packages/typeagent/test/storage.workQueue.spec.ts
Support indexing large number of email files reliably:
* Work queue  object
* Persistent email indexing queue; automatic replay of failed files.
* Incremental updates through queue
* Refactored email indexing command
* Evaluated with all embedding models + scores
=> Email Indexing Improvements

ts/examples/memoryProviders/src/sqlite/textTable.ts, ts/packages/knowledgeProcessor/src/conversation/topics.ts, ts/packages/knowledgeProcessor/src/knowledgeIndex.ts
=> Indexing Bug

ts/examples/spelunker/package.json, ts/examples/spelunker/src/chunkDocSchema.ts, ts/examples/spelunker/src/chunkyIndex.ts, ts/examples/spelunker/src/codeDocSchema.ts, ts/examples/spelunker/src/fileDocumenter.ts, ts/examples/spelunker/src/main.ts, ts/examples/spelunker/src/pythonChunker.ts, ts/examples/spelunker/src/pythonImporter.ts, ts/examples/spelunker/src/queryInterface.ts, ts/pnpm-lock.yaml
This is only a halfway point on the journey; querying is currently a mess:
It just looks up the query as a key in each of the tables and reports any hits it gets.
No stemming, no trying sub-sequences, it is even case-sensitive, etc.
We may also need to clarify to the model what each of these means.
=> [spelunker] Ask the model for keywords, topics, goals and dependencies

ts/examples/spelunker/src/chunkyIndex.ts, ts/examples/spelunker/src/pythonImporter.ts, ts/examples/spelunker/src/queryInterface.ts
=> Use TextIndex with semanticIndex:true instead of KeyValueIndex for keywords etc.

ts/examples/spelunker/src/chunkyIndex.ts, ts/examples/spelunker/src/queryInterface.ts
- Add default (non-`@`) search
- Fix queries in keyword (etc.) indexes -- don't call `sanitizeKey()`
- Add `@keywords`, `@topics`, `@goals`, `@dependencies`
- Use embedding cache
=> [spelunker] More index fun

dotnet/email/App.cs, dotnet/email/COMObject.cs, dotnet/email/Core/ConsoleEx.cs, dotnet/email/Core/FileEx.cs, dotnet/email/Email.cs, dotnet/email/EmailExporter.cs, dotnet/email/Includes.cs, dotnet/email/MailStats.cs, dotnet/email/MailtemEx.cs, dotnet/email/Outlook.cs, dotnet/email/outlookEmail.csproj
Improvements to Dotnet Outlook Interop app
* Calculate distribution of email sizes in mailbox
* Export Outlook messages bucketed by size
* Hooked up System.CommandLine to support proper commands etc.
=> Email Size Distribution in Outlook etc. (.NET)

ts/packages/cache/src/utils/language.ts, ts/packages/cache/test/reference.spec.ts, ts/packages/cli/src/commands/run/explain.ts, ts/packages/cli/src/commands/run/request.ts, ts/packages/cli/src/commands/run/translate.ts, ts/packages/dispatcher/src/handlers/common/commandHandlerContext.ts, ts/packages/dispatcher/src/handlers/constructionCommandHandlers.ts, ts/packages/dispatcher/src/handlers/requestCommandHandler.ts, ts/packages/dispatcher/src/session/options.ts, ts/packages/dispatcher/src/session/session.ts
`@const builtin on` or `@const builtin off`
Also reorganize the cache settings.
=> Add toggle for builtin cache.

ts/examples/spelunker/src/chunkyIndex.ts, ts/examples/spelunker/src/pythonChunker.ts, ts/examples/spelunker/src/pythonImporter.ts, ts/examples/spelunker/src/queryInterface.ts
Also rename IdType to ChunkId and use it everywhere it occurs.
=> [spelunker] Use a hit table to sort query results

ts/packages/agents/player/src/agent/playerSchema.json, ts/packages/cache/src/constructions/constructionCache.ts, ts/packages/cache/src/constructions/constructionMatch.ts, ts/packages/cache/src/constructions/constructionPrint.ts, ts/packages/cache/src/constructions/constructionValue.ts, ts/packages/cache/src/constructions/constructions.ts, ts/packages/cache/src/constructions/matchPart.ts, ts/packages/cache/src/constructions/parsePart.ts, ts/packages/cache/src/explanation/schemaConfig.ts, ts/packages/cache/src/explanation/v5/explanationV5.ts, ts/packages/cacheExplorer/src/site/index.ts
Allow references in checked wildcard, as the agent would be able to determine they valid or not.
=> Relax checked wildcard

ts/packages/typeagent/src/index.ts, ts/packages/typeagent/src/vector/semanticList.ts, ts/packages/typeagent/src/vector/semanticMap.ts
Adding Semantic Map and List back to TypeAgent
=> Semantic Map, List

ts/packages/knowledgeProcessor/src/conversation/index.ts, ts/packages/knowledgeProcessor/src/conversation/knowledgeResponseLoss.ts, ts/packages/knowledgeProcessor/src/index.ts
add a loss function for KnowledgeResponse
=> Add kr loss

ts/.vscode/launch.json
=> Fix launch.json

ts/examples/spelunker/src/fileDocSchema.ts, ts/examples/spelunker/src/fileDocumenter.ts, ts/examples/spelunker/src/pythonChunker.ts, ts/examples/spelunker/src/pythonImporter.ts, ts/examples/spelunker/src/queryInterface.ts
(This should have been in the previous PR.)
=> [spelunker] Rename codeDocSchema to fileDocSchema, rename interfaces and fields

ts/packages/cache/src/explanation/v5/explanationV5.ts, ts/packages/cli/src/commands/run/request.ts, ts/packages/cli/src/commands/run/translate.ts
Also close `dispatcher` in the CLI.
=> Fix exception on exception printing

ts/packages/actionSchema/src/creator.ts, ts/packages/actionSchema/src/generator.ts, ts/packages/actionSchema/src/index.ts, ts/packages/actionSchema/src/parser.ts, ts/packages/actionSchema/src/type.ts, ts/packages/actionSchema/src/utils.ts, ts/packages/actionSchema/src/validate.ts, ts/packages/actionSchema/test/validate.spec.ts, ts/packages/dispatcher/src/translation/actionTemplate.ts, ts/packages/dispatcher/src/translation/unknownSwitcher.ts
Also simplify the internal type name in `action-schema` that are not really "Action" specific.
=> Schema validation testing

ts/pnpm-lock.yaml
Update version dependences in the lock file for the following packages.
- cross-spawn
- http-proxy-middleware
- micromatch
- elliptic
=> lockfile: update package dependency

ts/examples/spelunker/src/chunker.py, ts/examples/spelunker/src/main.ts, ts/examples/spelunker/src/pythonChunker.ts, ts/examples/spelunker/src/pythonImporter.ts, ts/examples/spelunker/src/queryInterface.ts
Also:
- Use camelCase for the Chunk.fileName field
- Populate Chunk.fileName so that the model can see it
(this used to be the case but got lost; because the field was optional it wasn't flagged)
- Use io.writer.writeLine() instead of console.log() everywhere possible
=> [spelunker] Break large files into pieces

ts/packages/api/src/typeAgentServer.ts, ts/packages/cli/src/commands/run/explain.ts, ts/packages/cli/src/commands/run/translate.ts, ts/packages/dispatcher/src/agent/agentConfig.ts, ts/packages/dispatcher/src/agent/agentProcessShim.ts, ts/packages/dispatcher/src/agent/agentProvider.ts, ts/packages/dispatcher/src/handlers/common/appAgentManager.ts, ts/packages/dispatcher/src/session/session.ts, ts/packages/shell/src/main/agent.ts
Kill the agent processes once all the referencing dispatchers are closed.
=> Ref count agent process

ts/packages/actionSchema/src/parser.ts, ts/packages/dispatcher/src/action/actionHandlers.ts, ts/packages/dispatcher/src/agent/inlineAgentHandlers.ts, ts/packages/dispatcher/src/dispatcher/command.ts, ts/packages/dispatcher/src/handlers/common/appAgentManager.ts, ts/packages/dispatcher/src/handlers/common/commandHandlerContext.ts, ts/packages/dispatcher/src/handlers/requestCommandHandler.ts, ts/packages/dispatcher/src/translation/actionSchema.ts, ts/packages/dispatcher/src/translation/actionSchemaJsonTranslator.ts, ts/packages/dispatcher/src/translation/actionTemplate.ts, ts/packages/dispatcher/src/translation/agentTranslators.ts, ts/packages/dispatcher/src/translation/unknownSwitcher.ts, ts/packages/dispatcher/src/utils/loadSchemaConfig.ts
Make the `ComposeActionSchema` to use the parse cache.
Also some `translator` -> `schema` or `ActionSchema` renaming.
=> Compose Action Schema use parse cache

ts/packages/dispatcher/README.md, ts/packages/dispatcher/src/handlers/common/appAgentManager.ts, ts/packages/dispatcher/src/handlers/configCommandHandlers.ts, ts/packages/dispatcher/src/session/options.ts
Also don't show command disabled if command isn't implemented for the agent.
=> Fix agent toggle reset

ts/packages/agents/player/src/agent/playerSchema.ts, ts/packages/agents/player/src/client.ts, ts/packages/agents/player/src/endpoints.ts
get album doesn't need a parameter because we can search for albums using the search action
=> Get album fix

ts/examples/spelunker/README.md, ts/examples/spelunker/design.md, ts/examples/spelunker/src/queryInterface.ts
In design.md you will find a description of the current architecture plus a lot of open questions about improvements.
=> [spelunker] Add design.md, and a few loggin tweaks

ts/examples/spelunker/design.md, ts/examples/spelunker/src/queryInterface.ts
(Sorry for leaving main broken, even if only for Spelunker.)
=> [spelunker] Fix bug due to subtle schema change

ts/examples/spelunker/design.md, ts/examples/spelunker/src/chunkyIndex.ts, ts/examples/spelunker/src/queryInterface.ts
Also log the time taken in steps 1, 2, 3.
=> [spelunker] Use gpt-3.5-turbo for step 1 (proposing queries)

ts/.vscode/launch.json, ts/examples/vscodeSchemaGen/src/genStats.ts, ts/examples/vscodeSchemaGen/src/schemaGen.ts, ts/examples/vscodeSchemaGen/src/vscodeSchemaGenApp.ts
- Ability to handle larger number of schema definitions
- Added option to generate only embeddings
- Fixed bugs encountered during processing workbench.actions
=> Perf improvements for VSCODE schema gen

android/samples/mobile/gradle/libs.versions.toml, ts/packages/shell/src/renderer/assets/styles.less
Tables no longer overflow message bubble.
=> Fixed table formtting in the shell.

ts/packages/dispatcher/src/agent/agentProcess.ts, ts/packages/dispatcher/src/dispatcher/command.ts, ts/packages/dispatcher/src/handlers/common/appAgentManager.ts, ts/packages/dispatcher/src/handlers/common/commandHandlerContext.ts, ts/packages/dispatcher/src/handlers/configCommandHandlers.ts, ts/packages/dispatcher/src/handlers/requestCommandHandler.ts, ts/packages/dispatcher/src/session/session.ts, ts/packages/dispatcher/src/translation/actionSchemaJsonTranslator.ts, ts/packages/dispatcher/src/translation/actionSchemaSemanticMap.ts, ts/packages/dispatcher/src/translation/agentTranslators.ts, ts/packages/dispatcher/src/utils/config.ts, ts/packages/dispatcher/src/utils/metrics.ts
Reduce prompt token size by only chose the top 5 likeliest action as the first chance translation using embedding.
=> Partial schema translation

ts/packages/knowledgeProcessor/src/conversation/answerContext.ts, ts/packages/knowledgeProcessor/src/conversation/answerGenerator.ts, ts/packages/knowledgeProcessor/src/conversation/index.ts, ts/packages/knowledgeProcessor/test/answerGenerator.spec.ts, ts/packages/knowledgeProcessor/test/textMatcher.spec.ts
* Text matcher unit test error
* Refactoring answer generation
=> Unit test failure + refactoring

ts/examples/chat/src/memory/chatMemory.ts, ts/examples/memoryProviders/src/sqlite/textTable.ts, ts/packages/aiclient/src/models.ts, ts/packages/interactiveApp/src/interactiveApp.ts, ts/packages/knowledgeProcessor/src/conversation/knowledgeTermSearch2.ts, ts/packages/knowledgeProcessor/src/conversation/searchProcessor.ts, ts/packages/knowledgeProcessor/src/conversation/searchResponse.ts, ts/packages/knowledgeProcessor/src/conversation/topics.ts, ts/packages/knowledgeProcessor/src/email/email.ts, ts/packages/knowledgeProcessor/src/setOperations.ts
knowledge processing bug fixes in:
- topics
- actions
- Sqlite memory provider
- Set operations
Open AI:
Added support for "seed" parameter.
=> Memory search relevance + bug fixes

ts/packages/cache/src/cache/cache.ts, ts/packages/cache/src/cache/store.ts, ts/packages/cache/src/constructions/constructionCache.ts, ts/packages/dispatcher/src/handlers/constructionCommandHandlers.ts
- Add command to prune construction from old schemas
- `@const info` count constructions that has mismatch sources hash.
=> Construction prune command

ts/packages/dispatcher/data/explainer/v5/constructions.json, ts/packages/dispatcher/data/explainer/v5/data/player/basic.json
It contains a construction that is too generalize that take any input as the artist name for `playArtist` action
=> Fix builtin construction cache

ts/packages/agentSdk/README.md, ts/packages/dispatcher/src/context/appAgentManager.ts, ts/packages/dispatcher/src/translation/actionSchemaSemanticMap.ts, ts/packages/shell/src/main/index.ts, ts/packages/shell/src/main/localWhisperCommandHandler.ts
=> Add ActionContext info to SDK README.md

ts/packages/agentSdk/src/display.ts, ts/packages/dispatcher/src/execute/actionHandlers.ts
Also add more comment for display API in the SDK.
=> Action error return from the action should be shown with the action context

ts/packages/dispatcher/src/context/dispatcher/handlers/requestCommandHandler.ts
=> prevent embedding lookup on empty request (like when the user supplies image only request)

ts/packages/agents/agentUtils/graphUtils/src/calendarClient.ts
- Better tracking of thread state
- stop the current before starting a new one.
- Wait for finish indexing before scheduling the next one.
=> Fix calendar sync thread lifecycle

python/fineTuning/chaparral/models/data.py, python/fineTuning/chaparral/train/hf_model.py, python/fineTuning/chaparral/train/hf_params.py, python/fineTuning/chaparral/util/datareader.py, python/fineTuning/eval.py, python/fineTuning/tune.py
add code to evaluate fine-tuned knowledge extraction model
=> Fine tune eval

ts/examples/spelunker/design.md
Switch from keywords, topics, goals, dependencies to keywords, tags, synonyms, dependencies.
=> [spelunker] Update index categories in design.md

ts/packages/agents/agentUtils/graphUtils/src/graphClient.ts
This happens only in a clean dev environment.
=> Fix graph login regression when tokencahe.bin is missing.

README.md, docs/setup/setup-WSL2.md, docs/setup/setup-Windows.md
Also add links to the instructions from the root README.md
=> Add windows instructions

ts/packages/agents/agentUtils/graphUtils/src/graphClient.ts
Instead use withLockFile on the directory name.
=> Remove function to create lock file when tokencache.bin is missing.

ts/examples/searchActionTest/README.md, ts/examples/searchActionTest/package.json, ts/examples/searchActionTest/run.cmd, ts/examples/searchActionTest/src/calSearchSchema.ts, ts/examples/searchActionTest/src/main.ts, ts/examples/searchActionTest/src/tsconfig.json, ts/packages/commonUtils/src/indexNode.ts, ts/packages/commonUtils/src/jsonTranslator.ts, ts/pnpm-lock.yaml
Used to run tests on search actions.
=> action test runner

ts/packages/agentRpc/package.json, ts/packages/agentRpc/src/client.ts, ts/packages/agentRpc/src/common.ts, ts/packages/agentRpc/src/rpc.ts, ts/packages/agentRpc/src/server.ts, ts/packages/agents/browser/src/agent/actionHandler.mts, ts/packages/agents/browser/src/agent/webTypeAgent.mts, ts/packages/agents/browser/src/common/webAgentMessageTypes.mts, ts/packages/agents/browser/src/extension/serviceWorker.ts, ts/packages/agents/browser/src/extension/webTypeAgentContentScript.ts, ts/packages/agents/browser/src/extension/webTypeAgentMain.ts, ts/packages/agents/turtle/src/site/index.ts, ts/packages/dispatcher/src/agentProvider/process/agentProcess.ts, ts/packages/dispatcher/src/agentProvider/process/agentProcessShim.ts
Also, `registerTypeAgent` will return a promise for the agent to finish registering, so the web page knows if it succeeded or not.
=> Webagent: better disconnect/reconnect management, allow page to reload

ts/packages/shell/package.json, ts/packages/shell/src/renderer/assets/styles.less, ts/packages/shell/src/renderer/src/chatView.ts, ts/packages/shell/src/renderer/src/main.ts, ts/packages/shell/src/renderer/src/messageContainer.ts, ts/packages/shell/src/renderer/src/messageGroup.ts, ts/pnpm-lock.yaml
Added user name and icon place holder to the UI:
=> Added user name to the user chat bubble

ts/packages/agents/browser/src/agent/actionHandler.mts, ts/packages/agents/browser/src/agent/instacart/actionHandler.mts, ts/packages/agents/browser/src/agent/instacart/planHandler.mts, ts/packages/agents/browser/src/agent/instacart/schema/pageComponents.mts
- use builder pattern to express plans
- update page component schemas
- add friendly message with confirmation of items added to cart and items not available
- fix scenario bugs around recipes
=> Instacart updates 

ts/packages/dispatcher/src/utils/defaultAppProviders.ts
=> Use `getInstanceDir` in `getDefaultAppAgentProviders`

ts/packages/dispatcher/package.json, ts/packages/dispatcher/src/rpc/client.ts, ts/packages/dispatcher/src/rpc/server.ts, ts/packages/dispatcher/src/rpc/types.ts, ts/packages/shell/package.json, ts/packages/shell/src/main/index.ts, ts/packages/shell/src/preload/electronTypes.ts, ts/packages/shell/src/preload/index.ts, ts/packages/shell/src/renderer/src/chatView.ts, ts/packages/shell/src/renderer/src/main.ts, ts/packages/shell/src/renderer/src/partial.ts, ts/packages/shell/src/renderer/src/templateEditor.ts, ts/packages/shell/src/renderer/src/webSocketAPI.ts, ts/pnpm-lock.yaml
Create RPC marshalling for dispatcher interface.
Use it between the electron UI and electron main process.
=> Convert dispatcher calls in electron to use our RPC pattern

ts/packages/agents/browser/src/agent/actionHandler.mts, ts/packages/agents/browser/src/extension/serviceWorker.ts, ts/packages/agents/code/src/codeActionHandler.ts, ts/packages/coda/src/webSocket.ts, ts/packages/coda/src/wsConnect.ts, ts/packages/commonUtils/src/webSockets.ts, ts/packages/dispatcher/src/context/system/handlers/serviceHost/service.ts, ts/packages/shell/src/main/browserIpc.ts
- Agents that use the shared websocket service now connect to an agent-specific channel. The channel will typically have the agent and its extensions/clients.
=> Add channels to the shared web socket service

ts/packages/agents/browser/src/agent/actionHandler.mts, ts/packages/agents/browser/src/agent/browserConnector.mts, ts/packages/agents/browser/src/agent/instacart/planHandler.mts, ts/packages/agents/browser/src/extension/serviceWorker.ts, ts/packages/commonUtils/src/webSockets.ts, ts/packages/dispatcher/src/context/system/handlers/serviceHost/service.ts, ts/packages/shell/src/main/browserIpc.ts, ts/packages/shell/src/main/index.ts, ts/packages/shell/src/preload/webView.ts
- Add WebSocketMessageV2 type to hold new message schema
- Update browser extension service worker
- Update preload script used for inline browser
=> Align the messages sent for browser agent to JSON RPC conventions

ts/packages/shell/src/main/index.ts
Make sure the DOM is ready, where both side of the RPC is setup, before using the dispatcher.
This fix the issue where the greeting sometime is too early, calling the chatView before it is initialized
=> Shell init order

.github/workflows/build-ts.yml
=> Reenable windows node v22 test

ts/examples/chat/src/memory/knowproMemory.ts, ts/packages/interactiveApp/src/InteractiveIo.ts, ts/packages/knowPro/src/conversationIndex.ts, ts/packages/knowPro/src/dataFormat.ts, ts/packages/knowPro/src/import.ts, ts/packages/knowPro/src/index.ts, ts/packages/knowPro/src/query.ts, ts/packages/knowPro/src/search.ts, ts/packages/knowPro/src/termIndex.ts
Fuzzy matching:
* Conversation: Embedding indexing, persistance
* Term alternatives now generated with embedding matching
* RelatedTerms Query operator/Expr
* Other tweaks
=> Knowpro: fuzzy

ts/examples/chat/src/memory/knowproMemory.ts, ts/packages/knowPro/src/conversationIndex.ts, ts/packages/knowPro/src/dataFormat.ts, ts/packages/knowPro/src/index.ts, ts/packages/knowPro/src/query.ts, ts/packages/knowPro/src/search.ts
"Where" predicate experiments
- action predicates
- entity predicates 
- where expression
=> knowPro query experiments

ts/packages/shell/src/main/index.ts, ts/packages/shell/test/testHelper.ts
Also fix the app path in the playwright tests for windows to have `file://` prefix.
=> Switch to use `WebContentsView` from deprecated `BrowserView`

ts/examples/memoryProviders/package.json, ts/packages/actionSchema/package.json, ts/packages/actionSchema/src/validate.ts, ts/packages/agents/test/src/handler.ts, ts/packages/agents/test/src/schema.ts, ts/packages/aiclient/package.json, ts/packages/api/package.json, ts/packages/cache/package.json, ts/packages/commonUtils/package.json, ts/packages/dispatcher/package.json, ts/packages/dispatcher/src/context/system/systemAgent.ts, ts/packages/dispatcher/test/provider.spec.ts, ts/packages/knowledgeProcessor/package.json, ts/packages/telemetry/package.json, ts/packages/typeagent/package.json
Also fix the test script that should call test:local in package.json
=> Fix action command handler with no parameters

ts/examples/chat/src/memory/common.ts, ts/examples/chat/src/memory/knowproMemory.ts, ts/examples/chat/src/memory/knowproPrinter.ts, ts/examples/chat/src/memory/podcastMemory.ts, ts/packages/knowPro/src/accumulators.ts, ts/packages/knowPro/src/dataFormat.ts, ts/packages/knowPro/src/import.ts, ts/packages/knowPro/src/query.ts, ts/packages/knowPro/src/search.ts, ts/packages/knowPro/src/timestampIndex.ts
Experiments:
* Timestamp index
* Scope queries using date ranges
=> knowpro: Timestamp Scope

ts/examples/chat/src/memory/chatMemoryPrinter.ts, ts/examples/chat/src/memory/knowproPrinter.ts, ts/packages/interactiveApp/src/InteractiveIo.ts, ts/packages/knowPro/src/accumulators.ts, ts/packages/knowPro/src/dataFormat.ts, ts/packages/knowPro/src/import.ts, ts/packages/knowPro/src/query.ts, ts/packages/knowPro/src/timestampIndex.ts
Continuing experiments on:
* Better match hit rates, Union on accumulators
* Scopes:
* Time Range Indexing rework
* TextRange accumulator rework
* Refactoring
=> knowpro: query improvements

ts/packages/commonUtils/src/jsonTranslator.ts, ts/packages/dispatcher/src/context/chatHistoryPrompt.ts, ts/packages/dispatcher/src/context/dispatcher/handlers/requestCommandHandler.ts, ts/packages/dispatcher/src/translation/agentTranslators.ts
Create explicit translate function to translate without context for explainable check, explicitly disable any context sensitive information in the prompt.
=> Separate debug trace between main action vs explainable check translations

ts/packages/agents/spelunker/src/typescriptChunker.ts
This way, the text of a function is not repeated in its parent chunk.
=> Remove child chunk text from parent chunks.

ts/packages/agents/spelunker/src/typescriptChunker.ts
I really need to start working on a test suite...
=> [Spelunker] Add breadcrumbs and fix recursive chunking

ts/packages/agents/spelunker/src/makeSelectorSchema.ts, ts/packages/agents/spelunker/src/searchCode.ts
Also a few minor prompt tweaks.
=> [Spelunker] Fix dramatic typo in selection prompt

pipelines/azure-build-ts.yml, ts/package.json
See: https://github.com/nodejs/corepack/issues/612
=> Fix corepack signature.

ts/packages/agents/markdown/package.json, ts/packages/agents/markdown/src/view/route/service.ts, ts/packages/agents/markdown/src/view/site/index.html, ts/pnpm-lock.yaml
Fixing https://github.com/microsoft/TypeAgent/security/code-scanning/42, https://github.com/microsoft/TypeAgent/security/code-scanning/43 and https://github.com/microsoft/TypeAgent/security/code-scanning/44
=> Fix security warning

ts/examples/chat/src/memory/knowproMemory.ts, ts/examples/chat/src/memory/knowproPrinter.ts, ts/packages/knowPro/src/collections.ts, ts/packages/knowPro/src/propertyIndex.ts, ts/packages/knowPro/src/query.ts, ts/packages/knowPro/src/relatedTermsIndex.ts, ts/packages/knowPro/src/search.ts
* Improved:
* Property and facet matching
* Scoring: consistent scoring for search terms, property terms, related terms 
* Query compilation improvements; cleaner query expressions. 
* Test app
* Code refactoring
=> knowpro improvements

ts/packages/cli/src/commands/interactive.ts, ts/packages/defaultAgentProvider/src/defaultAgentProviders.ts, ts/packages/defaultAgentProvider/src/index.ts, ts/packages/dispatcher/src/agentProvider/agentProvider.ts, ts/packages/dispatcher/src/agentProvider/npmAgentProvider.ts, ts/packages/dispatcher/src/agentProvider/process/agentProcess.ts, ts/packages/dispatcher/src/context/appAgentManager.ts, ts/packages/dispatcher/src/context/commandHandlerContext.ts, ts/packages/dispatcher/src/context/system/handlers/installCommandHandlers.ts, ts/packages/dispatcher/src/context/system/systemAgent.ts, ts/packages/dispatcher/src/execute/actionHandlers.ts, ts/packages/dispatcher/src/index.ts, ts/packages/shell/src/main/index.ts
Allow agent install based on path.
=> Install and uninstall command

ts/packages/agents/spelunker/design.md, ts/packages/agents/spelunker/package.json, ts/packages/agents/spelunker/src/chunkSchema.ts, ts/packages/agents/spelunker/src/chunker.py, ts/packages/agents/spelunker/src/searchCode.ts, ts/packages/agents/spelunker/src/spelunkerActionHandler.ts, ts/packages/agents/spelunker/src/spelunkerSchema.ts, ts/packages/agents/spelunker/src/typescriptChunker.ts, ts/packages/aiclient/src/restClient.ts, ts/pnpm-lock.yaml
This also stops turning type (alias) definitions in their own chunk -- there are too many and they are too small.
=> [Spelunker] Remove input entities; improve retry logic; better logging; and more

ts/.vscode/settings.json, ts/packages/dispatcher/src/context/chatHistoryPrompt.ts, ts/packages/dispatcher/src/translation/translateRequest.ts
- Refactor and cleanup prompt generation.
- Don't do outer assistant switching if there are no more assistant to look for.
=> Minor Refactor

ts/packages/api/src/webDispatcher.ts, ts/packages/cli/src/commands/test/translate.ts, ts/packages/defaultAgentProvider/test/translateTestCommon.ts, ts/packages/dispatcher/src/command/command.ts, ts/packages/dispatcher/src/context/appAgentManager.ts, ts/packages/dispatcher/src/context/commandHandlerContext.ts, ts/packages/dispatcher/src/context/dispatcher/dispatcherUtils.ts, ts/packages/dispatcher/src/context/dispatcher/handlers/requestCommandHandler.ts, ts/packages/dispatcher/src/context/interactiveIO.ts, ts/packages/dispatcher/src/context/session.ts, ts/packages/dispatcher/src/context/system/handlers/notifyCommandHandler.ts, ts/packages/dispatcher/src/context/system/handlers/randomCommandHandler.ts, ts/packages/dispatcher/src/dispatcher.ts, ts/packages/dispatcher/src/execute/actionHandlers.ts, ts/packages/dispatcher/src/translation/confirmTranslation.ts, ts/packages/dispatcher/src/translation/pendingRequest.ts, ts/packages/dispatcher/src/translation/translateRequest.ts
- Detect if there are any error in commands so that we can assert that in test.
- Add a flag to enable full command result collection.
- Reorganizing some code around
=> Detect command error in test

ts/packages/agents/spelunker/src/pythonChunker.ts, ts/packages/agents/spelunker/src/searchCode.ts, ts/packages/agents/spelunker/src/selectorSchema.ts
Also reword the comments in selectorSchema.ts and remove "large file splitting" from pythonChunker.ts -- it is not needed any more.
=> [Spelunker] Big refactor of searchCode() into smaller functions

ts/packages/agents/spelunker/src/searchCode.ts
I thought it had the type wrong when calling selectRelevantChunks(), but actually it got the name wrong, and it should have called selectChunks(). I also changed a log message so step 3 is announced.
=> [Spelunker] Fix bugs introduced by Copilot (and my poor review skills)

ts/examples/chat/src/memory/knowproMemory.ts, ts/packages/knowPro/src/query.ts, ts/packages/knowPro/src/search.ts
- Now can do all property matching without requiring property Index.
- Optional flag that lets us compare one vs other
=> knowpro: Make propertyIndex optional

ts/examples/chat/src/memory/knowproMemory.ts, ts/packages/knowPro/src/collections.ts, ts/packages/knowPro/src/query.ts, ts/packages/knowPro/src/search.ts, ts/packages/knowPro/src/secondaryIndexes.ts, ts/packages/knowPro/src/timestampIndex.ts
* Fixed "And" operator (matchAll). Useful for other operations
* Separate options for (a) matchAll (b) exact match for testing
* Range matching fix
* Refactored/renamed
* Removed unused code
=> knowPro bugs and improvements

ts/packages/knowPro/src/collections.ts, ts/packages/knowPro/src/dataFormat.ts, ts/packages/knowPro/src/index.ts, ts/packages/knowPro/src/query.ts, ts/packages/knowPro/src/relatedTermsIndex.ts, ts/packages/knowPro/src/search.ts, ts/packages/knowPro/src/secondaryIndexes.ts
=> knowpro: Refactoring etc. 

ts/packages/defaultAgentProvider/test/data/translate-history-e2e.json, ts/packages/defaultAgentProvider/test/translateTestCommon.ts, ts/packages/dispatcher/src/context/chatHistory.ts, ts/packages/dispatcher/src/context/chatHistoryPrompt.ts, ts/packages/dispatcher/src/context/commandHandlerContext.ts, ts/packages/dispatcher/src/context/session.ts, ts/packages/dispatcher/src/execute/actionHandlers.ts
Continue to use the string value to match entity as well for now, but don't if there are multiple of the same name.
=> Translation use entity id to refer to entities

ts/examples/chat/src/memory/knowproMemory.ts, ts/packages/knowPro/src/collections.ts, ts/packages/knowPro/src/query.ts, ts/packages/knowPro/src/search.ts
* Action scopes applies automatically in "outer" scope
* Removed special case action "scope" terms. 
* Renamed outer scope to just scope; "inner" scope not currently needed.
=> knowpro: make Action scoping automatic 

ts/packages/knowPro/src/collections.ts, ts/packages/knowPro/src/query.ts, ts/packages/knowledgeProcessor/src/conversation/actions.ts
* Intersection bug
* Text range bug
=> knowpro: bug fixes

ts/examples/chat/src/memory/knowproMemory.ts, ts/examples/chat/src/memory/knowproPrinter.ts, ts/packages/interactiveApp/src/interactiveApp.ts, ts/packages/knowPro/src/collections.ts, ts/packages/knowPro/src/conversationIndex.ts, ts/packages/knowPro/src/dataFormat.ts, ts/packages/knowPro/src/fuzzyIndex.ts, ts/packages/knowPro/src/import.ts, ts/packages/knowPro/src/relatedTermsIndex.ts, ts/packages/knowPro/src/threads.ts
* Refactoring
* Starting experiments with threads
* Bugs, CLI improvements
=> knowpro: Refactor, conversation threads

ts/packages/agents/spelunker/src/chunker.py, ts/packages/agents/spelunker/src/searchCode.ts
Also lint chunker.py, since apparently the lint rules have changed?
=> [Spelunker] Add References to the end of the main answer (if any)

ts/examples/chat/src/memory/knowproMemory.ts, ts/examples/chat/src/memory/knowproPrinter.ts, ts/examples/chat/src/memory/podcastMemory.ts, ts/packages/knowPro/src/import.ts, ts/packages/knowPro/src/query.ts, ts/packages/knowPro/src/search.ts, ts/packages/knowPro/src/secondaryIndexes.ts
* Conversation threads: experiments
* Refactoring
=> knowpro: threads + refactoring

ts/packages/agents/browser/src/agent/actionHandler.mts, ts/packages/agents/browser/src/agent/discovery/actionHandler.mts, ts/packages/agents/browser/src/agent/discovery/schema/discoveryActions.mts, ts/packages/agents/browser/src/agent/discovery/schema/recordedActions.mts, ts/packages/agents/browser/src/agent/discovery/translator.mts, ts/packages/agents/browser/src/extension/contentScript.ts, ts/packages/agents/browser/src/extension/serviceWorker.ts, ts/packages/agents/browser/src/extension/sidepanel.html, ts/packages/agents/browser/src/extension/sidepanel.ts
- Add tabs to show detailed recording actions
- first pass at processing recorded actions into usable schemas
=> [browser] improving action recording

ts/examples/chat/src/memory/podcastMemory.ts, ts/packages/knowPro/src/conversationThread.ts, ts/packages/knowPro/src/import.ts, ts/packages/knowPro/src/search.ts, ts/packages/knowPro/src/secondaryIndexes.ts
Ongoing evolution of **threads**
* Simplified + Refactored Thread interfaces.
* Reusable ConversationThreads class
=> knowpro: Threads simplification, refactoring

ts/packages/knowPro/src/conversationIndex.ts, ts/packages/knowPro/src/dataFormat.ts, ts/packages/knowPro/src/import.ts, ts/packages/knowPro/src/importImages.ts, ts/packages/knowPro/src/propertyIndex.ts, ts/packages/knowPro/src/query.ts, ts/packages/knowPro/src/search.ts
Replaced import {conversation} "kpLib"
=> knowpro: Rename import from knowledge-processor for clarity

ts/examples/chat/src/memory/knowproPrinter.ts, ts/packages/knowPro/src/common.ts, ts/packages/knowPro/src/dataFormat.ts, ts/packages/knowPro/src/fuzzyIndex.ts, ts/packages/knowPro/src/knowledge.ts, ts/packages/knowPro/src/messageIndex.ts, ts/packages/knowPro/src/relatedTermsIndex.ts, ts/packages/knowPro/src/search.ts, ts/packages/knowPro/src/secondaryIndexes.ts, ts/packages/knowPro/src/textLocationIndex.ts
- Refactoring
- Unified ScoredKnowledge type
- common.ts for shared internal types and code (in progress)
- **TextToTextLocationIndex**: 
- Starting Fuzzy index for find the Text Locations of "similar" text.
=> knowpro: TextToTextLocationIndex + Refactor

ts/packages/shell/package.json, ts/packages/shell/src/renderer/assets/styles.less, ts/pnpm-lock.yaml
Stop random build error from the font service.
=> Using local font instead of thru a URL

ts/examples/chat/src/memory/knowproMemory.ts, ts/packages/memory/image/src/importImages.ts
Image Collection Persistence:
- Moved to using 2 files; JSON for data, binary for embeddings. 
- Breaking change: old saved indexes will no longer work.
=> knowpro: Image Collection persistance

ts/packages/knowPro/src/secondaryIndexes.ts, ts/packages/knowPro/src/serialization.ts, ts/packages/memory/conversation/src/importPodcast.ts, ts/packages/memory/image/src/importImages.ts
=> knowpro: Simplify load/save of conversations

ts/examples/chat/src/memory/knowproCommon.ts, ts/examples/chat/src/memory/knowproMemory.ts, ts/examples/chat/src/memory/knowproPrinter.ts, ts/packages/knowPro/src/collections.ts, ts/packages/knowPro/src/conversation.ts, ts/packages/knowPro/src/index.ts, ts/packages/knowPro/src/interfaces.ts, ts/packages/knowPro/src/query.ts, ts/packages/knowPro/src/search.ts, ts/packages/knowPro/src/searchTranslator.ts
* Message selection using knowledge matches
* 3 search methods:
* searchConversation
* searchConversationKnowledge
* searchConversationWithNaturalLanguage 
* Improvements here
=> knowpro: now also return message matches

ts/examples/chat/src/memory/knowproMemory.ts, ts/packages/knowPro/src/collections.ts, ts/packages/knowPro/src/fuzzyIndex.ts, ts/packages/knowPro/src/index.ts, ts/packages/knowPro/src/interfaces.ts, ts/packages/knowPro/src/query.ts, ts/packages/knowPro/src/searchSchema.ts, ts/packages/knowPro/src/textLocationIndex.ts, ts/packages/memory/conversation/src/importPodcast.ts
- Starting message indexing. 
- Bug fixes to message matching.
- Deserialization bug in importPodcast
=> knowpro: message indexing, bugs  

ts/examples/chat/src/memory/knowproMemory.ts, ts/examples/chat/src/memory/knowproPrinter.ts, ts/packages/knowPro/src/conversationThread.ts, ts/packages/knowPro/src/fuzzyIndex.ts, ts/packages/knowPro/src/import.ts, ts/packages/knowPro/src/index.ts, ts/packages/knowPro/src/interfaces.ts, ts/packages/knowPro/src/messageIndex.ts, ts/packages/knowPro/src/secondaryIndexes.ts, ts/packages/knowPro/src/textLocationIndex.ts, ts/packages/memory/conversation/src/importPodcast.ts, ts/packages/typeagent/src/lib/array.ts
* Message Indexing 
* Refactored and re-arranged fuzzy/embedding indexing for better robustness. 
* Return partial results to allow restarts
* Cleaner batch behavior
* Classic RAG command
* Setting up for persisting message index serialization.
=> knowpro: Message Indexing 

ts/packages/agents/browser/src/agent/browserConnector.mts, ts/packages/agents/browser/src/agent/discovery/actionHandler.mts, ts/packages/agents/browser/src/agent/discovery/schema/pageComponents.mts, ts/packages/agents/browser/src/agent/discovery/schema/recordedActions.mts, ts/packages/agents/browser/src/agent/discovery/tempAgentActionHandler.mts, ts/packages/agents/browser/src/extension/serviceWorker.ts, ts/packages/agents/browser/src/extension/sidepanel.ts, ts/packages/agents/browser/src/extension/uiEventsDispatcher.ts
- Save discovered action sequences in extension local storage
- Add handler to run the user-defined intents based on the inferred plan
- Add helper ui automation to handle dropdowns
- Always run schema inference when use saves new recorded action.
=> Sidepanel: enable user-defined action sequences to run in the dynamic webAgent

ts/packages/agents/browser/src/extension/serviceWorker.ts, ts/packages/agents/browser/src/extension/sidepanel.html, ts/packages/agents/browser/src/extension/sidepanel.ts
- Update the dynamic webAgent whenever the schema is saved
- Simplify sidepanel UI
=> sidepanel: Update the dynamic webAgent whenever the schema is saved

ts/packages/knowPro/src/collections.ts, ts/packages/knowPro/src/propertyIndex.ts, ts/packages/knowPro/src/query.ts, ts/packages/knowPro/src/relatedTermsIndex.ts, ts/packages/knowPro/src/search.ts
- Better de-duping of related term matches to reduce over-counting/scoring. 
- Prefer entity name exact matches
=> knowpro: Relevance improvements

ts/examples/chat/src/memory/knowproMemory.ts, ts/examples/chat/src/memory/knowproPrinter.ts, ts/packages/knowPro/src/conversationIndex.ts, ts/packages/knowPro/src/interfaces.ts, ts/packages/knowPro/src/search.ts, ts/packages/memory/conversation/src/importPodcast.ts, ts/packages/memory/image/src/importImages.ts
* Simplify IConversation and IMessage; remove metadata dependency
* Align with Python impl
=> knowpro: simplify IConversatation, IMessage 

ts/Dockerfile
=> Add --legacy flag to pnpm deploy after v10 update

ts/examples/chat/src/memory/knowproCommon.ts, ts/examples/chat/src/memory/knowproMemory.ts, ts/examples/chat/src/memory/knowproPrinter.ts, ts/packages/knowPro/src/conversationIndex.ts, ts/packages/knowPro/src/interfaces.ts, ts/packages/knowPro/src/propertyIndex.ts, ts/packages/knowPro/src/relatedTermsIndex.ts, ts/packages/knowPro/src/secondaryIndexes.ts, ts/packages/knowPro/src/textLocationIndex.ts, ts/packages/knowPro/src/timestampIndex.ts, ts/packages/memory/conversation/src/importPodcast.ts, ts/packages/memory/image/src/importImages.ts
* Removed unused IMessageMetadata
* Integrated message indexing into *buildSecondaryIndex*
- Use buildTransientSecondaryIndexes function to get rid of flags
* Improved IndexResults, now with detailed indexing status
* Better indexing callbacks
=> knowpro: refactoring, integrate message indexing

python/ta/Makefile, python/ta/README.md, python/ta/pyproject.toml, python/ta/requirements.txt, python/ta/typeagent/knowpro/convindex.py, python/ta/typeagent/knowpro/interfaces.py, python/ta/typeagent/memconv/__main__.py, python/ta/typeagent/memconv/import_podcasts.py
Note: the rename from ...Index to ...Ordinal (when it's an int) is not technically Steve-approved yet. It's easy to change.
Other minimal tweaks.
=> [python/knowpro] Improvebuild infra; rename Index to Ordinal

ts/examples/chat/src/memory/knowproCommon.ts, ts/examples/chat/src/memory/knowproMemory.ts, ts/examples/chat/src/memory/knowproPrinter.ts, ts/examples/chat/src/memory/podcastMemory.ts, ts/packages/knowPro/src/collections.ts, ts/packages/knowPro/src/common.ts, ts/packages/knowPro/src/conversationIndex.ts, ts/packages/knowPro/src/conversationThread.ts, ts/packages/knowPro/src/interfaces.ts, ts/packages/knowPro/src/knowledge.ts, ts/packages/knowPro/src/messageIndex.ts, ts/packages/knowPro/src/propertyIndex.ts, ts/packages/knowPro/src/query.ts, ts/packages/knowPro/src/search.ts, ts/packages/knowPro/src/timestampIndex.ts, ts/packages/memory/conversation/src/importPodcast.ts, ts/packages/memory/image/src/importImages.ts
* Renamed all 'ordinal' types from ****Index*** to ****Ordinal*** 
* Updated all variable and parameter names
* The above causes file format changes. Please rebuild indexes.
* Bug fixes
=> knowpro: (a) For clarity: refactor ordinal types and fields (b) file format change  

ts/packages/dispatcher/src/context/chatHistoryPrompt.ts
Make the check for context-free translation (for caching) is more accurate.
=> Consistent clarifying instruction for prompt with and without context.

ts/examples/chat/src/memory/knowproMemory.ts, ts/packages/knowPro/src/collections.ts, ts/packages/knowPro/src/interfaces.ts, ts/packages/knowPro/src/search.ts, ts/packages/knowPro/test/collections.spec.ts
- Small refactoring to collections experiments. 
- Bug fixes
- NLP testing: adding flags
=> knowpro: refactoring, bug fix

ts/examples/chat/src/memory/knowproPrinter.ts, ts/packages/knowPro/src/collections.ts, ts/packages/knowPro/src/query.ts, ts/packages/knowPro/src/relatedTermsIndex.ts, ts/packages/knowPro/src/search.ts, ts/packages/knowPro/src/searchQueryTranslator.ts, ts/packages/knowPro/src/serialization.ts
* Ongoing work on natural language querying:
* Use actionTerm.additionalEntities as scoping terms
* Optional scoping terms on WhenFilter
*  Reorganized query builder
* Other refactoring
* File Header for serialization
* Bug fixes
* Some more documentation
=> knowpro: natural language query improvements; refactor

ts/examples/docuProc/package.json, ts/examples/docuProc/src/main.ts, ts/examples/docuProc/src/pdfFileDocumenter.ts, ts/examples/docuProc/src/pdfImporter.ts, ts/examples/docuProc/src/pdfQNAInteractiveApp.ts
The [deploy pipeline] (https://github.com/microsoft/TypeAgent/actions/runs/13958193623/job/39074210269) was failure because of this.
Misc fixes in docupro.
=> Fix typo on docupro package.json

ts/packages/cli/src/commands/test/translate.ts, ts/packages/defaultAgentProvider/test/translateTestCommon.ts, ts/packages/dispatcher/src/context/chatHistoryPrompt.ts, ts/packages/dispatcher/src/context/session.ts, ts/packages/dispatcher/src/execute/actionHandlers.ts, ts/packages/dispatcher/src/translation/translateRequest.ts
Add a fixed schema mode for testing (make sure switching works).
=> Fixed first schema mode

python/ta/TODO.md, python/ta/pyproject.toml, python/ta/typeagent/aitools/vectorbase.py, python/ta/typeagent/knowpro/__init__.py, python/ta/typeagent/knowpro/convindex.py, python/ta/typeagent/knowpro/convthreads.py, python/ta/typeagent/knowpro/interfaces.py, python/ta/typeagent/knowpro/kplib.py, python/ta/typeagent/knowpro/relatedtermsindex.py, python/ta/typeagent/knowpro/secindex.py, python/ta/typeagent/podcasts/__init__.py, python/ta/typeagent/podcasts/__main__.py, python/ta/typeagent/podcasts/podcast.py, python/ta/typeagent/podcasts/podcast_import.py
Had to add a lot of new serialization data classes (inheriting from TypedDict) since a dataclass doesn't look like a dict in Python.
It's still a bit messy due to the moving around of classes (mostly into interfaces) to avoid circular imports.
=> [python/knowpro] Serialization works! (except embeddings)

ts/packages/knowPro/src/common.ts, ts/packages/knowPro/src/query.ts, ts/packages/knowPro/src/search.ts, ts/packages/knowPro/src/searchQueryTranslator.ts
Improve natural language query precision:
* or_max query operator from knowledge-processor
* Builder updated to produce better queries trees
=> knowpro: natural language query precision

python/ta/.gitignore, python/ta/TODO.md, python/ta/typeagent/aitools/vectorbase.py, python/ta/typeagent/knowpro/convthreads.py, python/ta/typeagent/knowpro/importing.py, python/ta/typeagent/knowpro/interfaces.py, python/ta/typeagent/knowpro/serialization.py
Possibly some other serialize() functions could be replaced by serialization.serialize_object() too.
Also the usual cleanups, refactorings, etc. (notably moved TextEmbeddingIndexSettings from knowpro/importing.py to aitools/vectorbase.py).
=> [python/knowpro] Complete Knowledge serialization

ts/.vscode/launch.json, ts/packages/aiclient/src/bing.ts, ts/packages/aiclient/test/bing.spec.ts
Bing search:
- Add site specific search option
- Unit tests
=> Bing: site search, unit tests

python/ta/TODO.md, python/ta/demo.py, python/ta/typeagent/aitools/embeddings.py, python/ta/typeagent/aitools/vectorbase.py, python/ta/typeagent/knowpro/convindex.py, python/ta/typeagent/knowpro/convthreads.py, python/ta/typeagent/knowpro/interfaces.py, python/ta/typeagent/knowpro/messageindex.py, python/ta/typeagent/knowpro/relatedtermsindex.py, python/ta/typeagent/knowpro/secindex.py, python/ta/typeagent/knowpro/serialization.py, python/ta/typeagent/knowpro/textlocationindex.py, python/ta/typeagent/podcasts/__main__.py, python/ta/typeagent/podcasts/podcast.py
I had the design for deserialize_object() in my head but had trouble getting it out of there onto paper / code. So I gave ChatGPT a careful description of what I wanted, let it ask clarifying questions, answered those, and I was 90% there. The things I had to add were things I had left out of the spec, and some typing introspection oddity around the two ways of spelling unions.
=> [python/knowpro] Complete deserialization (largely with the help of o3-mini-high)

ts/.vscode/launch.json, ts/packages/knowPro/src/collections.ts, ts/packages/knowPro/src/common.ts, ts/packages/knowPro/src/conversationIndex.ts, ts/packages/knowPro/src/index.ts, ts/packages/knowPro/src/message.ts, ts/packages/knowPro/src/query.ts, ts/packages/knowPro/src/queryCmp.ts, ts/packages/knowPro/src/search.ts, ts/packages/knowPro/src/timestampIndex.ts, ts/packages/knowPro/test/query.message.spec.ts, ts/packages/knowPro/test/query.spec.ts, ts/packages/knowPro/test/queryCmp.spec.ts, ts/packages/knowPro/test/testCommon.ts, ts/packages/knowPro/test/verify.ts
* Comparison Operators
* Lt, Lte, Gt, Gte etc. 
* Loopy implementation for Facets
* Message matches to scoping ranges
* Unit Tests
=> knowpro: Comparison operations, message matching, unit tests

python/ta/Makefile, python/ta/TODO.md, python/ta/demo.py, python/ta/typeagent/aitools/vectorbase.py, python/ta/typeagent/knowpro/convindex.py, python/ta/typeagent/knowpro/convthreads.py, python/ta/typeagent/knowpro/interfaces.py, python/ta/typeagent/knowpro/kplib.py, python/ta/typeagent/knowpro/messageindex.py, python/ta/typeagent/knowpro/relatedtermsindex.py, python/ta/typeagent/knowpro/secindex.py, python/ta/typeagent/knowpro/serialization.py, python/ta/typeagent/knowpro/textlocationindex.py, python/ta/typeagent/podcasts/__main__.py, python/ta/typeagent/podcasts/podcast.py, python/ta/typeagent/podcasts/podcast_import.py
Also:
- Remove 'I' from serialization TypedDicts.
- Pass settings to Podcast.read_from_file().
=> [python/knowpro] Fixes to the deserialization to be able to read TS-generated dumps

.gitignore, python/ta/make.bat, python/ta/typeagent/knowpro/serialization.py
* Add encoding="utf-8" when opening text files to read or write serializations.
=> [python/knowpro] Add make.bat to run things on Windows

ts/packages/agentSdk/src/action.ts, ts/packages/agents/list/src/listActionHandler.ts, ts/packages/agents/list/src/listSchema.ts, ts/packages/cache/src/explanation/requestAction.ts, ts/packages/cache/src/index.ts, ts/packages/dispatcher/src/context/appAgentManager.ts, ts/packages/dispatcher/src/context/chatHistoryPrompt.ts, ts/packages/dispatcher/src/context/commandHandlerContext.ts, ts/packages/dispatcher/src/context/dispatcher/dispatcherAgent.ts, ts/packages/dispatcher/src/context/dispatcher/dispatcherUtils.ts, ts/packages/dispatcher/src/context/dispatcher/handlers/requestCommandHandler.ts, ts/packages/dispatcher/src/context/dispatcher/schema/activityActionSchema.ts, ts/packages/dispatcher/src/execute/actionHandlers.ts, ts/packages/dispatcher/src/translation/agentTranslators.ts, ts/packages/dispatcher/src/translation/translateRequest.ts
- Allow an action to enter an "activity" that focuses on a task, by limiting the schema that are in use.
- Add "edit list" activity in the list agent.
=> Initial implementation of activity mode

ts/.vscode/launch.json, ts/examples/chat/src/memory/knowproCommon.ts, ts/examples/chat/src/memory/podcastMemory.ts, ts/packages/knowPro/src/conversationIndex.ts, ts/packages/knowPro/src/interfaces.ts, ts/packages/knowPro/src/knowledge.ts, ts/packages/knowPro/src/message.ts, ts/packages/knowPro/src/query.ts, ts/packages/knowPro/test/collections.spec.ts, ts/packages/knowPro/test/data/Episode_53_query.txt, ts/packages/knowPro/test/message.spec.ts, ts/packages/knowPro/test/testCommon.ts, ts/packages/knowPro/test/testMessage.ts, ts/packages/memory/conversation/test/podcast.spec.ts, ts/packages/memory/conversation/test/testCommon.ts
* Batch Indexing for Semantic Refs
* Support indexing multiple chunks
* Return correct indexing results for retries
*  Unit Tests
=> knowpro: Batched Indexing, unit tests 

ts/packages/shell/src/main/index.ts, ts/packages/shell/src/main/shellSettings.ts, ts/packages/shell/src/renderer/src/chatView.ts, ts/packages/shell/src/renderer/src/main.ts, ts/packages/shell/src/renderer/viewHost.html
- The main window shouldn't zoom, so that the divider will be at the right position.
- Zoom apply to both chat view and browser view together.
- Save the right value (from chat view) for zoom and F12 settings (TODO: might want to save the state for the main window and inline browser as well)
- Set up F12 for main window as well.
=> Fix shell zoom settings

ts/packages/knowPro/src/common.ts, ts/packages/knowPro/src/dataFrame.ts, ts/packages/knowPro/src/interfaces.ts, ts/packages/knowPro/src/query.ts, ts/packages/knowPro/src/search.ts, ts/packages/knowPro/src/searchQueryTranslator.ts, ts/packages/knowPro/test/search.spec.ts, ts/packages/knowPro/test/testCommon.ts, ts/packages/knowPro/test/verify.ts
* Refactor
* Interface updates
* Starting Data Frame
=> knowpro: Refactor, DataFrame start

ts/packages/agents/greeting/package.json, ts/packages/agents/greeting/src/greetingCommandHandler.ts, ts/pnpm-lock.yaml
=> Use debug trace in greeting agent

ts/examples/chat/src/memory/knowproDataFrame.ts, ts/packages/knowPro/src/collections.ts, ts/packages/knowPro/src/conversationIndex.ts, ts/packages/knowPro/src/dataFrame.ts, ts/packages/knowPro/src/dataFrameQuery.ts, ts/packages/knowPro/src/index.ts, ts/packages/knowPro/src/interfaces.ts, ts/packages/knowPro/src/knowledge.ts, ts/packages/knowPro/src/query.ts, ts/packages/knowPro/src/search.ts
Ongoing experiments:
* Hybrid Conversations that integrate DataFrames/Tables for storage
* Query processing: automatic routing of query terms to appropriate frames
* Operators
* First examples of:
*  Using data frames for **outer scope** resolution
* Using data frame matches to resolve messages
* NLP querying 
* More to come
=> knowpro: Hybrid Conversations with DataFrames

ts/packages/agents/player/package.json, ts/packages/agents/player/src/endpoints.ts, ts/packages/agents/player/src/tokenProvider.ts, ts/packages/agents/player/src/utils.ts, ts/packages/coda/package.json, ts/pnpm-lock.yaml
Also clean up the endpoint calling code.
=> Music play use fetch instead of axios

python/commonCrawlData/.funcignore, python/commonCrawlData/.gitignore, python/commonCrawlData/README.md, python/commonCrawlData/get_urls/__init__.py, python/commonCrawlData/get_urls/function.json, python/commonCrawlData/host.json, python/commonCrawlData/http_start/__init__.py, python/commonCrawlData/http_start/function.json, python/commonCrawlData/orchestrator/__init__.py, python/commonCrawlData/orchestrator/function.json, python/commonCrawlData/process_url_batch/__init__.py, python/commonCrawlData/process_url_batch/function.json, python/commonCrawlData/requirements.txt, python/commonCrawlData/save_results/__init__.py, python/commonCrawlData/save_results/function.json
Adding an Azure function that can search for entries in common crawl, find WARC files corresponding to specific files and extract [schema.org](https://schema.org) [Restaurant](https://schema.org/Restaurant) entries.
=> extract JSON-LD from common crawl

ts/packages/agents/browser/package.json, ts/packages/agents/browser/src/agent/actionHandler.mts, ts/packages/agents/browser/src/extension/contentScript/eventHandlers.ts, ts/packages/agents/browser/src/extension/serviceWorker/index.ts, ts/packages/agents/browser/src/extension/serviceWorker/storage.ts, ts/packages/agents/browser/src/extension/uiEventsDispatcher.ts
- Update logic for selecting input elements for page-level text input
- Handle async messages
=> Fix UI event dispatching bugs

ts/examples/chat/package.json, ts/examples/chat/src/memory/knowproDataFrame.ts, ts/examples/chat/src/memory/restaurantDb.ts, ts/packages/knowPro/src/dataFrame.ts, ts/packages/memory/storage/src/sqlite/index.ts, ts/packages/memory/storage/src/sqlite/sqliteDataFrame.ts, ts/pnpm-lock.yaml
* Data Frame on Sqlite
* Hybrid querying using Sqlite data frames
=> knowpro: Ongoing DataFrame experiments

python/commonCrawlData/process_url_batch/__init__.py, ts/examples/microdataExtract/src/commands/filter.ts, ts/examples/microdataExtract/src/commands/merge.ts
[#96](https://github.com/microsoft/TypeAgent/security/code-scanning/96)
[#95](https://github.com/microsoft/TypeAgent/security/code-scanning/95)
[#94](https://github.com/microsoft/TypeAgent/security/code-scanning/94)
[#93](https://github.com/microsoft/TypeAgent/security/code-scanning/93)
[#92](https://github.com/microsoft/TypeAgent/security/code-scanning/92)
[#91](https://github.com/microsoft/TypeAgent/security/code-scanning/91)
=> Fixing URL-related codeql errors

ts/packages/shell/src/main/agent.ts, ts/packages/shell/src/preload/shellSettingsType.ts, ts/packages/shell/src/renderer/src/setContent.ts, ts/packages/shell/src/renderer/src/settingsView.ts
Add completion for `@shell set` command for settings
=> Shell set command settings completion

ts/examples/chat/src/memory/knowproMemory.ts, ts/examples/chat/src/memory/knowproPrinter.ts, ts/packages/knowPro/src/answerContextSchema.ts, ts/packages/knowPro/src/answerGenerator.ts, ts/packages/knowPro/src/answerResponseSchema.ts, ts/packages/knowPro/src/interfaces.ts, ts/packages/knowPro/src/message.ts, ts/packages/knowPro/src/searchLang.ts, ts/packages/memory/conversation/src/conversationMemory.ts, ts/packages/memory/conversation/src/podcast.ts, ts/packages/memory/image/src/importImages.ts
* Improved answer generation
* Attribution for entities
* Better schema for accurate answers
* Debug code
* Bug fixes
=> knowpro: Answer Generation improvements

python/ta/Makefile, python/ta/make.bat, python/ta/pyproject.toml, python/ta/requirements.txt, python/ta/test/fixtures.py, python/ta/test/test_demo.py, python/ta/test/test_vectorbase.py, python/ta/typeagent/aitools/vectorbase.py
test/test_vectorbase.py is a collaboration with Copilot (through VS Code). It helped a lot writing tests!
=> [python/knowpro] Add test_vectorbase and fix VectorBase bugs

python/ta/Makefile, python/ta/make.bat, python/ta/requirements.txt, python/ta/test/test_auth.py, python/ta/test/test_embeddings.py, python/ta/typeagent/aitools/auth.py, python/ta/typeagent/aitools/embeddings.py
Also extend scope of `make check` to include the `test` directory.
=> [python/knowpro] Add test_embeddings.py and test_auth.py and fix bugs they found

python/ta/test/test_auth.py, python/ta/test/test_interfaces.py, python/ta/test/test_kplib.py, python/ta/test/test_serialization.py, python/ta/typeagent/knowpro/serialization.py
Also reformat test_auth.py.
(I just realize I have to keep on top of the formatting myself, there's no repo root for that yet.)
=> [python/knowpro] Add test_interfaces, test_kplib, test_serialization. No bug found.

ts/examples/chat/src/memory/knowproCommon.ts, ts/examples/chat/src/memory/knowproDataFrame.ts, ts/examples/chat/src/memory/knowproMemory.ts, ts/examples/chat/src/memory/knowproPrinter.ts, ts/packages/agents/montage/src/agent/montageActionHandler.ts, ts/packages/knowPro/src/collections.ts, ts/packages/knowPro/src/common.ts, ts/packages/knowPro/src/conversation.ts, ts/packages/knowPro/src/conversationIndex.ts, ts/packages/knowPro/src/interfaces.ts, ts/packages/knowPro/src/message.ts, ts/packages/knowPro/src/messageIndex.ts, ts/packages/knowPro/src/query.ts, ts/packages/knowPro/src/storage.ts, ts/packages/knowPro/src/timestampIndex.ts, ts/packages/knowPro/test/collections.spec.ts, ts/packages/knowPro/test/message.spec.ts, ts/packages/knowPro/test/testCommon.ts, ts/packages/knowPro/test/testMessage.ts, ts/packages/knowPro/test/verify.ts, ts/packages/memory/conversation/src/conversationMemory.ts, ts/packages/memory/conversation/src/podcast.ts, ts/packages/memory/conversation/test/testCommon.ts, ts/packages/memory/image/src/importImages.ts, ts/packages/memory/image/src/indexingService.ts
Conversation:
* Move messages to collections for out of memory storage.
=> knowpro: prepping for email indexing

ts/packages/knowPro/src/dataFrame/dataFrame.ts, ts/packages/knowPro/src/interfaces.ts, ts/packages/knowPro/src/storage.ts, ts/packages/knowledgeProcessor/src/email/email.ts, ts/packages/knowledgeProcessor/src/email/emailSchema.ts, ts/packages/memory/conversation/package.json, ts/packages/memory/conversation/src/email.ts, ts/packages/memory/conversation/src/emailMemory.ts, ts/packages/memory/conversation/src/emailMessage.ts, ts/packages/memory/conversation/src/importPodcast.ts, ts/packages/memory/conversation/src/index.ts, ts/packages/memory/conversation/src/podcast.ts, ts/packages/memory/conversation/src/podcastMessage.ts, ts/packages/memory/conversation/test/email.spec.ts, ts/packages/memory/conversation/test/testCommon.ts, ts/packages/memory/conversation/test/verify.ts, ts/packages/memory/storage/src/sqlite/index.ts, ts/packages/memory/storage/src/sqlite/sqliteProvider.ts, ts/pnpm-lock.yaml
Email Memory on knowpro
* Setting up index structure
* Using Sql Storage provider for message storage
* First Unit tests
=> knowpro: Email memory, part1

python/ta/test/test_convindex.py, python/ta/test/test_messageindex.py, python/ta/test/test_propindex.py, python/ta/test/test_serialization.py, python/ta/typeagent/knowpro/propindex.py, python/ta/typeagent/knowpro/serialization.py
Only test_propindex found a (significant) bug.
test_messageindex has some skipped parts which I haven't been able to debug yet.
make check fails for some tests.
Also reformatted some files from a previous commit.
=> [python/knowpro] Add test_convindex, test_propindex, test_messageindex

ts/packages/agents/oracle/src/oracleActionHandler.ts, ts/packages/shell/electron-builder.config.js, ts/packages/shell/package.json, ts/packages/shell/src/main/agent.ts, ts/packages/shell/src/main/commands/update.ts, ts/packages/shell/src/main/debug.ts, ts/packages/shell/src/main/index.ts, ts/packages/shell/src/main/shellSettings.ts, ts/packages/shell/src/main/shellWindow.ts, ts/packages/shell/src/main/tsconfig.json, ts/pnpm-lock.yaml
Implement a command to auto update packaged installs.
=> `@shell update check` command

.github/workflows/build-package-shell.yml
Also remove uploading artifact.
=> Add pipeline permissions.

ts/examples/chat/src/memory/knowproMemory.ts, ts/packages/agents/montage/src/agent/montageActionHandler.ts, ts/packages/knowPro/src/answerGenerator.ts, ts/packages/knowPro/src/messageIndex.ts, ts/packages/knowPro/src/query.ts, ts/packages/knowPro/src/search.ts, ts/packages/knowPro/src/searchLang.ts
* Answer Generation
* Improved natural language matching
* Better output
* Settings
* Bug fixes 
* Refactor:  
* Removed old test options
=> knowpro: Answer Generation improvements, refactor

ts/packages/shell/src/main/commands/update.ts, ts/tools/scripts/install-shell.cmd
Should update last check data for all "install" checks.
=> Fix update status command

ts/packages/shell/electron-builder.config.js, ts/packages/shell/package.json, ts/packages/shell/src/main/index.ts
Set product name in the package.json so that the data directory name will use it.
=> Shell product name

ts/packages/shell/src/main/args.ts, ts/packages/shell/src/main/index.ts, ts/packages/shell/src/renderer/src/chatView.ts
Double check if we are scrolling after requestAnimationFrame before calling "scrollIntoView"
=> Shell fix scrolling and allow dev build to have single instance.

ts/packages/agents/browser/src/agent/discovery/authoringActionHandler.mts, ts/packages/agents/browser/src/agent/discovery/authoringUtilities.mts, ts/packages/agents/browser/src/agent/discovery/tempAgentActionHandler.mts, ts/packages/planVisualizer/public/css/styles.css, ts/packages/planVisualizer/public/index.html, ts/packages/planVisualizer/src/client/app.ts, ts/packages/planVisualizer/src/client/cytoscapeConfig.ts, ts/packages/planVisualizer/src/client/visualizer.ts, ts/packages/shell/src/main/agent.ts, ts/packages/shell/src/main/shellActionSchema.ts
- Add command and schema support for launching the plan visualizer inline
- Update label position when nodes show a screenshot
- Make preview canvas size responsive
=> Integrate plan visualizer with inline browser

pipelines/azure-build-package-shell.yml, pipelines/azure-build-ts.yml, pipelines/include-prepare-repo.yml, pipelines/include-update-package-version.yml, ts/package.json
Also refactor common steps in the pipelines.
=> Azure NPM package build pipeline use internal feed

ts/examples/chat/src/memory/chatMemory.ts, ts/examples/chat/src/memory/common.ts, ts/examples/chat/src/memory/podcastMemory.ts
Updated Chat Example
* Command to copy messages + knowledge from one conversation into another
* Command to export podcast messages and knowledge
=> conversation memory: copy and clone command

ts/examples/chat/src/memory/chatMemory.ts
Small change:
Added useful flags to new copyConversation command
=> conversation copy impovement

ts/packages/agents/montage/src/agent/montageActionHandler.ts
Change the minScore, scores are decimal between 0 to 1.
Clean up some of the code referencing the active montage.
=> Montage: fix create with filter

ts/packages/cli/src/commands/constructions.ts, ts/packages/cli/src/commands/data/add.ts, ts/packages/cli/src/commands/data/regenerate.ts, ts/packages/cli/src/commands/data/stat.ts, ts/packages/cli/src/commands/interactive.ts, ts/packages/cli/src/commands/run/explain.ts, ts/packages/cli/src/commands/run/request.ts, ts/packages/cli/src/commands/run/translate.ts, ts/packages/cli/src/commands/schema.ts, ts/packages/cli/src/commands/test/translate.ts, ts/packages/defaultAgentProvider/src/defaultAgentProviders.ts, ts/packages/defaultAgentProvider/test/construction.spec.ts, ts/packages/defaultAgentProvider/test/constructionCacheTestCommon.ts, ts/packages/defaultAgentProvider/test/schema.spec.ts, ts/packages/dispatcher/src/context/inlineAgentProvider.ts, ts/packages/dispatcher/src/internal.ts
Expand the switch test to include all schema except mcpfilesystem
=> Clean up internal provider create for CLI.

ts/packages/dispatcher/src/translation/actionTemplate.ts
- The typing for call to `toTemplate` is incorrect, as it expects an `ExecutableAction`, but got passed in a `FullAction`. 
Regression from #671 
- Change it to accept `FullAction`
- Use `unknown` instead of `any` for safety in `getSystemTemplateSchema`
=> Fix confirm flow

ts/examples/chat/src/memory/knowproMemory.ts, ts/examples/docuProc/src/srag/pdfKnowproMem.ts, ts/packages/knowPro/src/fuzzyIndex.ts, ts/packages/knowPro/src/messageIndex.ts, ts/packages/knowPro/src/query.ts, ts/packages/knowPro/src/relatedTermsIndex.ts, ts/packages/knowPro/src/search.ts, ts/packages/knowPro/src/searchLang.ts, ts/packages/knowPro/src/textLocationIndex.ts
* Query processing
* Query operator for similarity matching
* Outer Scope application for similarity (date ranges, etc.)
* Custom predicate for fuzzy matching
* Search API
* Language Query
* Switched fallback to use new operators
* Email related bug fixes
* Refactor
* Commands
* Updated test commands
=> knowpro: Email, Natural Language Query, Bugs

ts/examples/chat/README.md, ts/examples/chat/src/memory/knowproChat.ts, ts/examples/chat/src/memory/knowproDataFrame.ts, ts/examples/chat/src/memory/knowproMemory.ts, ts/packages/knowPro/README.md, ts/packages/knowPro/src/dataFrame/searchQuerySchema2.ts, ts/packages/memory/conversation/README.md, ts/packages/memory/conversation/src/conversationMemory.ts, ts/packages/memory/conversation/src/email.ts
Chat example app update: 
- Now also implements knowpro based conversation memory
=> knowpro:  Conversation Memory example

python/ta/typeagent/knowpro/collections.py, python/ta/typeagent/knowpro/common.py, python/ta/typeagent/knowpro/query.py
Added to MatchAccumulator:
- __iter__
- add_union (fix signature)
- combine_matches
- calculate_total_score
- get_top_n_scoring
- get_matched_values (fix return type)
- select_top_n_scoring
Added to SemanticRefAccumulator:
- fix signature of add_union
Added class ScoredItem, and class TopNCollection, and derived classes TopNList and TopNListAll.
Added classes SelectTopNExpr, MatchTermsBooleanExpr, MatchTermsOrExpr.
Added class IQueryTextRangeSelector.
Added class GetScopeExpr.
=> [python/knowpro] Slowly making progress on query.py, filling some gaps in collections.py

ts/examples/chat/package.json, ts/examples/docuProc/src/pdfChunker.ts, ts/examples/spelunker/src/pythonChunker.ts, ts/packages/commonUtils/package.json, ts/pnpm-lock.yaml
For better args incase they include quotes that change the meaning of the command line.
=> Switch to use execFile instead of exec

ts/packages/api/src/webDispatcher.ts, ts/packages/dispatcher/src/context/commandHandlerContext.ts, ts/packages/dispatcher/src/execute/actionHandlers.ts, ts/packages/shell/src/main/index.ts
Also fix entity resolution with arrays.
=> Default explainer to async

ts/packages/knowPro/README.md
knowpro README:
- Improved overview of a typical query flow
=> knowpro: README updates

README.md, docs/architecture/dispatcher.md, dotnet/README.md, python/README.md, ts/README.md, ts/examples/playground/README.md, ts/examples/schemaStudio/ReadMe.md, ts/packages/agents/calendar/README.md, ts/packages/agents/chat/README.md, ts/packages/agents/email/README.md, ts/packages/agents/greeting/README.md, ts/packages/agents/spelunker/evals/eval-1/source/dispatcher/README.md, ts/packages/api/README.md, ts/packages/cli/README.md, ts/packages/codeProcessor/README.md, ts/packages/dispatcher/README.md, ts/packages/knowPro/README.md, ts/packages/knowledgeProcessor/README.md, ts/packages/schemaAuthor/README.md, ts/packages/shell/README.md
Also clean up TypeChat verbiage.
=> Root README.md overview update

CONTRIBUTIONS.md, README.md
- Remove contributions section from main README
- Add a new `CONTRIBUTIONS.md` file to the root of the repository to provide a detailed guide on how to contribute to the project.
=> Add contributions in separate markdown file. 

python/ta/TODO.md, python/ta/test/test_knowledge.py, python/ta/test/test_query.py, python/ta/typeagent/knowpro/collections.py, python/ta/typeagent/knowpro/query.py
Also:
- Add `add_term_matches_if_new()` in collections.py
- Fix `intersection` in `SemanticRefAccumulator` in collections.py
- Implemented `TextRangeSelector` in query.py
=> [python/knowpro] Add test_query.py and test_knowledge.py

docs/architecture/memory.md, ts/packages/knowPro/src/searchLang.ts
=> Updated docs

README.md, docs/architecture/dispatcher.md, docs/setup/setup-Linux.md, docs/setup/setup-WSL2.md, docs/setup/setup-Windows.md, ts/packages/knowPro/README.md, ts/packages/knowledgeProcessor/README.md
=> Minor doc fixes.

README.md, ts/packages/knowPro/README.md
* Fixed typo on main README
* Small updates to KnowPro Readme
=> Readme updates

ts/examples/agentExamples/measure/README.md
Updated Readme for agent example
=> Example Readme update

README.md, docs/setup/setup-Linux.md, docs/setup/setup-WSL2.md, docs/setup/setup-Windows.md, docs/setup/setup-macOS.md
=> Doc update: pointer to discussion

ts/tools/scripts/README.MD, ts/tools/scripts/armTemplates/template.json, ts/tools/scripts/azureDeploy.mjs, ts/tools/scripts/lib/azureUtils.mjs, ts/tools/scripts/lib/pimClient.mjs
- Needs to add `{shell : true }` options to run AzCLI, which is a script.
- Refactoring so that PIM client and deploy share some code.
=> Fix deploy script running in windows

ts/packages/agentSdk/src/helpers/actionHelpers.ts, ts/packages/agentSdk/src/index.ts, ts/packages/agents/montage/src/agent/montageActionHandler.ts, ts/packages/agents/montage/src/agent/montageActionSchema.ts, ts/packages/agents/montage/src/route/route.ts, ts/packages/dispatcher/src/context/dispatcher/dispatcherAgent.ts, ts/packages/dispatcher/src/context/dispatcher/dispatcherUtils.ts, ts/packages/dispatcher/src/context/session.ts, ts/packages/dispatcher/src/context/system/handlers/indexCommandHandler.ts, ts/packages/dispatcher/src/execute/actionHandlers.ts, ts/packages/shell/src/renderer/src/setContent.ts
- Add clarification flow for multiple entity matches (disabled by default)
- Refactor entity resolution between parameter and results.
- Add (and fix extra line-break in display) for multi-line mode for markdown results.
=> Entity clarification

python/ta/test/test_demo.py, python/ta/test/test_vectorbase.py, python/ta/typeagent/aitools/vectorbase.py, python/ta/typeagent/demo/ui.py, python/ta/typeagent/knowpro/convthreads.py, python/ta/typeagent/knowpro/fuzzyindex.py, python/ta/typeagent/knowpro/reltermsindex.py, python/ta/typeagent/knowpro/textlocindex.py
Streamline fuzzyindex.py and textlocindex.py. Improve query pretty-printing.
=> [python/knowpro] Follow-up to last night

ts/packages/shell/electron-builder.config.js
Also remove non-existing plist for macos.
=> Package: remove windows only binaries from linux/macOS package

python/ta/typeagent/demo/ui.py, python/ta/typeagent/knowpro/search_query_schema.py
One of the doc bugs in particular (apparently inserted by Copilot when asked to translate the schema from TypeScript to Python) changed the docs for SearchFilter to cause the AI to *always* construct a search filter. Thanks @umeshma for making me review this and realize the problem.
=> [python/knowpro] Fix doc bugs in query schema; improve debug output

ts/packages/agentSdk/src/agentInterface.ts, ts/packages/agents/browser/package.json, ts/packages/agents/browser/src/agent/actionHandler.mts, ts/packages/dispatcher/src/context/system/handlers/indexCommandHandler.ts, ts/pnpm-lock.yaml
- Integrate website semantic search with URL resolve logic
- Persist the website index
=> Resolve website URLs from website visit data (bookmarks and history)

ts/examples/chat/src/memory/knowproTest.ts, ts/examples/examplesLib/src/file.ts, ts/packages/interactiveApp/src/interactiveApp.ts, ts/packages/knowProTest/src/answerTest.ts, ts/packages/knowProTest/src/common.ts, ts/packages/knowProTest/src/knowproCommands.ts, ts/packages/knowProTest/src/searchTest.ts, ts/packages/knowProTest/src/types.ts
* Search Test Batching & Verification against baseline
* Support working directory switching in _batch_
* Load command
=> knowproTest updates

ts/examples/chat/src/memory/knowproTest.ts, ts/packages/interactiveApp/src/interactiveApp.ts, ts/packages/knowPro/src/answerGenerator.ts, ts/packages/knowProTest/src/answerTest.ts, ts/packages/knowProTest/src/searchTest.ts, ts/packages/knowProTest/src/types.ts
* Improvements to batch data generators & verifiers. 
* Relative path support
=> knowproTest: Improvements

python/ta/typeagent/aitools/embeddings.py, python/ta/typeagent/demo/ui.py, python/ta/typeagent/knowpro/fuzzyindex.py, python/ta/typeagent/knowpro/importing.py, python/ta/typeagent/knowpro/searchlang.py, python/ta/typeagent/knowpro/textlocindex.py
And the usual ui.py and formatting tweaks.
=> [python/knowpro] Share the one and only AsyncEmbeddingModel

python/ta/TODO.md, python/ta/pyproject.toml, python/ta/test/cmpsearch.py, python/ta/typeagent/demo/answer_context_schema.py, python/ta/typeagent/demo/ui.py, python/ta/typeagent/knowpro/convutils.py, python/ta/typeagent/knowpro/searchlang.py, python/ta/uv.lock
This brings searchlang.py closer to its TypeScript equivalent.
Also move some other things out of ui.py to where they should be (convutils.py).
Add a little test utility that reads the question/expected-answer pairs from a certain JSON file.
=> [python/knowpro] Move search logic from ui.py to searchlang.py., and other slight improvements

python/ta/typeagent/knowpro/collections.py
Forgot to fix this in the previous PR.
=> [pyhon/knowpro] Add missing MessageAccumulator.intersect override

ts/packages/agentRpc/src/rpc.ts, ts/packages/agents/browser/package.json, ts/packages/agents/browser/src/agent/actionHandler.mts, ts/packages/agents/browser/src/agent/browserControl.mts, ts/packages/agents/browser/src/agent/rpc/externalBrowserControlClient.mts, ts/packages/agents/browser/src/common/contentScriptRpc/client.mts, ts/packages/agents/browser/src/common/contentScriptRpc/types.mts, ts/packages/agents/browser/src/extension/contentScript/eventHandlers.ts, ts/packages/agents/browser/src/extension/serviceWorker/browserActions.ts, ts/packages/agents/browser/src/extension/serviceWorker/externalBrowserControlServer.ts, ts/packages/shell/src/main/inlineBrowserControl.ts, ts/packages/shell/src/preload/index.ts, ts/packages/shell/src/preload/inlineBrowserRendererRpcServer.ts, ts/packages/shell/src/preload/webView.ts
Starting with `scrollUp` and `scrollDown`
=> Browser RPC: Content Script remote functions

python/ta/Makefile, python/ta/test/cmpsearch.py, python/ta/typeagent/demo/answer_response_schema.py, python/ta/typeagent/demo/ui.py, python/ta/typeagent/knowpro/collections.py, python/ta/typeagent/knowpro/interfaces.py, python/ta/typeagent/knowpro/query.py
`test/cmpsearch.py` now doesn't just show you the queries to run; it runs the queries and compares the actual answers to the expected ones using a dot product between embeddings.
Run `python test/cmpsearch.py` to try it. This assumes a checkout of the (internal) AISystems-Archive repo exists as a sibling of the TypeAgent repo.
Various small tweaks elsewhere.
=> [python/knowpro] Finish MatchMessagesBooleanExpr subclasses; add automatic evaluation script

ts/packages/agents/browser/package.json, ts/packages/agents/browser/src/agent/planVisualizationClient.mts, ts/packages/agents/browser/src/views/client/plans/app.ts, ts/packages/agents/browser/src/views/client/plans/config.ts, ts/packages/agents/browser/src/views/server/core/baseServer.ts, ts/packages/agents/browser/src/views/server/core/sseManager.ts, ts/packages/agents/browser/src/views/server/core/types.ts, ts/packages/agents/browser/src/views/server/features/pdf/pdfRoutes.ts, ts/packages/agents/browser/src/views/server/features/pdf/pdfService.ts, ts/packages/agents/browser/src/views/server/features/pdf/pdfTypes.ts, ts/packages/agents/browser/src/views/server/features/plans/plansRoutes.ts, ts/packages/agents/browser/src/views/server/features/plans/plansService.ts, ts/packages/agents/browser/src/views/server/features/plans/plansTypes.ts, ts/packages/agents/browser/src/views/server/server.ts
- Move the plan-specific service views code to a features folder.
- Add PDF views service code. This is setting the stage for us to add pdf.js for viewing and collaborating on pdfs
=> Refactor browser views service code

ts/packages/agents/greeting/src/greetingCommandHandler.ts, ts/packages/dispatcher/src/context/memory.ts, ts/packages/dispatcher/src/context/session.ts, ts/packages/dispatcher/src/context/system/systemAgent.ts, ts/packages/dispatcher/src/search/search.ts
Use command `@memory legacy off` to use conversation memory (instead of manager) for lookup.
=> Add a mode to use knowpro for conversation lookup

ts/examples/chat/src/memory/knowproTest.ts, ts/packages/knowPro/src/answerGenerator.ts, ts/packages/knowPro/src/searchLib.ts, ts/packages/knowProTest/src/types.ts
- Anwer Generator: Wrapper to make multiple choice memory answers easier. 
- Bug fixes
=> Memory updates

ts/examples/chat/src/memory/knowproPrinter.ts, ts/packages/agentSdk/src/parameters.ts, ts/packages/dispatcher/src/context/memory.ts, ts/packages/dispatcher/src/context/memoryPrinter.ts, ts/packages/shell/src/renderer/src/setContent.ts
Copy code from knowProPrinter and refactor them.  Can be move to the knowpro library to reuse later.
=> Memory answer command print out result.

ts/packages/agents/browser/scripts/buildExtension.mjs, ts/packages/agents/browser/src/agent/actionHandler.mts, ts/packages/agents/browser/src/extension/contentScript/index.ts, ts/packages/agents/browser/src/extension/contentScript/pdfInterceptor.ts, ts/packages/agents/browser/src/extension/manifest.json, ts/packages/agents/browser/src/extension/serviceWorker/messageHandlers.ts, ts/packages/agents/browser/src/extension/views/pdfView.html, ts/packages/agents/browser/src/extension/views/pdfView.ts, ts/packages/agents/browser/src/views/client/pdf/app.ts, ts/packages/agents/browser/src/views/client/pdf/components/NoteEditor.ts, ts/packages/agents/browser/src/views/client/pdf/pdf-viewer.css, ts/packages/agents/browser/src/views/client/pdf/styles/contextual-toolbar.css, ts/packages/agents/browser/src/views/client/pdf/styles/note-editor.css, ts/packages/agents/browser/src/views/server/features/pdf/pdfRoutes.ts, ts/packages/agents/browser/src/views/server/features/pdf/pdfService.ts, ts/packages/agents/browser/src/views/server/server.mts
- Use our custom PDF view when users navigate to a PDF link in the browser. This has early support for highlights, notes and image annotations as well as integration with the browser agent. This will allow question-answering, knowledge extraction and other interactions in future.
=> Use PDF viewer in the browser

ts/examples/chat/src/memory/knowproMemory.ts, ts/examples/chat/src/memory/knowproTest.ts, ts/packages/knowProTest/src/common.ts, ts/packages/knowProTest/src/logging.ts, ts/packages/knowProTest/src/searchTest.ts
Improved test result collection, logging
=> knowproTest improvements

python/ta/test/cmpsearch.py, python/ta/typeagent/demo/ui.py, python/ta/typeagent/knowpro/reltermsindex.py, python/ta/typeagent/knowpro/search.py
- ui.py: Add special case for '.DDD' to show semantic ref DDD
- cmpsearch.py: Reduce noise in output; format term weights as .3f (was .1f)
- reltermsindex.py: Fix multiset with projection; add a docstring
- **search.py: Fix important bug that turned "or" into "and" in some cases**
=> [python/knowpro] Fix important bug in search.py; and other stuff

ts/.vscode/settings.json, ts/examples/chat/src/memory/knowproTest.ts, ts/packages/knowPro/src/relatedTermsIndex.ts, ts/packages/textPro/package.json, ts/packages/textPro/src/markdown.ts, ts/pnpm-lock.yaml
* Markdown parse + knowledge + tags extraction
* Refinements/refactoring + indexing in DocMemory coming
=> textPro: Markdown knowledge, tags, blocks

ts/packages/knowPro/src/searchQueryTranslator.ts
For case-sensitive file systems.
=> Fix file casing in knowpro

ts/.vscode/launch.json, ts/examples/chat/src/memory/knowproTest.ts, ts/packages/knowPro/src/compileLib.ts, ts/packages/knowPro/src/search.ts, ts/packages/knowPro/src/searchLang.ts, ts/packages/knowPro/src/searchQuerySchema_v2.ts, ts/packages/knowPro/src/searchQueryTranslator.ts, ts/packages/knowPro/test/search.spec.ts, ts/packages/knowProTest/src/knowproCommands.ts, ts/packages/memory/conversation/src/docMemory.ts, ts/packages/memory/conversation/src/docSearchQuerySchema.ts, ts/packages/typeagent/src/schema.ts
* SearchTermGroup validation
* Unit Tests 
* Allow for experimentation with custom query schemas 
* DocMemory
* Scope query improvements 
* Experimental schema with custom instructions for scoped queries
=> DocMemory, knowpro 

ts/packages/knowPro/src/search.ts, ts/packages/knowPro/src/searchLib.ts, ts/packages/textPro/src/markdown.ts
* Fuzzy tag matching
* Markdown import bug
=> Doc Memory: bug fixes

ts/packages/agents/browser/src/agent/actionHandler.mts, ts/packages/agents/browser/src/agent/searchWebMemories.mts, ts/packages/agents/browser/src/extension/serviceWorker/messageHandlers.ts, ts/packages/agents/browser/src/extension/views/entityGraphView.html, ts/packages/agents/browser/src/extension/views/entityGraphView.ts, ts/packages/agents/browser/src/extension/views/entitySidebar.ts, ts/packages/agents/browser/src/extension/views/knowledgeLibrary.css, ts/packages/agents/browser/src/extension/views/knowledgeSearchPanel.ts, ts/packages/agents/browser/src/extension/views/knowledgeUtilities.ts, ts/packages/memory/website/README.md
This pull request introduces new search functionalities (`searchByEntities`, `searchByTopics`, and `hybridSearch`) while also simplifying the `EntityGraphView` interface by removing unused controls and layout-related features. The changes enhance the search capabilities and streamline the graph visualization interface.
* Updated breadcrumb functionality in `entityGraphView.ts` to dynamically display the selected entity name.
* Improved validation logic for graph relationships to handle additional data formats.
=> WebMemories: Update the sidebar and graph display for the entities graph view

ts/packages/shell/src/renderer/src/chatInput.ts, ts/packages/shell/src/renderer/src/chatView.ts, ts/packages/shell/src/renderer/src/speech.ts
Also refactor the `recognizeOnce` to accept handler that return in progress/success/error data, and leave the UI update to the caller.
=> Suppress intellisense menu on voice or injected inputs.

ts/examples/chat/src/memory/knowproTest.ts, ts/packages/knowPro/src/searchLang.ts, ts/packages/knowPro/src/searchQueryTranslator.ts, ts/packages/memory/conversation/src/docMemory.ts, ts/packages/memory/conversation/src/docSearchQuerySchema.ts, ts/packages/textPro/src/markdown.ts
- Better schema comments & indexing
- Refactoring
=> DocMemory: search improvements

ts/packages/shell/src/main/index.ts, ts/packages/shell/src/renderer/assets/styles.less
- Make agent message overflow-x to add scroll if it is too big.
- Give the chat view focus back after a command (for the case where we have an inline browser action)
=> Shell: minor ui fixes

ts/examples/chat/src/memory/knowproTest.ts, ts/packages/knowPro/src/interfaces.ts, ts/packages/knowPro/src/search.ts, ts/packages/knowPro/src/searchLang.ts, ts/packages/textPro/src/markdown.ts
* Lang to query: Improved scope compiler to use both structured and string tags
* documents: extract more structured tags like lists and tables
=> knowPro: Scope improvements

ts/examples/chat/src/knowledgeProc/knowledgeProcessorMemory.ts, ts/examples/chat/src/memory/knowproCommon.ts, ts/examples/chat/src/memory/knowproConversation.ts, ts/examples/chat/src/memory/knowproDataFrame.ts, ts/examples/chat/src/memory/knowproDoc.ts, ts/examples/chat/src/memory/knowproEmail.ts, ts/examples/chat/src/memory/knowproKnowledge.ts, ts/examples/chat/src/memory/knowproMemory.ts, ts/examples/chat/src/memory/knowproPodcast.ts, ts/examples/chat/src/memory/knowproWebsite.ts, ts/examples/examplesLib/src/chalkWriter.ts, ts/packages/knowPro/src/knowledge.ts, ts/packages/knowProTest/src/knowproContext.ts, ts/packages/knowledgeProcessor/src/conversation/knowledge.ts, ts/packages/memory/conversation/src/docMemory.ts, ts/packages/memory/conversation/src/docSearchQuerySchema.ts, ts/packages/memory/conversation/src/memory.ts, ts/packages/textPro/src/markdown.ts
* Markdown Analysis
* Refactor, handle more tags
* Introduce options: Customize what tokens are turned into structured tags
* Doc Memory
* Scoped Query bug fix
* Support more efficient knowledge extractor
* Diagnostics improvements
* Token counting
* Stats printing
=> DocMemory, TextPro improvements

ts/packages/agents/player/src/agent/playerHandlers.ts, ts/packages/agents/player/src/client.ts, ts/packages/agents/player/src/devices.ts, ts/packages/agents/player/src/endpoints.ts, ts/packages/agents/player/src/playback.ts, ts/packages/agents/player/src/volume.ts, ts/packages/cache/src/index.ts, ts/packages/dispatcher/src/translation/requestCompletion.ts
Device might become offline or changed, so query every time we need it.
=> Player: stop caching device id

ts/packages/agents/player/src/devices.ts
Also fix list device to not error if the selected device is not available.
=> Player: remove .local from host name on Mac to selected device

python/ta/tools/utool.py, python/ta/tools/vizcmp.py
* 595de6d5 vizcmp.py: Get scores from Score: headers instead of file trailer
* fc5dcb68 utools.py: Always show output diff even when success differs
* 8147b7f1 utool.py: assign score 0.001 if we have an unexpected answer
* fa4053af utool.py: Add support for Pydantic's Logfire
* fca0f571 vizcmp.py: Simplify footer
* e29246ed vizcmp.py: Sort by average score, not first file's
* f0e7ebfa vizcmp.py: Only sort filenames when using default glob
* d2a6be4c vizcmp.py: Print only basename
* 6b564a20 vizcmp.py: show file names in footer
* 4e72780f vizcmp.py: Display N/A results in bright yellow
=> [python/knowpro] Various improvements to tools

ts/packages/shell/src/main/browserIpc.ts
If the browser extension is not installed there's a potential timing issue that causes the machine to go into a create/close WS loop
- now there's a singular Promise while waiting for port creation
- dropped connections are now throttled
=> Added reentrancy gates when websocket is created/dropped 

ts/examples/chat/src/memory/knowproTest.ts, ts/packages/knowProTest/src/common.ts, ts/packages/knowProTest/src/knowproContext.ts, ts/packages/knowProTest/src/searchTest.ts, ts/packages/knowProTest/src/types.ts, ts/packages/textPro/README.md
Batch testing of scope query schema.
=> knowPro: batch validation updates

ts/examples/chat/src/memory/knowproDoc.ts, ts/examples/chat/src/memory/knowproTest.ts, ts/examples/examplesLib/src/chalkWriter.ts, ts/packages/knowPro/src/searchLang.ts, ts/packages/knowPro/src/searchQuerySchema_v2.ts, ts/packages/knowProTest/src/common.ts, ts/packages/knowProTest/src/searchTest.ts, ts/packages/memory/conversation/src/docSearchQuerySchema.ts, ts/packages/memory/conversation/src/memory.ts
* Scope query schema: bug fixes
* Memory: settings flag to allow auto experimentation of natural language queries with enhanced scope ("where") detection
* Code for fuzzier comparisons of test output
=> Memory improvements

python/ta/TODO.md, python/ta/test/test_interfaces.py, python/ta/typeagent/knowpro/collections.py, python/ta/typeagent/knowpro/interfaces.py, python/ta/typeagent/knowpro/propindex.py, python/ta/typeagent/podcasts/podcast.py
First of the decisions from today's in-person meeting.
=> [python/knowpro] Drop char_ordinal from TextLocation; make TextRange end default to start.chunk_ordinal + 1

ts/examples/chat/src/memory/knowproDoc.ts, ts/packages/knowPro/src/serialization.ts, ts/packages/memory/conversation/README.md, ts/packages/memory/conversation/src/docMemory.ts, ts/packages/memory/conversation/src/memory.ts, ts/packages/memory/conversation/test/docImport.spec.ts, ts/packages/memory/conversation/test/verify.ts, ts/packages/testLib/src/index.ts, ts/packages/testLib/src/test.ts, ts/packages/testLib/src/verify.ts
* Improved Unit Tests for Doc Memory
* API tidying up/improvements
* README and Documentation improvements
=> DocMemory improvements

ts/packages/agents/browser/src/agent/knowledge/knowledgeHandler.mts, ts/packages/agents/browser/src/extension/serviceWorker/messageHandlers.ts, ts/packages/agents/browser/src/extension/views/entityGraphView.html, ts/packages/agents/browser/src/extension/views/extensionServiceBase.ts, ts/packages/agents/browser/src/extension/views/knowledgeLibrary.html, ts/packages/agents/browser/src/extension/views/pageKnowledge.css, ts/packages/agents/browser/src/extension/views/pageKnowledge.html, ts/packages/agents/browser/src/extension/views/pageKnowledge.ts
- Simplify page knowledge extraction steps to "extract" -> "save".
- Update bootstrap icons css to latest edition
- Simplify modules shown in sidepanel
=> Update page knowledge extraction UX

ts/packages/agentSdk/src/command.ts, ts/packages/shell/src/renderer/src/partial.ts
temporarily assign emoji chars in the renderer until plumbed through the agent sdk
=> add emoji char in partial.ts until plumbed through agent sdk

ts/packages/shell/src/main/browserViewManager.ts, ts/packages/shell/src/main/shellWindow.ts, ts/packages/shell/src/preload/index.ts
- https://github.com/microsoft/TypeAgent/issues/1482
- Add Ctrl+E and Ctrl+L as shortcuts to set focus to chat view
=> Fix: Shell: Chat input loses focus after open website action

ts/.vscode/settings.json, ts/examples/chat/src/common.ts, ts/examples/chat/src/memory/knowproAzureSearch.ts, ts/examples/chat/src/memory/knowproMemory.ts, ts/packages/knowPro/src/compileLib.ts, ts/packages/knowPro/src/dataFrame/dataFrameQuery.ts, ts/packages/knowPro/src/search.ts, ts/packages/knowPro/src/searchLib.ts, ts/packages/knowPro/test/search.spec.ts, ts/packages/knowPro/test/verify.ts, ts/packages/memory/storage/src/azSearch/azLucene.ts, ts/packages/memory/storage/src/azSearch/azSemanticRefIndex.ts, ts/packages/memory/storage/src/azSearch/index.ts
Experimentation:
- Azure Search querying
- SearchTermGroup to Lucene syntax compilation
- Test commands
- Refactor to support above
=> knowpro: Azure Search

ts/tools/scripts/elevate.config.json, ts/tools/scripts/elevate.js
* Add config for new Azure Search RBAC roles
* Do async correctly
=> Fix elevate script

ts/examples/chat/src/memory/knowproAzureSearch.ts, ts/examples/chat/src/memory/knowproCommon.ts, ts/examples/chat/src/memory/knowproMemory.ts, ts/packages/knowPro/src/textLocationIndex.ts, ts/packages/memory/storage/src/azSearch/README.md, ts/packages/memory/storage/src/azSearch/azLucene.ts, ts/packages/memory/storage/src/azSearch/azSemanticRefIndex.ts
Ongoing experimentation:
* Cleaner schema + schema code
* SearchTermGroup -> Lucene... support non-property terms improvements
* Test commands:
* azSearch command: support non-qualified terms
* Improved index upload
* ReadMe
=> knowPro: Azure Search experimentation

ts/examples/chat/src/memory/knowproAzSearch.ts, ts/packages/memory/storage/src/azSearch/azQuery.ts, ts/packages/memory/storage/src/azSearch/azSemanticRefIndex.ts
Ongoing experiments:
* Scope: textRange--> azSearch filters
* term.relatedTerms --> match expressions
* apply term weights as boosts 
* Test Command updates:
* date ranges
* ordinal range
=> knowPro: azSearch filters

docs/content/help/dev.md, ts/packages/agents/browser/src/agent/actionHandler.mts, ts/packages/agents/browser/src/agent/actionsSchema.mts, ts/packages/agents/browser/src/agent/rpc/externalBrowserControlClient.mts, ts/packages/agents/browser/src/common/browserControl.mts, ts/packages/agents/browser/src/extension/serviceWorker/externalBrowserControlServer.ts, ts/packages/dispatcher/src/translation/matchRequest.ts, ts/packages/shell/package.json, ts/packages/shell/src/main/inlineBrowserControl.ts, ts/pnpm-lock.yaml
- Added switchTabs action to the inline browser action.  ExternalBrowser option has some dependency issues so is currently disabled.
- Added new/current/existing tab disambiguation to openWebPage
=> Added switchTabs action and added tab disambiguation for "openWebPage"

ts/examples/chat/src/memory/knowproAzSearch.ts, ts/examples/chat/src/memoryWriter.ts, ts/packages/memory/storage/src/azSearch/README.md, ts/packages/memory/storage/src/azSearch/azSearchCommon.ts, ts/packages/memory/storage/src/azSearch/azSearchIndex.ts, ts/packages/memory/storage/src/azSearch/azSemanticRefIndex.ts, ts/packages/memory/storage/src/azSearch/azTermsVectorIndex.ts, ts/packages/memory/storage/src/azSearch/azVectorIndex.ts, ts/packages/memory/storage/src/azSearch/index.ts
Ongoing experiments:
* Azure Search vector index
* create
* query
* Related Term Index
* Ingest local index and embeddings into Azure
* query   
* Test commands
=> knowpro: Azure vector experiments   

ts/packages/agents/browser/src/agent/actionsSchema.mts
- Search action too aggressive, detuning it a bit.
=> De-tune search Action

ts/packages/shell/src/main/index.ts, ts/packages/shell/src/main/shellSettings.ts, ts/packages/shell/src/main/shellWindow.ts, ts/packages/shell/src/preload/shellSettingsType.ts, ts/packages/shell/src/renderer/src/settingsView.ts, ts/packages/shell/src/renderer/viewHost.html
Initial implementation of vertical layout mode, putting the chat pane at the bottom and make the content area always visible.
Off by default.  Use `@shell set ui.verticalLayout true` to turn it on.
=> Shell: add vertical layout mode

ts/packages/agents/browser/src/agent/actionHandler.mts, ts/packages/agents/browser/src/agent/actionsSchema.mts, ts/packages/agents/browser/src/agent/rpc/externalBrowserControlClient.mts, ts/packages/agents/browser/src/common/browserControl.mts, ts/packages/agents/browser/src/extension/serviceWorker/externalBrowserControlServer.ts, ts/packages/shell/src/main/browserViewManager.ts, ts/packages/shell/src/main/inlineBrowserControl.ts, ts/packages/shell/src/main/shellWindow.ts, ts/packages/shell/src/renderer/viewHost.html
- fixed the tab removal bug
- added "closeAllTabs" action
=> Fixed tab removal issue, added "closeAllTabs" action

ts/packages/defaultAgentProvider/package.json, ts/packages/defaultAgentProvider/test/data/translate-mcpfs-e2e.json, ts/packages/dispatcher/src/execute/pendingActions.ts, ts/pnpm-lock.yaml
=> Fix exception for pending request

ts/packages/agents/browser/src/agent/actionHandler.mts, ts/packages/agents/browser/src/agent/browserConnector.mts, ts/packages/agents/browser/src/agent/knowledge/knowledgeHandler.mts, ts/packages/agents/browser/src/agent/knowledge/knowledgeProgressEvents.mts, ts/packages/agents/browser/src/agent/knowledge/knowledgeWebSocketBridge.mts, ts/packages/agents/browser/src/agent/rpc/externalBrowserControlClient.mts, ts/packages/agents/browser/src/common/browserControl.mts, ts/packages/agents/browser/src/extension/serviceWorker/externalBrowserControlServer.ts, ts/packages/agents/browser/src/extension/serviceWorker/index.ts, ts/packages/agents/browser/src/extension/views/extensionServiceBase.ts, ts/packages/agents/browser/src/extension/views/knowledgeLibrary.ts, ts/packages/shell/src/main/extensionStorage.ts, ts/packages/shell/src/main/index.ts, ts/packages/shell/src/main/inlineBrowserControl.ts, ts/packages/shell/src/main/shellWindow.ts, ts/packages/shell/src/preload/webView.ts
- Enable knowledge extraction when handling openWebPage() action
- Show knowledge extraction progress in the chat input section
- Persist auto-indexing setting when in electron
=> Show knowledge extraction progress in the chat input section

ts/packages/agentSdk/src/command.ts, ts/packages/dispatcher/src/translation/requestCompletion.ts, ts/packages/shell/src/main/agent.ts, ts/packages/shell/src/renderer/src/partial.ts, ts/packages/shell/src/renderer/src/search.ts, ts/packages/shell/src/renderer/src/templateEditor.ts
To prepare for remoting the popup menu to another overlay view.
Also add property to indicate whether a completion group is sorted, which will be prioritize and alternate with other completion group.  Default to false, so that the completion will be alphabetically sorted and not sliced with other groups.
=> Shell: Refactor UI code from SearchMenu

ts/examples/chat/src/memory/knowproAzSearch.ts, ts/packages/memory/storage/src/azSearch/azQuery.ts, ts/packages/memory/storage/src/azSearch/azSemanticRefIndex.ts
Experiment with full scope expressions using Azure Search
=> Memory and Azure search 

ts/packages/agents/browser/src/agent/actionHandler.mts, ts/packages/agents/browser/src/extension/serviceWorker/externalBrowserControlServer.ts, ts/packages/agents/browser/src/extension/views/pageKnowledge.ts, ts/packages/shell/src/main/index.ts, ts/packages/shell/src/preload/chatView.ts, ts/packages/shell/src/preload/electronTypes.ts, ts/packages/shell/src/renderer/src/setContent.ts, ts/packages/shell/src/renderer/src/webSocketAPI.ts
- register custom protocol for extension views
- update dompurify rules to preserve links with the custom protocol
=> WebKnowledge: making links in the chat view clickable and open in the inline browser

ts/packages/agents/player/src/agent/playerHandlers.ts, ts/packages/agents/player/src/agent/playerSchema.json, ts/packages/agents/player/src/client.ts, ts/packages/agents/player/src/userData.ts
add intellisense for getPlaylist
=> add playlist intellisense

ts/packages/agents/browser/src/agent/actionHandler.mts, ts/packages/agents/browser/src/extension/serviceWorker/index.ts, ts/packages/shell/src/main/browserViewManager.ts
- this triggers the extraction operation if user navigates by clicking on links. We also have dedupe to account for refresh and other cases that may send multiple navigation messages
=> WebKnowledge: Enable knowledge extraction on page navigation

ts/packages/agents/browser/src/agent/actionHandler.mts, ts/packages/agents/browser/src/agent/knowledge/knowledgeHandler.mts, ts/packages/defaultAgentProvider/data/config.json
- `@browser extractKnowledge` runs knowledge extraction on the current page. If the page is already in the index, the command shows the current indexed knowledge.
- `@browser autoIndex` set of commands can show current auto-indexing status, switch auto-indexing on/off, and set the indexing delay.
=> WebKnowledge: Adding commands for extracting knowledge and managing knowledge settings

ts/packages/agents/browser/src/extension/views/entityGraphView.css, ts/packages/agents/browser/src/extension/views/entityGraphView.html, ts/packages/agents/browser/src/extension/views/entityGraphView.ts, ts/packages/agents/browser/src/extension/views/entityGraphVisualizer.ts, ts/packages/agents/browser/src/extension/views/entitySidebar.ts, ts/packages/agents/browser/src/extension/views/graphDataProvider.ts
- Introduce global and detail instances - global and detail. Navigation operations change the data and visibility for these views, giving faster interactions
=> Speed up navigation in entity graph views by maintaining two cytoscape instances

ts/packages/agents/player/src/agent/playerSchema.json, ts/packages/agents/player/src/agent/playerSchema.ts, ts/packages/agents/player/src/client.ts, ts/packages/agents/player/src/endpoints.ts
update playlist list on delete playlist
new action that adds current track to named playlist
=> Delete playlist upd

ts/packages/shell/src/main/index.ts, ts/packages/shell/src/main/instance.ts, ts/packages/shell/src/main/shellWindow.ts
- Ctrl-L and Ctrl-E will now show and focus on chat input (even from minimized state)
- Second-Instance activation will also focus on chat input
- Make sure we report error until the shell window is "ready"
=> Shell: improve load error and global shortcuts

dotnet/typeagent/README.md, dotnet/typeagent/examples/examplesLib/CommandLine/ConsoleWriter.cs, dotnet/typeagent/examples/examplesLib/KnowProWriter.cs, dotnet/typeagent/examples/knowProConsole/PodcastCommands.cs, dotnet/typeagent/src/common/EnumerationExtensions.cs, dotnet/typeagent/src/common/ListExtensions.cs, dotnet/typeagent/src/knowpro/Conversation.cs, dotnet/typeagent/src/knowpro/IConversation.cs, dotnet/typeagent/src/knowpro/IMessageCollection.cs, dotnet/typeagent/src/knowpro/IStorageProvider.cs, dotnet/typeagent/src/knowpro/Query/LookupExtensions.cs, dotnet/typeagent/src/knowpro/Query/MatchTermExpr.cs, dotnet/typeagent/src/knowpro/Query/QueryEvalContext.cs, dotnet/typeagent/src/knowpro/Query/TextRangesInScope.cs, dotnet/typeagent/src/knowpro/Serializer.cs, dotnet/typeagent/src/knowproStorage/Sqlite/SqliteDatabase.cs, dotnet/typeagent/src/knowproStorage/Sqlite/SqliteMessageCollection.cs, dotnet/typeagent/src/knowproStorage/Sqlite/SqliteStorageProvider.cs, dotnet/typeagent/src/knowproTest/KnowProContext.cs
* Refactored interfaces for cleaner programming model
* Non-generic and generic IConversation both work; worked around Type covariance issues
* Sqlite Provider improvements
* Starting query processor port
=> knowpro.NET updates

ts/packages/shell/src/renderer/src/main.ts
=> Fixed inadvertent check-in.

python/ta/tools/test_email.py, python/ta/typeagent/emails/email_import.py, python/ta/typeagent/emails/email_message.py, python/ta/typeagent/knowpro/answers.py
Email import:
* Chunk large message bodies
* Gmail testing
* Test REPL improvements
* Bug fixes
=> knowpro.py: Email example
